
/*
 * This file was automatically generated from unicode
 * charset definition files http://unicode.org/Public/MAPPINGS/
 * using the script twin/scripts/helper-from-unicode.org.bash
 *
 * PLEASE DO NOT EDIT!
 */


#ifndef _TUTF_APPLE_JAPANESE_H
#define _TUTF_APPLE_JAPANESE_H

#define T_APPLE_JAPANESE_UNDEFINED_0000	0x0000
#define T_APPLE_JAPANESE_UNDEFINED_0001	0x0001
#define T_APPLE_JAPANESE_UNDEFINED_0002	0x0002
#define T_APPLE_JAPANESE_UNDEFINED_0003	0x0003
#define T_APPLE_JAPANESE_UNDEFINED_0004	0x0004
#define T_APPLE_JAPANESE_UNDEFINED_0005	0x0005
#define T_APPLE_JAPANESE_UNDEFINED_0006	0x0006
#define T_APPLE_JAPANESE_UNDEFINED_0007	0x0007
#define T_APPLE_JAPANESE_UNDEFINED_0008	0x0008
#define T_APPLE_JAPANESE_UNDEFINED_0009	0x0009
#define T_APPLE_JAPANESE_UNDEFINED_000A	0x000A
#define T_APPLE_JAPANESE_UNDEFINED_000B	0x000B
#define T_APPLE_JAPANESE_UNDEFINED_000C	0x000C
#define T_APPLE_JAPANESE_UNDEFINED_000D	0x000D
#define T_APPLE_JAPANESE_UNDEFINED_000E	0x000E
#define T_APPLE_JAPANESE_UNDEFINED_000F	0x000F
#define T_APPLE_JAPANESE_UNDEFINED_0010	0x0010
#define T_APPLE_JAPANESE_UNDEFINED_0011	0x0011
#define T_APPLE_JAPANESE_UNDEFINED_0012	0x0012
#define T_APPLE_JAPANESE_UNDEFINED_0013	0x0013
#define T_APPLE_JAPANESE_UNDEFINED_0014	0x0014
#define T_APPLE_JAPANESE_UNDEFINED_0015	0x0015
#define T_APPLE_JAPANESE_UNDEFINED_0016	0x0016
#define T_APPLE_JAPANESE_UNDEFINED_0017	0x0017
#define T_APPLE_JAPANESE_UNDEFINED_0018	0x0018
#define T_APPLE_JAPANESE_UNDEFINED_0019	0x0019
#define T_APPLE_JAPANESE_UNDEFINED_001A	0x001A
#define T_APPLE_JAPANESE_UNDEFINED_001B	0x001B
#define T_APPLE_JAPANESE_UNDEFINED_001C	0x001C
#define T_APPLE_JAPANESE_UNDEFINED_001D	0x001D
#define T_APPLE_JAPANESE_UNDEFINED_001E	0x001E
#define T_APPLE_JAPANESE_UNDEFINED_001F	0x001F
#define T_APPLE_JAPANESE_SPACE	0x0020
#define T_APPLE_JAPANESE_EXCLAMATION_MARK	0x0021
#define T_APPLE_JAPANESE_QUOTATION_MARK	0x0022
#define T_APPLE_JAPANESE_NUMBER_SIGN	0x0023
#define T_APPLE_JAPANESE_DOLLAR_SIGN	0x0024
#define T_APPLE_JAPANESE_PERCENT_SIGN	0x0025
#define T_APPLE_JAPANESE_AMPERSAND	0x0026
#define T_APPLE_JAPANESE_APOSTROPHE	0x0027
#define T_APPLE_JAPANESE_LEFT_PARENTHESIS	0x0028
#define T_APPLE_JAPANESE_RIGHT_PARENTHESIS	0x0029
#define T_APPLE_JAPANESE_ASTERISK	0x002A
#define T_APPLE_JAPANESE_PLUS_SIGN	0x002B
#define T_APPLE_JAPANESE_COMMA	0x002C
#define T_APPLE_JAPANESE_HYPHEN_MINUS	0x002D
#define T_APPLE_JAPANESE_FULL_STOP	0x002E
#define T_APPLE_JAPANESE_SOLIDUS	0x002F
#define T_APPLE_JAPANESE_DIGIT_ZERO	0x0030
#define T_APPLE_JAPANESE_DIGIT_ONE	0x0031
#define T_APPLE_JAPANESE_DIGIT_TWO	0x0032
#define T_APPLE_JAPANESE_DIGIT_THREE	0x0033
#define T_APPLE_JAPANESE_DIGIT_FOUR	0x0034
#define T_APPLE_JAPANESE_DIGIT_FIVE	0x0035
#define T_APPLE_JAPANESE_DIGIT_SIX	0x0036
#define T_APPLE_JAPANESE_DIGIT_SEVEN	0x0037
#define T_APPLE_JAPANESE_DIGIT_EIGHT	0x0038
#define T_APPLE_JAPANESE_DIGIT_NINE	0x0039
#define T_APPLE_JAPANESE_COLON	0x003A
#define T_APPLE_JAPANESE_SEMICOLON	0x003B
#define T_APPLE_JAPANESE_LESS_THAN_SIGN	0x003C
#define T_APPLE_JAPANESE_EQUALS_SIGN	0x003D
#define T_APPLE_JAPANESE_GREATER_THAN_SIGN	0x003E
#define T_APPLE_JAPANESE_QUESTION_MARK	0x003F
#define T_APPLE_JAPANESE_COMMERCIAL_AT	0x0040
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_A	0x0041
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_B	0x0042
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_C	0x0043
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_D	0x0044
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_E	0x0045
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_F	0x0046
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_G	0x0047
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_H	0x0048
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_I	0x0049
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_J	0x004A
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_K	0x004B
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_L	0x004C
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_M	0x004D
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_N	0x004E
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_O	0x004F
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_P	0x0050
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_Q	0x0051
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_R	0x0052
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_S	0x0053
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_T	0x0054
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_U	0x0055
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_V	0x0056
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_W	0x0057
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_X	0x0058
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_Y	0x0059
#define T_APPLE_JAPANESE_LATIN_CAPITAL_LETTER_Z	0x005A
#define T_APPLE_JAPANESE_LEFT_SQUARE_BRACKET	0x005B
#define T_APPLE_JAPANESE_YEN_SIGN	0x005C
#define T_APPLE_JAPANESE_RIGHT_SQUARE_BRACKET	0x005D
#define T_APPLE_JAPANESE_CIRCUMFLEX_ACCENT	0x005E
#define T_APPLE_JAPANESE_LOW_LINE	0x005F
#define T_APPLE_JAPANESE_GRAVE_ACCENT	0x0060
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_A	0x0061
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_B	0x0062
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_C	0x0063
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_D	0x0064
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_E	0x0065
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_F	0x0066
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_G	0x0067
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_H	0x0068
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_I	0x0069
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_J	0x006A
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_K	0x006B
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_L	0x006C
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_M	0x006D
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_N	0x006E
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_O	0x006F
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_P	0x0070
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_Q	0x0071
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_R	0x0072
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_S	0x0073
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_T	0x0074
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_U	0x0075
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_V	0x0076
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_W	0x0077
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_X	0x0078
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_Y	0x0079
#define T_APPLE_JAPANESE_LATIN_SMALL_LETTER_Z	0x007A
#define T_APPLE_JAPANESE_LEFT_CURLY_BRACKET	0x007B
#define T_APPLE_JAPANESE_VERTICAL_LINE	0x007C
#define T_APPLE_JAPANESE_RIGHT_CURLY_BRACKET	0x007D
#define T_APPLE_JAPANESE_TILDE	0x007E
#define T_APPLE_JAPANESE_UNDEFINED_007F	0x007F
#define T_APPLE_JAPANESE_REVERSE_SOLIDUS	0x0080
#define T_APPLE_JAPANESE_UNDEFINED_0081	0x0081
#define T_APPLE_JAPANESE_UNDEFINED_0082	0x0082
#define T_APPLE_JAPANESE_UNDEFINED_0083	0x0083
#define T_APPLE_JAPANESE_UNDEFINED_0084	0x0084
#define T_APPLE_JAPANESE_UNDEFINED_0085	0x0085
#define T_APPLE_JAPANESE_UNDEFINED_0086	0x0086
#define T_APPLE_JAPANESE_UNDEFINED_0087	0x0087
#define T_APPLE_JAPANESE_UNDEFINED_0088	0x0088
#define T_APPLE_JAPANESE_UNDEFINED_0089	0x0089
#define T_APPLE_JAPANESE_UNDEFINED_008A	0x008A
#define T_APPLE_JAPANESE_UNDEFINED_008B	0x008B
#define T_APPLE_JAPANESE_UNDEFINED_008C	0x008C
#define T_APPLE_JAPANESE_UNDEFINED_008D	0x008D
#define T_APPLE_JAPANESE_UNDEFINED_008E	0x008E
#define T_APPLE_JAPANESE_UNDEFINED_008F	0x008F
#define T_APPLE_JAPANESE_UNDEFINED_0090	0x0090
#define T_APPLE_JAPANESE_UNDEFINED_0091	0x0091
#define T_APPLE_JAPANESE_UNDEFINED_0092	0x0092
#define T_APPLE_JAPANESE_UNDEFINED_0093	0x0093
#define T_APPLE_JAPANESE_UNDEFINED_0094	0x0094
#define T_APPLE_JAPANESE_UNDEFINED_0095	0x0095
#define T_APPLE_JAPANESE_UNDEFINED_0096	0x0096
#define T_APPLE_JAPANESE_UNDEFINED_0097	0x0097
#define T_APPLE_JAPANESE_UNDEFINED_0098	0x0098
#define T_APPLE_JAPANESE_UNDEFINED_0099	0x0099
#define T_APPLE_JAPANESE_UNDEFINED_009A	0x009A
#define T_APPLE_JAPANESE_UNDEFINED_009B	0x009B
#define T_APPLE_JAPANESE_UNDEFINED_009C	0x009C
#define T_APPLE_JAPANESE_UNDEFINED_009D	0x009D
#define T_APPLE_JAPANESE_UNDEFINED_009E	0x009E
#define T_APPLE_JAPANESE_UNDEFINED_009F	0x009F
#define T_APPLE_JAPANESE_NO_BREAK_SPACE	0x00A0
#define T_APPLE_JAPANESE_HALFWIDTH_IDEOGRAPHIC_FULL_STOP	0x00A1
#define T_APPLE_JAPANESE_HALFWIDTH_LEFT_CORNER_BRACKET	0x00A2
#define T_APPLE_JAPANESE_HALFWIDTH_RIGHT_CORNER_BRACKET	0x00A3
#define T_APPLE_JAPANESE_HALFWIDTH_IDEOGRAPHIC_COMMA	0x00A4
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_MIDDLE_DOT	0x00A5
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_WO	0x00A6
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_A	0x00A7
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_I	0x00A8
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_U	0x00A9
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_E	0x00AA
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_O	0x00AB
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_YA	0x00AC
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_YU	0x00AD
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_YO	0x00AE
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SMALL_TU	0x00AF
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_HIRAGANA_PROLONGED_SOUND_MARK	0x00B0
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_A	0x00B1
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_I	0x00B2
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_U	0x00B3
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_E	0x00B4
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_O	0x00B5
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_KA	0x00B6
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_KI	0x00B7
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_KU	0x00B8
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_KE	0x00B9
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_KO	0x00BA
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SA	0x00BB
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SI	0x00BC
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SU	0x00BD
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SE	0x00BE
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_SO	0x00BF
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_TA	0x00C0
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_TI	0x00C1
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_TU	0x00C2
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_TE	0x00C3
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_TO	0x00C4
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_NA	0x00C5
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_NI	0x00C6
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_NU	0x00C7
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_NE	0x00C8
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_NO	0x00C9
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_HA	0x00CA
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_HI	0x00CB
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_HU	0x00CC
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_HE	0x00CD
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_HO	0x00CE
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_MA	0x00CF
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_MI	0x00D0
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_MU	0x00D1
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_ME	0x00D2
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_MO	0x00D3
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_YA	0x00D4
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_YU	0x00D5
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_YO	0x00D6
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_RA	0x00D7
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_RI	0x00D8
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_RU	0x00D9
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_RE	0x00DA
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_RO	0x00DB
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_WA	0x00DC
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_LETTER_N	0x00DD
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_VOICED_SOUND_MARK	0x00DE
#define T_APPLE_JAPANESE_HALFWIDTH_KATAKANA_SEMI_VOICED_SOUND_MARK	0x00DF
#define T_APPLE_JAPANESE_UNDEFINED_00E0	0x00E0
#define T_APPLE_JAPANESE_UNDEFINED_00E1	0x00E1
#define T_APPLE_JAPANESE_UNDEFINED_00E2	0x00E2
#define T_APPLE_JAPANESE_UNDEFINED_00E3	0x00E3
#define T_APPLE_JAPANESE_UNDEFINED_00E4	0x00E4
#define T_APPLE_JAPANESE_UNDEFINED_00E5	0x00E5
#define T_APPLE_JAPANESE_UNDEFINED_00E6	0x00E6
#define T_APPLE_JAPANESE_UNDEFINED_00E7	0x00E7
#define T_APPLE_JAPANESE_UNDEFINED_00E8	0x00E8
#define T_APPLE_JAPANESE_UNDEFINED_00E9	0x00E9
#define T_APPLE_JAPANESE_UNDEFINED_00EA	0x00EA
#define T_APPLE_JAPANESE_UNDEFINED_00EB	0x00EB
#define T_APPLE_JAPANESE_UNDEFINED_00EC	0x00EC
#define T_APPLE_JAPANESE_UNDEFINED_00ED	0x00ED
#define T_APPLE_JAPANESE_UNDEFINED_00EE	0x00EE
#define T_APPLE_JAPANESE_UNDEFINED_00EF	0x00EF
#define T_APPLE_JAPANESE_UNDEFINED_00F0	0x00F0
#define T_APPLE_JAPANESE_UNDEFINED_00F1	0x00F1
#define T_APPLE_JAPANESE_UNDEFINED_00F2	0x00F2
#define T_APPLE_JAPANESE_UNDEFINED_00F3	0x00F3
#define T_APPLE_JAPANESE_UNDEFINED_00F4	0x00F4
#define T_APPLE_JAPANESE_UNDEFINED_00F5	0x00F5
#define T_APPLE_JAPANESE_UNDEFINED_00F6	0x00F6
#define T_APPLE_JAPANESE_UNDEFINED_00F7	0x00F7
#define T_APPLE_JAPANESE_UNDEFINED_00F8	0x00F8
#define T_APPLE_JAPANESE_UNDEFINED_00F9	0x00F9
#define T_APPLE_JAPANESE_UNDEFINED_00FA	0x00FA
#define T_APPLE_JAPANESE_UNDEFINED_00FB	0x00FB
#define T_APPLE_JAPANESE_UNDEFINED_00FC	0x00FC
#define T_APPLE_JAPANESE_COPYRIGHT_SIGN	0x00FD
#define T_APPLE_JAPANESE_TRADE_MARK_SIGN	0x00FE
#define T_APPLE_JAPANESE_UNDEFINED_00FF	0x00FF

/* list of all characters */
#define T_LIST_APPLE_JAPANESE(EL) \
    EL(_SPACE) \
    EL(_EXCLAMATION_MARK) \
    EL(_QUOTATION_MARK) \
    EL(_NUMBER_SIGN) \
    EL(_DOLLAR_SIGN) \
    EL(_PERCENT_SIGN) \
    EL(_AMPERSAND) \
    EL(_APOSTROPHE) \
    EL(_LEFT_PARENTHESIS) \
    EL(_RIGHT_PARENTHESIS) \
    EL(_ASTERISK) \
    EL(_PLUS_SIGN) \
    EL(_COMMA) \
    EL(_HYPHEN_MINUS) \
    EL(_FULL_STOP) \
    EL(_SOLIDUS) \
    EL(_DIGIT_ZERO) \
    EL(_DIGIT_ONE) \
    EL(_DIGIT_TWO) \
    EL(_DIGIT_THREE) \
    EL(_DIGIT_FOUR) \
    EL(_DIGIT_FIVE) \
    EL(_DIGIT_SIX) \
    EL(_DIGIT_SEVEN) \
    EL(_DIGIT_EIGHT) \
    EL(_DIGIT_NINE) \
    EL(_COLON) \
    EL(_SEMICOLON) \
    EL(_LESS_THAN_SIGN) \
    EL(_EQUALS_SIGN) \
    EL(_GREATER_THAN_SIGN) \
    EL(_QUESTION_MARK) \
    EL(_COMMERCIAL_AT) \
    EL(_LATIN_CAPITAL_LETTER_A) \
    EL(_LATIN_CAPITAL_LETTER_B) \
    EL(_LATIN_CAPITAL_LETTER_C) \
    EL(_LATIN_CAPITAL_LETTER_D) \
    EL(_LATIN_CAPITAL_LETTER_E) \
    EL(_LATIN_CAPITAL_LETTER_F) \
    EL(_LATIN_CAPITAL_LETTER_G) \
    EL(_LATIN_CAPITAL_LETTER_H) \
    EL(_LATIN_CAPITAL_LETTER_I) \
    EL(_LATIN_CAPITAL_LETTER_J) \
    EL(_LATIN_CAPITAL_LETTER_K) \
    EL(_LATIN_CAPITAL_LETTER_L) \
    EL(_LATIN_CAPITAL_LETTER_M) \
    EL(_LATIN_CAPITAL_LETTER_N) \
    EL(_LATIN_CAPITAL_LETTER_O) \
    EL(_LATIN_CAPITAL_LETTER_P) \
    EL(_LATIN_CAPITAL_LETTER_Q) \
    EL(_LATIN_CAPITAL_LETTER_R) \
    EL(_LATIN_CAPITAL_LETTER_S) \
    EL(_LATIN_CAPITAL_LETTER_T) \
    EL(_LATIN_CAPITAL_LETTER_U) \
    EL(_LATIN_CAPITAL_LETTER_V) \
    EL(_LATIN_CAPITAL_LETTER_W) \
    EL(_LATIN_CAPITAL_LETTER_X) \
    EL(_LATIN_CAPITAL_LETTER_Y) \
    EL(_LATIN_CAPITAL_LETTER_Z) \
    EL(_LEFT_SQUARE_BRACKET) \
    EL(_YEN_SIGN) \
    EL(_RIGHT_SQUARE_BRACKET) \
    EL(_CIRCUMFLEX_ACCENT) \
    EL(_LOW_LINE) \
    EL(_GRAVE_ACCENT) \
    EL(_LATIN_SMALL_LETTER_A) \
    EL(_LATIN_SMALL_LETTER_B) \
    EL(_LATIN_SMALL_LETTER_C) \
    EL(_LATIN_SMALL_LETTER_D) \
    EL(_LATIN_SMALL_LETTER_E) \
    EL(_LATIN_SMALL_LETTER_F) \
    EL(_LATIN_SMALL_LETTER_G) \
    EL(_LATIN_SMALL_LETTER_H) \
    EL(_LATIN_SMALL_LETTER_I) \
    EL(_LATIN_SMALL_LETTER_J) \
    EL(_LATIN_SMALL_LETTER_K) \
    EL(_LATIN_SMALL_LETTER_L) \
    EL(_LATIN_SMALL_LETTER_M) \
    EL(_LATIN_SMALL_LETTER_N) \
    EL(_LATIN_SMALL_LETTER_O) \
    EL(_LATIN_SMALL_LETTER_P) \
    EL(_LATIN_SMALL_LETTER_Q) \
    EL(_LATIN_SMALL_LETTER_R) \
    EL(_LATIN_SMALL_LETTER_S) \
    EL(_LATIN_SMALL_LETTER_T) \
    EL(_LATIN_SMALL_LETTER_U) \
    EL(_LATIN_SMALL_LETTER_V) \
    EL(_LATIN_SMALL_LETTER_W) \
    EL(_LATIN_SMALL_LETTER_X) \
    EL(_LATIN_SMALL_LETTER_Y) \
    EL(_LATIN_SMALL_LETTER_Z) \
    EL(_LEFT_CURLY_BRACKET) \
    EL(_VERTICAL_LINE) \
    EL(_RIGHT_CURLY_BRACKET) \
    EL(_TILDE) \
    EL(_REVERSE_SOLIDUS) \
    EL(_NO_BREAK_SPACE) \
    EL(_HALFWIDTH_IDEOGRAPHIC_FULL_STOP) \
    EL(_HALFWIDTH_LEFT_CORNER_BRACKET) \
    EL(_HALFWIDTH_RIGHT_CORNER_BRACKET) \
    EL(_HALFWIDTH_IDEOGRAPHIC_COMMA) \
    EL(_HALFWIDTH_KATAKANA_MIDDLE_DOT) \
    EL(_HALFWIDTH_KATAKANA_LETTER_WO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_A) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_I) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_U) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_E) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_O) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_YA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_YU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_YO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_TU) \
    EL(_HALFWIDTH_KATAKANA_HIRAGANA_PROLONGED_SOUND_MARK) \
    EL(_HALFWIDTH_KATAKANA_LETTER_A) \
    EL(_HALFWIDTH_KATAKANA_LETTER_I) \
    EL(_HALFWIDTH_KATAKANA_LETTER_U) \
    EL(_HALFWIDTH_KATAKANA_LETTER_E) \
    EL(_HALFWIDTH_KATAKANA_LETTER_O) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_ME) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_YA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_YU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_YO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_WA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_N) \
    EL(_HALFWIDTH_KATAKANA_VOICED_SOUND_MARK) \
    EL(_HALFWIDTH_KATAKANA_SEMI_VOICED_SOUND_MARK) \
    EL(_COPYRIGHT_SIGN) \
    EL(_TRADE_MARK_SIGN)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_APPLE_JAPANESE(EL) \
    EL(_YEN_SIGN) \
    EL(_REVERSE_SOLIDUS) \
    EL(_HALFWIDTH_IDEOGRAPHIC_FULL_STOP) \
    EL(_HALFWIDTH_LEFT_CORNER_BRACKET) \
    EL(_HALFWIDTH_RIGHT_CORNER_BRACKET) \
    EL(_HALFWIDTH_IDEOGRAPHIC_COMMA) \
    EL(_HALFWIDTH_KATAKANA_MIDDLE_DOT) \
    EL(_HALFWIDTH_KATAKANA_LETTER_WO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_A) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_I) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_U) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_E) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_O) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_YA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_YU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_YO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SMALL_TU) \
    EL(_HALFWIDTH_KATAKANA_HIRAGANA_PROLONGED_SOUND_MARK) \
    EL(_HALFWIDTH_KATAKANA_LETTER_A) \
    EL(_HALFWIDTH_KATAKANA_LETTER_I) \
    EL(_HALFWIDTH_KATAKANA_LETTER_U) \
    EL(_HALFWIDTH_KATAKANA_LETTER_E) \
    EL(_HALFWIDTH_KATAKANA_LETTER_O) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_KO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_SO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_TO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_NO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_HO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_ME) \
    EL(_HALFWIDTH_KATAKANA_LETTER_MO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_YA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_YU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_YO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RI) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RU) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RE) \
    EL(_HALFWIDTH_KATAKANA_LETTER_RO) \
    EL(_HALFWIDTH_KATAKANA_LETTER_WA) \
    EL(_HALFWIDTH_KATAKANA_LETTER_N) \
    EL(_HALFWIDTH_KATAKANA_VOICED_SOUND_MARK) \
    EL(_HALFWIDTH_KATAKANA_SEMI_VOICED_SOUND_MARK) \
    EL(_COPYRIGHT_SIGN) \
    EL(_TRADE_MARK_SIGN)


#endif /* _TUTF_APPLE_JAPANESE_H */
