
/*
 * This file was automatically generated from unicode
 * charset definition files http://unicode.org/Public/MAPPINGS/
 * using the script twin/scripts/helper-from-unicode.org.bash
 *
 * PLEASE DO NOT EDIT!
 */


#ifndef _TUTF_APPLE_DINGBATS_H
#define _TUTF_APPLE_DINGBATS_H

#define T_APPLE_DINGBATS_UNDEFINED_0000	0x0000
#define T_APPLE_DINGBATS_UNDEFINED_0001	0x0001
#define T_APPLE_DINGBATS_UNDEFINED_0002	0x0002
#define T_APPLE_DINGBATS_UNDEFINED_0003	0x0003
#define T_APPLE_DINGBATS_UNDEFINED_0004	0x0004
#define T_APPLE_DINGBATS_UNDEFINED_0005	0x0005
#define T_APPLE_DINGBATS_UNDEFINED_0006	0x0006
#define T_APPLE_DINGBATS_UNDEFINED_0007	0x0007
#define T_APPLE_DINGBATS_UNDEFINED_0008	0x0008
#define T_APPLE_DINGBATS_UNDEFINED_0009	0x0009
#define T_APPLE_DINGBATS_UNDEFINED_000A	0x000A
#define T_APPLE_DINGBATS_UNDEFINED_000B	0x000B
#define T_APPLE_DINGBATS_UNDEFINED_000C	0x000C
#define T_APPLE_DINGBATS_UNDEFINED_000D	0x000D
#define T_APPLE_DINGBATS_UNDEFINED_000E	0x000E
#define T_APPLE_DINGBATS_UNDEFINED_000F	0x000F
#define T_APPLE_DINGBATS_UNDEFINED_0010	0x0010
#define T_APPLE_DINGBATS_UNDEFINED_0011	0x0011
#define T_APPLE_DINGBATS_UNDEFINED_0012	0x0012
#define T_APPLE_DINGBATS_UNDEFINED_0013	0x0013
#define T_APPLE_DINGBATS_UNDEFINED_0014	0x0014
#define T_APPLE_DINGBATS_UNDEFINED_0015	0x0015
#define T_APPLE_DINGBATS_UNDEFINED_0016	0x0016
#define T_APPLE_DINGBATS_UNDEFINED_0017	0x0017
#define T_APPLE_DINGBATS_UNDEFINED_0018	0x0018
#define T_APPLE_DINGBATS_UNDEFINED_0019	0x0019
#define T_APPLE_DINGBATS_UNDEFINED_001A	0x001A
#define T_APPLE_DINGBATS_UNDEFINED_001B	0x001B
#define T_APPLE_DINGBATS_UNDEFINED_001C	0x001C
#define T_APPLE_DINGBATS_UNDEFINED_001D	0x001D
#define T_APPLE_DINGBATS_UNDEFINED_001E	0x001E
#define T_APPLE_DINGBATS_UNDEFINED_001F	0x001F
#define T_APPLE_DINGBATS_SPACE	0x0020
#define T_APPLE_DINGBATS_UPPER_BLADE_SCISSORS	0x0021
#define T_APPLE_DINGBATS_BLACK_SCISSORS	0x0022
#define T_APPLE_DINGBATS_LOWER_BLADE_SCISSORS	0x0023
#define T_APPLE_DINGBATS_WHITE_SCISSORS	0x0024
#define T_APPLE_DINGBATS_BLACK_TELEPHONE	0x0025
#define T_APPLE_DINGBATS_TELEPHONE_LOCATION_SIGN	0x0026
#define T_APPLE_DINGBATS_TAPE_DRIVE	0x0027
#define T_APPLE_DINGBATS_AIRPLANE	0x0028
#define T_APPLE_DINGBATS_ENVELOPE	0x0029
#define T_APPLE_DINGBATS_BLACK_RIGHT_POINTING_INDEX	0x002A
#define T_APPLE_DINGBATS_WHITE_RIGHT_POINTING_INDEX	0x002B
#define T_APPLE_DINGBATS_VICTORY_HAND	0x002C
#define T_APPLE_DINGBATS_WRITING_HAND	0x002D
#define T_APPLE_DINGBATS_LOWER_RIGHT_PENCIL	0x002E
#define T_APPLE_DINGBATS_PENCIL	0x002F
#define T_APPLE_DINGBATS_UPPER_RIGHT_PENCIL	0x0030
#define T_APPLE_DINGBATS_WHITE_NIB	0x0031
#define T_APPLE_DINGBATS_BLACK_NIB	0x0032
#define T_APPLE_DINGBATS_CHECK_MARK	0x0033
#define T_APPLE_DINGBATS_HEAVY_CHECK_MARK	0x0034
#define T_APPLE_DINGBATS_MULTIPLICATION_X	0x0035
#define T_APPLE_DINGBATS_HEAVY_MULTIPLICATION_X	0x0036
#define T_APPLE_DINGBATS_BALLOT_X	0x0037
#define T_APPLE_DINGBATS_HEAVY_BALLOT_X	0x0038
#define T_APPLE_DINGBATS_OUTLINED_GREEK_CROSS	0x0039
#define T_APPLE_DINGBATS_HEAVY_GREEK_CROSS	0x003A
#define T_APPLE_DINGBATS_OPEN_CENTRE_CROSS	0x003B
#define T_APPLE_DINGBATS_HEAVY_OPEN_CENTRE_CROSS	0x003C
#define T_APPLE_DINGBATS_LATIN_CROSS	0x003D
#define T_APPLE_DINGBATS_SHADOWED_WHITE_LATIN_CROSS	0x003E
#define T_APPLE_DINGBATS_OUTLINED_LATIN_CROSS	0x003F
#define T_APPLE_DINGBATS_MALTESE_CROSS	0x0040
#define T_APPLE_DINGBATS_STAR_OF_DAVID	0x0041
#define T_APPLE_DINGBATS_FOUR_TEARDROP_SPOKED_ASTERISK	0x0042
#define T_APPLE_DINGBATS_FOUR_BALLOON_SPOKED_ASTERISK	0x0043
#define T_APPLE_DINGBATS_HEAVY_FOUR_BALLOON_SPOKED_ASTERISK	0x0044
#define T_APPLE_DINGBATS_FOUR_CLUB_SPOKED_ASTERISK	0x0045
#define T_APPLE_DINGBATS_BLACK_FOUR_POINTED_STAR	0x0046
#define T_APPLE_DINGBATS_WHITE_FOUR_POINTED_STAR	0x0047
#define T_APPLE_DINGBATS_BLACK_STAR	0x0048
#define T_APPLE_DINGBATS_STRESS_OUTLINED_WHITE_STAR	0x0049
#define T_APPLE_DINGBATS_CIRCLED_WHITE_STAR	0x004A
#define T_APPLE_DINGBATS_OPEN_CENTRE_BLACK_STAR	0x004B
#define T_APPLE_DINGBATS_BLACK_CENTRE_WHITE_STAR	0x004C
#define T_APPLE_DINGBATS_OUTLINED_BLACK_STAR	0x004D
#define T_APPLE_DINGBATS_HEAVY_OUTLINED_BLACK_STAR	0x004E
#define T_APPLE_DINGBATS_PINWHEEL_STAR	0x004F
#define T_APPLE_DINGBATS_SHADOWED_WHITE_STAR	0x0050
#define T_APPLE_DINGBATS_HEAVY_ASTERISK	0x0051
#define T_APPLE_DINGBATS_OPEN_CENTRE_ASTERISK	0x0052
#define T_APPLE_DINGBATS_EIGHT_SPOKED_ASTERISK	0x0053
#define T_APPLE_DINGBATS_EIGHT_POINTED_BLACK_STAR	0x0054
#define T_APPLE_DINGBATS_EIGHT_POINTED_PINWHEEL_STAR	0x0055
#define T_APPLE_DINGBATS_SIX_POINTED_BLACK_STAR	0x0056
#define T_APPLE_DINGBATS_EIGHT_POINTED_RECTILINEAR_BLACK_STAR	0x0057
#define T_APPLE_DINGBATS_HEAVY_EIGHT_POINTED_RECTILINEAR_BLACK_STAR	0x0058
#define T_APPLE_DINGBATS_TWELVE_POINTED_BLACK_STAR	0x0059
#define T_APPLE_DINGBATS_SIXTEEN_POINTED_ASTERISK	0x005A
#define T_APPLE_DINGBATS_TEARDROP_SPOKED_ASTERISK	0x005B
#define T_APPLE_DINGBATS_OPEN_CENTRE_TEARDROP_SPOKED_ASTERISK	0x005C
#define T_APPLE_DINGBATS_HEAVY_TEARDROP_SPOKED_ASTERISK	0x005D
#define T_APPLE_DINGBATS_SIX_PETALLED_BLACK_AND_WHITE_FLORETTE	0x005E
#define T_APPLE_DINGBATS_BLACK_FLORETTE	0x005F
#define T_APPLE_DINGBATS_WHITE_FLORETTE	0x0060
#define T_APPLE_DINGBATS_EIGHT_PETALLED_OUTLINED_BLACK_FLORETTE	0x0061
#define T_APPLE_DINGBATS_CIRCLED_OPEN_CENTRE_EIGHT_POINTED_STAR	0x0062
#define T_APPLE_DINGBATS_HEAVY_TEARDROP_SPOKED_PINWHEEL_ASTERISK	0x0063
#define T_APPLE_DINGBATS_SNOWFLAKE	0x0064
#define T_APPLE_DINGBATS_TIGHT_TRIFOLIATE_SNOWFLAKE	0x0065
#define T_APPLE_DINGBATS_HEAVY_CHEVRON_SNOWFLAKE	0x0066
#define T_APPLE_DINGBATS_SPARKLE	0x0067
#define T_APPLE_DINGBATS_HEAVY_SPARKLE	0x0068
#define T_APPLE_DINGBATS_BALLOON_SPOKED_ASTERISK	0x0069
#define T_APPLE_DINGBATS_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK	0x006A
#define T_APPLE_DINGBATS_HEAVY_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK	0x006B
#define T_APPLE_DINGBATS_BLACK_CIRCLE	0x006C
#define T_APPLE_DINGBATS_SHADOWED_WHITE_CIRCLE	0x006D
#define T_APPLE_DINGBATS_BLACK_SQUARE	0x006E
#define T_APPLE_DINGBATS_LOWER_RIGHT_DROP_SHADOWED_WHITE_SQUARE	0x006F
#define T_APPLE_DINGBATS_UPPER_RIGHT_DROP_SHADOWED_WHITE_SQUARE	0x0070
#define T_APPLE_DINGBATS_LOWER_RIGHT_SHADOWED_WHITE_SQUARE	0x0071
#define T_APPLE_DINGBATS_UPPER_RIGHT_SHADOWED_WHITE_SQUARE	0x0072
#define T_APPLE_DINGBATS_BLACK_UP_POINTING_TRIANGLE	0x0073
#define T_APPLE_DINGBATS_BLACK_DOWN_POINTING_TRIANGLE	0x0074
#define T_APPLE_DINGBATS_BLACK_DIAMOND	0x0075
#define T_APPLE_DINGBATS_BLACK_DIAMOND_MINUS_WHITE_X	0x0076
#define T_APPLE_DINGBATS_RIGHT_HALF_BLACK_CIRCLE	0x0077
#define T_APPLE_DINGBATS_LIGHT_VERTICAL_BAR	0x0078
#define T_APPLE_DINGBATS_MEDIUM_VERTICAL_BAR	0x0079
#define T_APPLE_DINGBATS_HEAVY_VERTICAL_BAR	0x007A
#define T_APPLE_DINGBATS_HEAVY_SINGLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT	0x007B
#define T_APPLE_DINGBATS_HEAVY_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT	0x007C
#define T_APPLE_DINGBATS_HEAVY_DOUBLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT	0x007D
#define T_APPLE_DINGBATS_HEAVY_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT	0x007E
#define T_APPLE_DINGBATS_UNDEFINED_007F	0x007F
#define T_APPLE_DINGBATS_MEDIUM_LEFT_PARENTHESIS_ORNAMENT	0x0080
#define T_APPLE_DINGBATS_MEDIUM_RIGHT_PARENTHESIS_ORNAMENT	0x0081
#define T_APPLE_DINGBATS_MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT	0x0082
#define T_APPLE_DINGBATS_MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT	0x0083
#define T_APPLE_DINGBATS_MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0084
#define T_APPLE_DINGBATS_MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0085
#define T_APPLE_DINGBATS_HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT	0x0086
#define T_APPLE_DINGBATS_HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT	0x0087
#define T_APPLE_DINGBATS_HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0088
#define T_APPLE_DINGBATS_HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0089
#define T_APPLE_DINGBATS_LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT	0x008A
#define T_APPLE_DINGBATS_LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT	0x008B
#define T_APPLE_DINGBATS_MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT	0x008C
#define T_APPLE_DINGBATS_MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT	0x008D
#define T_APPLE_DINGBATS_UNDEFINED_008E	0x008E
#define T_APPLE_DINGBATS_UNDEFINED_008F	0x008F
#define T_APPLE_DINGBATS_UNDEFINED_0090	0x0090
#define T_APPLE_DINGBATS_UNDEFINED_0091	0x0091
#define T_APPLE_DINGBATS_UNDEFINED_0092	0x0092
#define T_APPLE_DINGBATS_UNDEFINED_0093	0x0093
#define T_APPLE_DINGBATS_UNDEFINED_0094	0x0094
#define T_APPLE_DINGBATS_UNDEFINED_0095	0x0095
#define T_APPLE_DINGBATS_UNDEFINED_0096	0x0096
#define T_APPLE_DINGBATS_UNDEFINED_0097	0x0097
#define T_APPLE_DINGBATS_UNDEFINED_0098	0x0098
#define T_APPLE_DINGBATS_UNDEFINED_0099	0x0099
#define T_APPLE_DINGBATS_UNDEFINED_009A	0x009A
#define T_APPLE_DINGBATS_UNDEFINED_009B	0x009B
#define T_APPLE_DINGBATS_UNDEFINED_009C	0x009C
#define T_APPLE_DINGBATS_UNDEFINED_009D	0x009D
#define T_APPLE_DINGBATS_UNDEFINED_009E	0x009E
#define T_APPLE_DINGBATS_UNDEFINED_009F	0x009F
#define T_APPLE_DINGBATS_UNDEFINED_00A0	0x00A0
#define T_APPLE_DINGBATS_CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT	0x00A1
#define T_APPLE_DINGBATS_HEAVY_EXCLAMATION_MARK_ORNAMENT	0x00A2
#define T_APPLE_DINGBATS_HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT	0x00A3
#define T_APPLE_DINGBATS_HEAVY_BLACK_HEART	0x00A4
#define T_APPLE_DINGBATS_ROTATED_HEAVY_BLACK_HEART_BULLET	0x00A5
#define T_APPLE_DINGBATS_FLORAL_HEART	0x00A6
#define T_APPLE_DINGBATS_ROTATED_FLORAL_HEART_BULLET	0x00A7
#define T_APPLE_DINGBATS_BLACK_CLUB_SUIT	0x00A8
#define T_APPLE_DINGBATS_BLACK_DIAMOND_SUIT	0x00A9
#define T_APPLE_DINGBATS_BLACK_HEART_SUIT	0x00AA
#define T_APPLE_DINGBATS_BLACK_SPADE_SUIT	0x00AB
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_ONE	0x00AC
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_TWO	0x00AD
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_THREE	0x00AE
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_FOUR	0x00AF
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_FIVE	0x00B0
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_SIX	0x00B1
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_SEVEN	0x00B2
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_EIGHT	0x00B3
#define T_APPLE_DINGBATS_CIRCLED_DIGIT_NINE	0x00B4
#define T_APPLE_DINGBATS_CIRCLED_NUMBER_TEN	0x00B5
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE	0x00B6
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO	0x00B7
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE	0x00B8
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR	0x00B9
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE	0x00BA
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX	0x00BB
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN	0x00BC
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT	0x00BD
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE	0x00BE
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN	0x00BF
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE	0x00C0
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO	0x00C1
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE	0x00C2
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR	0x00C3
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE	0x00C4
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX	0x00C5
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN	0x00C6
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT	0x00C7
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE	0x00C8
#define T_APPLE_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN	0x00C9
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE	0x00CA
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO	0x00CB
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE	0x00CC
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR	0x00CD
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE	0x00CE
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX	0x00CF
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN	0x00D0
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT	0x00D1
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE	0x00D2
#define T_APPLE_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN	0x00D3
#define T_APPLE_DINGBATS_HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW	0x00D4
#define T_APPLE_DINGBATS_RIGHTWARDS_ARROW	0x00D5
#define T_APPLE_DINGBATS_LEFT_RIGHT_ARROW	0x00D6
#define T_APPLE_DINGBATS_UP_DOWN_ARROW	0x00D7
#define T_APPLE_DINGBATS_HEAVY_SOUTH_EAST_ARROW	0x00D8
#define T_APPLE_DINGBATS_HEAVY_RIGHTWARDS_ARROW	0x00D9
#define T_APPLE_DINGBATS_HEAVY_NORTH_EAST_ARROW	0x00DA
#define T_APPLE_DINGBATS_DRAFTING_POINT_RIGHTWARDS_ARROW	0x00DB
#define T_APPLE_DINGBATS_HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW	0x00DC
#define T_APPLE_DINGBATS_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00DD
#define T_APPLE_DINGBATS_HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00DE
#define T_APPLE_DINGBATS_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00DF
#define T_APPLE_DINGBATS_HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00E0
#define T_APPLE_DINGBATS_BLACK_RIGHTWARDS_ARROW	0x00E1
#define T_APPLE_DINGBATS_THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD	0x00E2
#define T_APPLE_DINGBATS_THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD	0x00E3
#define T_APPLE_DINGBATS_BLACK_RIGHTWARDS_ARROWHEAD	0x00E4
#define T_APPLE_DINGBATS_HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW	0x00E5
#define T_APPLE_DINGBATS_HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW	0x00E6
#define T_APPLE_DINGBATS_SQUAT_BLACK_RIGHTWARDS_ARROW	0x00E7
#define T_APPLE_DINGBATS_HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW	0x00E8
#define T_APPLE_DINGBATS_RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW	0x00E9
#define T_APPLE_DINGBATS_LEFT_SHADED_WHITE_RIGHTWARDS_ARROW	0x00EA
#define T_APPLE_DINGBATS_BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EB
#define T_APPLE_DINGBATS_FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EC
#define T_APPLE_DINGBATS_HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00ED
#define T_APPLE_DINGBATS_HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EE
#define T_APPLE_DINGBATS_NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EF
#define T_APPLE_DINGBATS_UNDEFINED_00F0	0x00F0
#define T_APPLE_DINGBATS_NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00F1
#define T_APPLE_DINGBATS_CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW	0x00F2
#define T_APPLE_DINGBATS_WHITE_FEATHERED_RIGHTWARDS_ARROW	0x00F3
#define T_APPLE_DINGBATS_BLACK_FEATHERED_SOUTH_EAST_ARROW	0x00F4
#define T_APPLE_DINGBATS_BLACK_FEATHERED_RIGHTWARDS_ARROW	0x00F5
#define T_APPLE_DINGBATS_BLACK_FEATHERED_NORTH_EAST_ARROW	0x00F6
#define T_APPLE_DINGBATS_HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW	0x00F7
#define T_APPLE_DINGBATS_HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW	0x00F8
#define T_APPLE_DINGBATS_HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW	0x00F9
#define T_APPLE_DINGBATS_TEARDROP_BARBED_RIGHTWARDS_ARROW	0x00FA
#define T_APPLE_DINGBATS_HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW	0x00FB
#define T_APPLE_DINGBATS_WEDGE_TAILED_RIGHTWARDS_ARROW	0x00FC
#define T_APPLE_DINGBATS_HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW	0x00FD
#define T_APPLE_DINGBATS_OPEN_OUTLINED_RIGHTWARDS_ARROW	0x00FE
#define T_APPLE_DINGBATS_UNDEFINED_00FF	0x00FF

/* list of all characters */
#define T_LIST_APPLE_DINGBATS(EL) \
    EL(_SPACE) \
    EL(_UPPER_BLADE_SCISSORS) \
    EL(_BLACK_SCISSORS) \
    EL(_LOWER_BLADE_SCISSORS) \
    EL(_WHITE_SCISSORS) \
    EL(_BLACK_TELEPHONE) \
    EL(_TELEPHONE_LOCATION_SIGN) \
    EL(_TAPE_DRIVE) \
    EL(_AIRPLANE) \
    EL(_ENVELOPE) \
    EL(_BLACK_RIGHT_POINTING_INDEX) \
    EL(_WHITE_RIGHT_POINTING_INDEX) \
    EL(_VICTORY_HAND) \
    EL(_WRITING_HAND) \
    EL(_LOWER_RIGHT_PENCIL) \
    EL(_PENCIL) \
    EL(_UPPER_RIGHT_PENCIL) \
    EL(_WHITE_NIB) \
    EL(_BLACK_NIB) \
    EL(_CHECK_MARK) \
    EL(_HEAVY_CHECK_MARK) \
    EL(_MULTIPLICATION_X) \
    EL(_HEAVY_MULTIPLICATION_X) \
    EL(_BALLOT_X) \
    EL(_HEAVY_BALLOT_X) \
    EL(_OUTLINED_GREEK_CROSS) \
    EL(_HEAVY_GREEK_CROSS) \
    EL(_OPEN_CENTRE_CROSS) \
    EL(_HEAVY_OPEN_CENTRE_CROSS) \
    EL(_LATIN_CROSS) \
    EL(_SHADOWED_WHITE_LATIN_CROSS) \
    EL(_OUTLINED_LATIN_CROSS) \
    EL(_MALTESE_CROSS) \
    EL(_STAR_OF_DAVID) \
    EL(_FOUR_TEARDROP_SPOKED_ASTERISK) \
    EL(_FOUR_BALLOON_SPOKED_ASTERISK) \
    EL(_HEAVY_FOUR_BALLOON_SPOKED_ASTERISK) \
    EL(_FOUR_CLUB_SPOKED_ASTERISK) \
    EL(_BLACK_FOUR_POINTED_STAR) \
    EL(_WHITE_FOUR_POINTED_STAR) \
    EL(_BLACK_STAR) \
    EL(_STRESS_OUTLINED_WHITE_STAR) \
    EL(_CIRCLED_WHITE_STAR) \
    EL(_OPEN_CENTRE_BLACK_STAR) \
    EL(_BLACK_CENTRE_WHITE_STAR) \
    EL(_OUTLINED_BLACK_STAR) \
    EL(_HEAVY_OUTLINED_BLACK_STAR) \
    EL(_PINWHEEL_STAR) \
    EL(_SHADOWED_WHITE_STAR) \
    EL(_HEAVY_ASTERISK) \
    EL(_OPEN_CENTRE_ASTERISK) \
    EL(_EIGHT_SPOKED_ASTERISK) \
    EL(_EIGHT_POINTED_BLACK_STAR) \
    EL(_EIGHT_POINTED_PINWHEEL_STAR) \
    EL(_SIX_POINTED_BLACK_STAR) \
    EL(_EIGHT_POINTED_RECTILINEAR_BLACK_STAR) \
    EL(_HEAVY_EIGHT_POINTED_RECTILINEAR_BLACK_STAR) \
    EL(_TWELVE_POINTED_BLACK_STAR) \
    EL(_SIXTEEN_POINTED_ASTERISK) \
    EL(_TEARDROP_SPOKED_ASTERISK) \
    EL(_OPEN_CENTRE_TEARDROP_SPOKED_ASTERISK) \
    EL(_HEAVY_TEARDROP_SPOKED_ASTERISK) \
    EL(_SIX_PETALLED_BLACK_AND_WHITE_FLORETTE) \
    EL(_BLACK_FLORETTE) \
    EL(_WHITE_FLORETTE) \
    EL(_EIGHT_PETALLED_OUTLINED_BLACK_FLORETTE) \
    EL(_CIRCLED_OPEN_CENTRE_EIGHT_POINTED_STAR) \
    EL(_HEAVY_TEARDROP_SPOKED_PINWHEEL_ASTERISK) \
    EL(_SNOWFLAKE) \
    EL(_TIGHT_TRIFOLIATE_SNOWFLAKE) \
    EL(_HEAVY_CHEVRON_SNOWFLAKE) \
    EL(_SPARKLE) \
    EL(_HEAVY_SPARKLE) \
    EL(_BALLOON_SPOKED_ASTERISK) \
    EL(_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK) \
    EL(_HEAVY_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK) \
    EL(_BLACK_CIRCLE) \
    EL(_SHADOWED_WHITE_CIRCLE) \
    EL(_BLACK_SQUARE) \
    EL(_LOWER_RIGHT_DROP_SHADOWED_WHITE_SQUARE) \
    EL(_UPPER_RIGHT_DROP_SHADOWED_WHITE_SQUARE) \
    EL(_LOWER_RIGHT_SHADOWED_WHITE_SQUARE) \
    EL(_UPPER_RIGHT_SHADOWED_WHITE_SQUARE) \
    EL(_BLACK_UP_POINTING_TRIANGLE) \
    EL(_BLACK_DOWN_POINTING_TRIANGLE) \
    EL(_BLACK_DIAMOND) \
    EL(_BLACK_DIAMOND_MINUS_WHITE_X) \
    EL(_RIGHT_HALF_BLACK_CIRCLE) \
    EL(_LIGHT_VERTICAL_BAR) \
    EL(_MEDIUM_VERTICAL_BAR) \
    EL(_HEAVY_VERTICAL_BAR) \
    EL(_HEAVY_SINGLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_DOUBLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_MEDIUM_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT) \
    EL(_CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT) \
    EL(_HEAVY_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_BLACK_HEART) \
    EL(_ROTATED_HEAVY_BLACK_HEART_BULLET) \
    EL(_FLORAL_HEART) \
    EL(_ROTATED_FLORAL_HEART_BULLET) \
    EL(_BLACK_CLUB_SUIT) \
    EL(_BLACK_DIAMOND_SUIT) \
    EL(_BLACK_HEART_SUIT) \
    EL(_BLACK_SPADE_SUIT) \
    EL(_CIRCLED_DIGIT_ONE) \
    EL(_CIRCLED_DIGIT_TWO) \
    EL(_CIRCLED_DIGIT_THREE) \
    EL(_CIRCLED_DIGIT_FOUR) \
    EL(_CIRCLED_DIGIT_FIVE) \
    EL(_CIRCLED_DIGIT_SIX) \
    EL(_CIRCLED_DIGIT_SEVEN) \
    EL(_CIRCLED_DIGIT_EIGHT) \
    EL(_CIRCLED_DIGIT_NINE) \
    EL(_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW) \
    EL(_RIGHTWARDS_ARROW) \
    EL(_LEFT_RIGHT_ARROW) \
    EL(_UP_DOWN_ARROW) \
    EL(_HEAVY_SOUTH_EAST_ARROW) \
    EL(_HEAVY_RIGHTWARDS_ARROW) \
    EL(_HEAVY_NORTH_EAST_ARROW) \
    EL(_DRAFTING_POINT_RIGHTWARDS_ARROW) \
    EL(_HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW) \
    EL(_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_BLACK_RIGHTWARDS_ARROW) \
    EL(_THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_BLACK_RIGHTWARDS_ARROWHEAD) \
    EL(_HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_SQUAT_BLACK_RIGHTWARDS_ARROW) \
    EL(_HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW) \
    EL(_RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_LEFT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW) \
    EL(_WHITE_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_TEARDROP_BARBED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW) \
    EL(_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_OPEN_OUTLINED_RIGHTWARDS_ARROW)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_APPLE_DINGBATS(EL) \
    EL(_UPPER_BLADE_SCISSORS) \
    EL(_BLACK_SCISSORS) \
    EL(_LOWER_BLADE_SCISSORS) \
    EL(_WHITE_SCISSORS) \
    EL(_BLACK_TELEPHONE) \
    EL(_TELEPHONE_LOCATION_SIGN) \
    EL(_TAPE_DRIVE) \
    EL(_AIRPLANE) \
    EL(_ENVELOPE) \
    EL(_BLACK_RIGHT_POINTING_INDEX) \
    EL(_WHITE_RIGHT_POINTING_INDEX) \
    EL(_VICTORY_HAND) \
    EL(_WRITING_HAND) \
    EL(_LOWER_RIGHT_PENCIL) \
    EL(_PENCIL) \
    EL(_UPPER_RIGHT_PENCIL) \
    EL(_WHITE_NIB) \
    EL(_BLACK_NIB) \
    EL(_CHECK_MARK) \
    EL(_HEAVY_CHECK_MARK) \
    EL(_MULTIPLICATION_X) \
    EL(_HEAVY_MULTIPLICATION_X) \
    EL(_BALLOT_X) \
    EL(_HEAVY_BALLOT_X) \
    EL(_OUTLINED_GREEK_CROSS) \
    EL(_HEAVY_GREEK_CROSS) \
    EL(_OPEN_CENTRE_CROSS) \
    EL(_HEAVY_OPEN_CENTRE_CROSS) \
    EL(_LATIN_CROSS) \
    EL(_SHADOWED_WHITE_LATIN_CROSS) \
    EL(_OUTLINED_LATIN_CROSS) \
    EL(_MALTESE_CROSS) \
    EL(_STAR_OF_DAVID) \
    EL(_FOUR_TEARDROP_SPOKED_ASTERISK) \
    EL(_FOUR_BALLOON_SPOKED_ASTERISK) \
    EL(_HEAVY_FOUR_BALLOON_SPOKED_ASTERISK) \
    EL(_FOUR_CLUB_SPOKED_ASTERISK) \
    EL(_BLACK_FOUR_POINTED_STAR) \
    EL(_WHITE_FOUR_POINTED_STAR) \
    EL(_BLACK_STAR) \
    EL(_STRESS_OUTLINED_WHITE_STAR) \
    EL(_CIRCLED_WHITE_STAR) \
    EL(_OPEN_CENTRE_BLACK_STAR) \
    EL(_BLACK_CENTRE_WHITE_STAR) \
    EL(_OUTLINED_BLACK_STAR) \
    EL(_HEAVY_OUTLINED_BLACK_STAR) \
    EL(_PINWHEEL_STAR) \
    EL(_SHADOWED_WHITE_STAR) \
    EL(_HEAVY_ASTERISK) \
    EL(_OPEN_CENTRE_ASTERISK) \
    EL(_EIGHT_SPOKED_ASTERISK) \
    EL(_EIGHT_POINTED_BLACK_STAR) \
    EL(_EIGHT_POINTED_PINWHEEL_STAR) \
    EL(_SIX_POINTED_BLACK_STAR) \
    EL(_EIGHT_POINTED_RECTILINEAR_BLACK_STAR) \
    EL(_HEAVY_EIGHT_POINTED_RECTILINEAR_BLACK_STAR) \
    EL(_TWELVE_POINTED_BLACK_STAR) \
    EL(_SIXTEEN_POINTED_ASTERISK) \
    EL(_TEARDROP_SPOKED_ASTERISK) \
    EL(_OPEN_CENTRE_TEARDROP_SPOKED_ASTERISK) \
    EL(_HEAVY_TEARDROP_SPOKED_ASTERISK) \
    EL(_SIX_PETALLED_BLACK_AND_WHITE_FLORETTE) \
    EL(_BLACK_FLORETTE) \
    EL(_WHITE_FLORETTE) \
    EL(_EIGHT_PETALLED_OUTLINED_BLACK_FLORETTE) \
    EL(_CIRCLED_OPEN_CENTRE_EIGHT_POINTED_STAR) \
    EL(_HEAVY_TEARDROP_SPOKED_PINWHEEL_ASTERISK) \
    EL(_SNOWFLAKE) \
    EL(_TIGHT_TRIFOLIATE_SNOWFLAKE) \
    EL(_HEAVY_CHEVRON_SNOWFLAKE) \
    EL(_SPARKLE) \
    EL(_HEAVY_SPARKLE) \
    EL(_BALLOON_SPOKED_ASTERISK) \
    EL(_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK) \
    EL(_HEAVY_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK) \
    EL(_BLACK_CIRCLE) \
    EL(_SHADOWED_WHITE_CIRCLE) \
    EL(_BLACK_SQUARE) \
    EL(_LOWER_RIGHT_DROP_SHADOWED_WHITE_SQUARE) \
    EL(_UPPER_RIGHT_DROP_SHADOWED_WHITE_SQUARE) \
    EL(_LOWER_RIGHT_SHADOWED_WHITE_SQUARE) \
    EL(_UPPER_RIGHT_SHADOWED_WHITE_SQUARE) \
    EL(_BLACK_UP_POINTING_TRIANGLE) \
    EL(_BLACK_DOWN_POINTING_TRIANGLE) \
    EL(_BLACK_DIAMOND) \
    EL(_BLACK_DIAMOND_MINUS_WHITE_X) \
    EL(_RIGHT_HALF_BLACK_CIRCLE) \
    EL(_LIGHT_VERTICAL_BAR) \
    EL(_MEDIUM_VERTICAL_BAR) \
    EL(_HEAVY_VERTICAL_BAR) \
    EL(_HEAVY_SINGLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_DOUBLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT) \
    EL(_MEDIUM_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT) \
    EL(_CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT) \
    EL(_HEAVY_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_BLACK_HEART) \
    EL(_ROTATED_HEAVY_BLACK_HEART_BULLET) \
    EL(_FLORAL_HEART) \
    EL(_ROTATED_FLORAL_HEART_BULLET) \
    EL(_BLACK_CLUB_SUIT) \
    EL(_BLACK_DIAMOND_SUIT) \
    EL(_BLACK_HEART_SUIT) \
    EL(_BLACK_SPADE_SUIT) \
    EL(_CIRCLED_DIGIT_ONE) \
    EL(_CIRCLED_DIGIT_TWO) \
    EL(_CIRCLED_DIGIT_THREE) \
    EL(_CIRCLED_DIGIT_FOUR) \
    EL(_CIRCLED_DIGIT_FIVE) \
    EL(_CIRCLED_DIGIT_SIX) \
    EL(_CIRCLED_DIGIT_SEVEN) \
    EL(_CIRCLED_DIGIT_EIGHT) \
    EL(_CIRCLED_DIGIT_NINE) \
    EL(_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW) \
    EL(_RIGHTWARDS_ARROW) \
    EL(_LEFT_RIGHT_ARROW) \
    EL(_UP_DOWN_ARROW) \
    EL(_HEAVY_SOUTH_EAST_ARROW) \
    EL(_HEAVY_RIGHTWARDS_ARROW) \
    EL(_HEAVY_NORTH_EAST_ARROW) \
    EL(_DRAFTING_POINT_RIGHTWARDS_ARROW) \
    EL(_HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW) \
    EL(_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_BLACK_RIGHTWARDS_ARROW) \
    EL(_THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_BLACK_RIGHTWARDS_ARROWHEAD) \
    EL(_HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_SQUAT_BLACK_RIGHTWARDS_ARROW) \
    EL(_HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW) \
    EL(_RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_LEFT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW) \
    EL(_WHITE_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_TEARDROP_BARBED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW) \
    EL(_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_OPEN_OUTLINED_RIGHTWARDS_ARROW)


#endif /* _TUTF_APPLE_DINGBATS_H */
