
/*
 * This file was automatically generated
 * from clisp sources with "from-kernel.bash"
 * Do not edit!
 */


#ifndef _TUTF_CP1256_H
#define _TUTF_CP1256_H

#define T_CP1256_NULL	0x0000
#define T_CP1256_START_OF_HEADING	0x0001
#define T_CP1256_START_OF_TEXT	0x0002
#define T_CP1256_END_OF_TEXT	0x0003
#define T_CP1256_END_OF_TRANSMISSION	0x0004
#define T_CP1256_ENQUIRY	0x0005
#define T_CP1256_ACKNOWLEDGE	0x0006
#define T_CP1256_BELL	0x0007
#define T_CP1256_BACKSPACE	0x0008
#define T_CP1256_HORIZONTAL_TABULATION	0x0009
#define T_CP1256_LINE_FEED	0x000A
#define T_CP1256_VERTICAL_TABULATION	0x000B
#define T_CP1256_FORM_FEED	0x000C
#define T_CP1256_CARRIAGE_RETURN	0x000D
#define T_CP1256_SHIFT_OUT	0x000E
#define T_CP1256_SHIFT_IN	0x000F
#define T_CP1256_DATA_LINK_ESCAPE	0x0010
#define T_CP1256_DEVICE_CONTROL_ONE	0x0011
#define T_CP1256_DEVICE_CONTROL_TWO	0x0012
#define T_CP1256_DEVICE_CONTROL_THREE	0x0013
#define T_CP1256_DEVICE_CONTROL_FOUR	0x0014
#define T_CP1256_NEGATIVE_ACKNOWLEDGE	0x0015
#define T_CP1256_SYNCHRONOUS_IDLE	0x0016
#define T_CP1256_END_OF_TRANSMISSION_BLOCK	0x0017
#define T_CP1256_CANCEL	0x0018
#define T_CP1256_END_OF_MEDIUM	0x0019
#define T_CP1256_SUBSTITUTE	0x001A
#define T_CP1256_ESCAPE	0x001B
#define T_CP1256_FILE_SEPARATOR	0x001C
#define T_CP1256_GROUP_SEPARATOR	0x001D
#define T_CP1256_RECORD_SEPARATOR	0x001E
#define T_CP1256_UNIT_SEPARATOR	0x001F
#define T_CP1256_SPACE	0x0020
#define T_CP1256_EXCLAMATION_MARK	0x0021
#define T_CP1256_QUOTATION_MARK	0x0022
#define T_CP1256_NUMBER_SIGN	0x0023
#define T_CP1256_DOLLAR_SIGN	0x0024
#define T_CP1256_PERCENT_SIGN	0x0025
#define T_CP1256_AMPERSAND	0x0026
#define T_CP1256_APOSTROPHE	0x0027
#define T_CP1256_LEFT_PARENTHESIS	0x0028
#define T_CP1256_RIGHT_PARENTHESIS	0x0029
#define T_CP1256_ASTERISK	0x002A
#define T_CP1256_PLUS_SIGN	0x002B
#define T_CP1256_COMMA	0x002C
#define T_CP1256_HYPHEN_MINUS	0x002D
#define T_CP1256_FULL_STOP	0x002E
#define T_CP1256_SOLIDUS	0x002F
#define T_CP1256_DIGIT_ZERO	0x0030
#define T_CP1256_DIGIT_ONE	0x0031
#define T_CP1256_DIGIT_TWO	0x0032
#define T_CP1256_DIGIT_THREE	0x0033
#define T_CP1256_DIGIT_FOUR	0x0034
#define T_CP1256_DIGIT_FIVE	0x0035
#define T_CP1256_DIGIT_SIX	0x0036
#define T_CP1256_DIGIT_SEVEN	0x0037
#define T_CP1256_DIGIT_EIGHT	0x0038
#define T_CP1256_DIGIT_NINE	0x0039
#define T_CP1256_COLON	0x003A
#define T_CP1256_SEMICOLON	0x003B
#define T_CP1256_LESS_THAN_SIGN	0x003C
#define T_CP1256_EQUALS_SIGN	0x003D
#define T_CP1256_GREATER_THAN_SIGN	0x003E
#define T_CP1256_QUESTION_MARK	0x003F
#define T_CP1256_COMMERCIAL_AT	0x0040
#define T_CP1256_LATIN_CAPITAL_LETTER_A	0x0041
#define T_CP1256_LATIN_CAPITAL_LETTER_B	0x0042
#define T_CP1256_LATIN_CAPITAL_LETTER_C	0x0043
#define T_CP1256_LATIN_CAPITAL_LETTER_D	0x0044
#define T_CP1256_LATIN_CAPITAL_LETTER_E	0x0045
#define T_CP1256_LATIN_CAPITAL_LETTER_F	0x0046
#define T_CP1256_LATIN_CAPITAL_LETTER_G	0x0047
#define T_CP1256_LATIN_CAPITAL_LETTER_H	0x0048
#define T_CP1256_LATIN_CAPITAL_LETTER_I	0x0049
#define T_CP1256_LATIN_CAPITAL_LETTER_J	0x004A
#define T_CP1256_LATIN_CAPITAL_LETTER_K	0x004B
#define T_CP1256_LATIN_CAPITAL_LETTER_L	0x004C
#define T_CP1256_LATIN_CAPITAL_LETTER_M	0x004D
#define T_CP1256_LATIN_CAPITAL_LETTER_N	0x004E
#define T_CP1256_LATIN_CAPITAL_LETTER_O	0x004F
#define T_CP1256_LATIN_CAPITAL_LETTER_P	0x0050
#define T_CP1256_LATIN_CAPITAL_LETTER_Q	0x0051
#define T_CP1256_LATIN_CAPITAL_LETTER_R	0x0052
#define T_CP1256_LATIN_CAPITAL_LETTER_S	0x0053
#define T_CP1256_LATIN_CAPITAL_LETTER_T	0x0054
#define T_CP1256_LATIN_CAPITAL_LETTER_U	0x0055
#define T_CP1256_LATIN_CAPITAL_LETTER_V	0x0056
#define T_CP1256_LATIN_CAPITAL_LETTER_W	0x0057
#define T_CP1256_LATIN_CAPITAL_LETTER_X	0x0058
#define T_CP1256_LATIN_CAPITAL_LETTER_Y	0x0059
#define T_CP1256_LATIN_CAPITAL_LETTER_Z	0x005A
#define T_CP1256_LEFT_SQUARE_BRACKET	0x005B
#define T_CP1256_REVERSE_SOLIDUS	0x005C
#define T_CP1256_RIGHT_SQUARE_BRACKET	0x005D
#define T_CP1256_CIRCUMFLEX_ACCENT	0x005E
#define T_CP1256_LOW_LINE	0x005F
#define T_CP1256_GRAVE_ACCENT	0x0060
#define T_CP1256_LATIN_SMALL_LETTER_A	0x0061
#define T_CP1256_LATIN_SMALL_LETTER_B	0x0062
#define T_CP1256_LATIN_SMALL_LETTER_C	0x0063
#define T_CP1256_LATIN_SMALL_LETTER_D	0x0064
#define T_CP1256_LATIN_SMALL_LETTER_E	0x0065
#define T_CP1256_LATIN_SMALL_LETTER_F	0x0066
#define T_CP1256_LATIN_SMALL_LETTER_G	0x0067
#define T_CP1256_LATIN_SMALL_LETTER_H	0x0068
#define T_CP1256_LATIN_SMALL_LETTER_I	0x0069
#define T_CP1256_LATIN_SMALL_LETTER_J	0x006A
#define T_CP1256_LATIN_SMALL_LETTER_K	0x006B
#define T_CP1256_LATIN_SMALL_LETTER_L	0x006C
#define T_CP1256_LATIN_SMALL_LETTER_M	0x006D
#define T_CP1256_LATIN_SMALL_LETTER_N	0x006E
#define T_CP1256_LATIN_SMALL_LETTER_O	0x006F
#define T_CP1256_LATIN_SMALL_LETTER_P	0x0070
#define T_CP1256_LATIN_SMALL_LETTER_Q	0x0071
#define T_CP1256_LATIN_SMALL_LETTER_R	0x0072
#define T_CP1256_LATIN_SMALL_LETTER_S	0x0073
#define T_CP1256_LATIN_SMALL_LETTER_T	0x0074
#define T_CP1256_LATIN_SMALL_LETTER_U	0x0075
#define T_CP1256_LATIN_SMALL_LETTER_V	0x0076
#define T_CP1256_LATIN_SMALL_LETTER_W	0x0077
#define T_CP1256_LATIN_SMALL_LETTER_X	0x0078
#define T_CP1256_LATIN_SMALL_LETTER_Y	0x0079
#define T_CP1256_LATIN_SMALL_LETTER_Z	0x007A
#define T_CP1256_LEFT_CURLY_BRACKET	0x007B
#define T_CP1256_VERTICAL_LINE	0x007C
#define T_CP1256_RIGHT_CURLY_BRACKET	0x007D
#define T_CP1256_TILDE	0x007E
#define T_CP1256_UNDEFINED_007F	0x007F
#define T_CP1256_EURO_SIGN	0x0080
#define T_CP1256_ARABIC_LETTER_PEH	0x0081
#define T_CP1256_SINGLE_LOW_9_QUOTATION_MARK	0x0082
#define T_CP1256_LATIN_SMALL_LETTER_F_WITH_HOOK	0x0083
#define T_CP1256_DOUBLE_LOW_9_QUOTATION_MARK	0x0084
#define T_CP1256_HORIZONTAL_ELLIPSIS	0x0085
#define T_CP1256_DAGGER	0x0086
#define T_CP1256_DOUBLE_DAGGER	0x0087
#define T_CP1256_MODIFIER_LETTER_CIRCUMFLEX_ACCENT	0x0088
#define T_CP1256_PER_MILLE_SIGN	0x0089
#define T_CP1256_ARABIC_LETTER_TTEH	0x008A
#define T_CP1256_SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK	0x008B
#define T_CP1256_LATIN_CAPITAL_LIGATURE_OE	0x008C
#define T_CP1256_ARABIC_LETTER_TCHEH	0x008D
#define T_CP1256_ARABIC_LETTER_JEH	0x008E
#define T_CP1256_ARABIC_LETTER_DDAL	0x008F
#define T_CP1256_ARABIC_LETTER_GAF	0x0090
#define T_CP1256_LEFT_SINGLE_QUOTATION_MARK	0x0091
#define T_CP1256_RIGHT_SINGLE_QUOTATION_MARK	0x0092
#define T_CP1256_LEFT_DOUBLE_QUOTATION_MARK	0x0093
#define T_CP1256_RIGHT_DOUBLE_QUOTATION_MARK	0x0094
#define T_CP1256_BULLET	0x0095
#define T_CP1256_EN_DASH	0x0096
#define T_CP1256_EM_DASH	0x0097
#define T_CP1256_ARABIC_LETTER_KEHEH	0x0098
#define T_CP1256_TRADE_MARK_SIGN	0x0099
#define T_CP1256_ARABIC_LETTER_RREH	0x009A
#define T_CP1256_SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK	0x009B
#define T_CP1256_LATIN_SMALL_LIGATURE_OE	0x009C
#define T_CP1256_ZERO_WIDTH_NON_JOINER	0x009D
#define T_CP1256_ZERO_WIDTH_JOINER	0x009E
#define T_CP1256_ARABIC_LETTER_NOON_GHUNNA	0x009F
#define T_CP1256_NO_BREAK_SPACE	0x00A0
#define T_CP1256_ARABIC_COMMA	0x00A1
#define T_CP1256_CENT_SIGN	0x00A2
#define T_CP1256_POUND_SIGN	0x00A3
#define T_CP1256_CURRENCY_SIGN	0x00A4
#define T_CP1256_YEN_SIGN	0x00A5
#define T_CP1256_BROKEN_BAR	0x00A6
#define T_CP1256_SECTION_SIGN	0x00A7
#define T_CP1256_DIAERESIS	0x00A8
#define T_CP1256_COPYRIGHT_SIGN	0x00A9
#define T_CP1256_ARABIC_LETTER_HEH_DOACHASHMEE	0x00AA
#define T_CP1256_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK	0x00AB
#define T_CP1256_NOT_SIGN	0x00AC
#define T_CP1256_SOFT_HYPHEN	0x00AD
#define T_CP1256_REGISTERED_SIGN	0x00AE
#define T_CP1256_MACRON	0x00AF
#define T_CP1256_DEGREE_SIGN	0x00B0
#define T_CP1256_PLUS_MINUS_SIGN	0x00B1
#define T_CP1256_SUPERSCRIPT_TWO	0x00B2
#define T_CP1256_SUPERSCRIPT_THREE	0x00B3
#define T_CP1256_ACUTE_ACCENT	0x00B4
#define T_CP1256_MICRO_SIGN	0x00B5
#define T_CP1256_PILCROW_SIGN	0x00B6
#define T_CP1256_MIDDLE_DOT	0x00B7
#define T_CP1256_CEDILLA	0x00B8
#define T_CP1256_SUPERSCRIPT_ONE	0x00B9
#define T_CP1256_ARABIC_SEMICOLON	0x00BA
#define T_CP1256_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK	0x00BB
#define T_CP1256_VULGAR_FRACTION_ONE_QUARTER	0x00BC
#define T_CP1256_VULGAR_FRACTION_ONE_HALF	0x00BD
#define T_CP1256_VULGAR_FRACTION_THREE_QUARTERS	0x00BE
#define T_CP1256_ARABIC_QUESTION_MARK	0x00BF
#define T_CP1256_ARABIC_LETTER_HEH_GOAL	0x00C0
#define T_CP1256_ARABIC_LETTER_HAMZA	0x00C1
#define T_CP1256_ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE	0x00C2
#define T_CP1256_ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE	0x00C3
#define T_CP1256_ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE	0x00C4
#define T_CP1256_ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW	0x00C5
#define T_CP1256_ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE	0x00C6
#define T_CP1256_ARABIC_LETTER_ALEF	0x00C7
#define T_CP1256_ARABIC_LETTER_BEH	0x00C8
#define T_CP1256_ARABIC_LETTER_TEH_MARBUTA	0x00C9
#define T_CP1256_ARABIC_LETTER_TEH	0x00CA
#define T_CP1256_ARABIC_LETTER_THEH	0x00CB
#define T_CP1256_ARABIC_LETTER_JEEM	0x00CC
#define T_CP1256_ARABIC_LETTER_HAH	0x00CD
#define T_CP1256_ARABIC_LETTER_KHAH	0x00CE
#define T_CP1256_ARABIC_LETTER_DAL	0x00CF
#define T_CP1256_ARABIC_LETTER_THAL	0x00D0
#define T_CP1256_ARABIC_LETTER_REH	0x00D1
#define T_CP1256_ARABIC_LETTER_ZAIN	0x00D2
#define T_CP1256_ARABIC_LETTER_SEEN	0x00D3
#define T_CP1256_ARABIC_LETTER_SHEEN	0x00D4
#define T_CP1256_ARABIC_LETTER_SAD	0x00D5
#define T_CP1256_ARABIC_LETTER_DAD	0x00D6
#define T_CP1256_MULTIPLICATION_SIGN	0x00D7
#define T_CP1256_ARABIC_LETTER_TAH	0x00D8
#define T_CP1256_ARABIC_LETTER_ZAH	0x00D9
#define T_CP1256_ARABIC_LETTER_AIN	0x00DA
#define T_CP1256_ARABIC_LETTER_GHAIN	0x00DB
#define T_CP1256_ARABIC_TATWEEL	0x00DC
#define T_CP1256_ARABIC_LETTER_FEH	0x00DD
#define T_CP1256_ARABIC_LETTER_QAF	0x00DE
#define T_CP1256_ARABIC_LETTER_KAF	0x00DF
#define T_CP1256_LATIN_SMALL_LETTER_A_WITH_GRAVE	0x00E0
#define T_CP1256_ARABIC_LETTER_LAM	0x00E1
#define T_CP1256_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX	0x00E2
#define T_CP1256_ARABIC_LETTER_MEEM	0x00E3
#define T_CP1256_ARABIC_LETTER_NOON	0x00E4
#define T_CP1256_ARABIC_LETTER_HEH	0x00E5
#define T_CP1256_ARABIC_LETTER_WAW	0x00E6
#define T_CP1256_LATIN_SMALL_LETTER_C_WITH_CEDILLA	0x00E7
#define T_CP1256_LATIN_SMALL_LETTER_E_WITH_GRAVE	0x00E8
#define T_CP1256_LATIN_SMALL_LETTER_E_WITH_ACUTE	0x00E9
#define T_CP1256_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX	0x00EA
#define T_CP1256_LATIN_SMALL_LETTER_E_WITH_DIAERESIS	0x00EB
#define T_CP1256_ARABIC_LETTER_ALEF_MAKSURA	0x00EC
#define T_CP1256_ARABIC_LETTER_YEH	0x00ED
#define T_CP1256_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX	0x00EE
#define T_CP1256_LATIN_SMALL_LETTER_I_WITH_DIAERESIS	0x00EF
#define T_CP1256_ARABIC_FATHATAN	0x00F0
#define T_CP1256_ARABIC_DAMMATAN	0x00F1
#define T_CP1256_ARABIC_KASRATAN	0x00F2
#define T_CP1256_ARABIC_FATHA	0x00F3
#define T_CP1256_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX	0x00F4
#define T_CP1256_ARABIC_DAMMA	0x00F5
#define T_CP1256_ARABIC_KASRA	0x00F6
#define T_CP1256_DIVISION_SIGN	0x00F7
#define T_CP1256_ARABIC_SHADDA	0x00F8
#define T_CP1256_LATIN_SMALL_LETTER_U_WITH_GRAVE	0x00F9
#define T_CP1256_ARABIC_SUKUN	0x00FA
#define T_CP1256_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX	0x00FB
#define T_CP1256_LATIN_SMALL_LETTER_U_WITH_DIAERESIS	0x00FC
#define T_CP1256_LEFT_TO_RIGHT_MARK	0x00FD
#define T_CP1256_RIGHT_TO_LEFT_MARK	0x00FE
#define T_CP1256_ARABIC_LETTER_YEH_BARREE	0x00FF

/* list of all characters */
#define T_LIST_CP1256(EL) \
    EL(_NULL) \
    EL(_START_OF_HEADING) \
    EL(_START_OF_TEXT) \
    EL(_END_OF_TEXT) \
    EL(_END_OF_TRANSMISSION) \
    EL(_ENQUIRY) \
    EL(_ACKNOWLEDGE) \
    EL(_BELL) \
    EL(_BACKSPACE) \
    EL(_HORIZONTAL_TABULATION) \
    EL(_LINE_FEED) \
    EL(_VERTICAL_TABULATION) \
    EL(_FORM_FEED) \
    EL(_CARRIAGE_RETURN) \
    EL(_SHIFT_OUT) \
    EL(_SHIFT_IN) \
    EL(_DATA_LINK_ESCAPE) \
    EL(_DEVICE_CONTROL_ONE) \
    EL(_DEVICE_CONTROL_TWO) \
    EL(_DEVICE_CONTROL_THREE) \
    EL(_DEVICE_CONTROL_FOUR) \
    EL(_NEGATIVE_ACKNOWLEDGE) \
    EL(_SYNCHRONOUS_IDLE) \
    EL(_END_OF_TRANSMISSION_BLOCK) \
    EL(_CANCEL) \
    EL(_END_OF_MEDIUM) \
    EL(_SUBSTITUTE) \
    EL(_ESCAPE) \
    EL(_FILE_SEPARATOR) \
    EL(_GROUP_SEPARATOR) \
    EL(_RECORD_SEPARATOR) \
    EL(_UNIT_SEPARATOR) \
    EL(_SPACE) \
    EL(_EXCLAMATION_MARK) \
    EL(_QUOTATION_MARK) \
    EL(_NUMBER_SIGN) \
    EL(_DOLLAR_SIGN) \
    EL(_PERCENT_SIGN) \
    EL(_AMPERSAND) \
    EL(_APOSTROPHE) \
    EL(_LEFT_PARENTHESIS) \
    EL(_RIGHT_PARENTHESIS) \
    EL(_ASTERISK) \
    EL(_PLUS_SIGN) \
    EL(_COMMA) \
    EL(_HYPHEN_MINUS) \
    EL(_FULL_STOP) \
    EL(_SOLIDUS) \
    EL(_DIGIT_ZERO) \
    EL(_DIGIT_ONE) \
    EL(_DIGIT_TWO) \
    EL(_DIGIT_THREE) \
    EL(_DIGIT_FOUR) \
    EL(_DIGIT_FIVE) \
    EL(_DIGIT_SIX) \
    EL(_DIGIT_SEVEN) \
    EL(_DIGIT_EIGHT) \
    EL(_DIGIT_NINE) \
    EL(_COLON) \
    EL(_SEMICOLON) \
    EL(_LESS_THAN_SIGN) \
    EL(_EQUALS_SIGN) \
    EL(_GREATER_THAN_SIGN) \
    EL(_QUESTION_MARK) \
    EL(_COMMERCIAL_AT) \
    EL(_LATIN_CAPITAL_LETTER_A) \
    EL(_LATIN_CAPITAL_LETTER_B) \
    EL(_LATIN_CAPITAL_LETTER_C) \
    EL(_LATIN_CAPITAL_LETTER_D) \
    EL(_LATIN_CAPITAL_LETTER_E) \
    EL(_LATIN_CAPITAL_LETTER_F) \
    EL(_LATIN_CAPITAL_LETTER_G) \
    EL(_LATIN_CAPITAL_LETTER_H) \
    EL(_LATIN_CAPITAL_LETTER_I) \
    EL(_LATIN_CAPITAL_LETTER_J) \
    EL(_LATIN_CAPITAL_LETTER_K) \
    EL(_LATIN_CAPITAL_LETTER_L) \
    EL(_LATIN_CAPITAL_LETTER_M) \
    EL(_LATIN_CAPITAL_LETTER_N) \
    EL(_LATIN_CAPITAL_LETTER_O) \
    EL(_LATIN_CAPITAL_LETTER_P) \
    EL(_LATIN_CAPITAL_LETTER_Q) \
    EL(_LATIN_CAPITAL_LETTER_R) \
    EL(_LATIN_CAPITAL_LETTER_S) \
    EL(_LATIN_CAPITAL_LETTER_T) \
    EL(_LATIN_CAPITAL_LETTER_U) \
    EL(_LATIN_CAPITAL_LETTER_V) \
    EL(_LATIN_CAPITAL_LETTER_W) \
    EL(_LATIN_CAPITAL_LETTER_X) \
    EL(_LATIN_CAPITAL_LETTER_Y) \
    EL(_LATIN_CAPITAL_LETTER_Z) \
    EL(_LEFT_SQUARE_BRACKET) \
    EL(_REVERSE_SOLIDUS) \
    EL(_RIGHT_SQUARE_BRACKET) \
    EL(_CIRCUMFLEX_ACCENT) \
    EL(_LOW_LINE) \
    EL(_GRAVE_ACCENT) \
    EL(_LATIN_SMALL_LETTER_A) \
    EL(_LATIN_SMALL_LETTER_B) \
    EL(_LATIN_SMALL_LETTER_C) \
    EL(_LATIN_SMALL_LETTER_D) \
    EL(_LATIN_SMALL_LETTER_E) \
    EL(_LATIN_SMALL_LETTER_F) \
    EL(_LATIN_SMALL_LETTER_G) \
    EL(_LATIN_SMALL_LETTER_H) \
    EL(_LATIN_SMALL_LETTER_I) \
    EL(_LATIN_SMALL_LETTER_J) \
    EL(_LATIN_SMALL_LETTER_K) \
    EL(_LATIN_SMALL_LETTER_L) \
    EL(_LATIN_SMALL_LETTER_M) \
    EL(_LATIN_SMALL_LETTER_N) \
    EL(_LATIN_SMALL_LETTER_O) \
    EL(_LATIN_SMALL_LETTER_P) \
    EL(_LATIN_SMALL_LETTER_Q) \
    EL(_LATIN_SMALL_LETTER_R) \
    EL(_LATIN_SMALL_LETTER_S) \
    EL(_LATIN_SMALL_LETTER_T) \
    EL(_LATIN_SMALL_LETTER_U) \
    EL(_LATIN_SMALL_LETTER_V) \
    EL(_LATIN_SMALL_LETTER_W) \
    EL(_LATIN_SMALL_LETTER_X) \
    EL(_LATIN_SMALL_LETTER_Y) \
    EL(_LATIN_SMALL_LETTER_Z) \
    EL(_LEFT_CURLY_BRACKET) \
    EL(_VERTICAL_LINE) \
    EL(_RIGHT_CURLY_BRACKET) \
    EL(_TILDE) \
    EL(_UNDEFINED_007F) \
    EL(_EURO_SIGN) \
    EL(_ARABIC_LETTER_PEH) \
    EL(_SINGLE_LOW_9_QUOTATION_MARK) \
    EL(_LATIN_SMALL_LETTER_F_WITH_HOOK) \
    EL(_DOUBLE_LOW_9_QUOTATION_MARK) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_DAGGER) \
    EL(_DOUBLE_DAGGER) \
    EL(_MODIFIER_LETTER_CIRCUMFLEX_ACCENT) \
    EL(_PER_MILLE_SIGN) \
    EL(_ARABIC_LETTER_TTEH) \
    EL(_SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_LATIN_CAPITAL_LIGATURE_OE) \
    EL(_ARABIC_LETTER_TCHEH) \
    EL(_ARABIC_LETTER_JEH) \
    EL(_ARABIC_LETTER_DDAL) \
    EL(_ARABIC_LETTER_GAF) \
    EL(_LEFT_SINGLE_QUOTATION_MARK) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_LEFT_DOUBLE_QUOTATION_MARK) \
    EL(_RIGHT_DOUBLE_QUOTATION_MARK) \
    EL(_BULLET) \
    EL(_EN_DASH) \
    EL(_EM_DASH) \
    EL(_ARABIC_LETTER_KEHEH) \
    EL(_TRADE_MARK_SIGN) \
    EL(_ARABIC_LETTER_RREH) \
    EL(_SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_LATIN_SMALL_LIGATURE_OE) \
    EL(_ZERO_WIDTH_NON_JOINER) \
    EL(_ZERO_WIDTH_JOINER) \
    EL(_ARABIC_LETTER_NOON_GHUNNA) \
    EL(_NO_BREAK_SPACE) \
    EL(_ARABIC_COMMA) \
    EL(_CENT_SIGN) \
    EL(_POUND_SIGN) \
    EL(_CURRENCY_SIGN) \
    EL(_YEN_SIGN) \
    EL(_BROKEN_BAR) \
    EL(_SECTION_SIGN) \
    EL(_DIAERESIS) \
    EL(_COPYRIGHT_SIGN) \
    EL(_ARABIC_LETTER_HEH_DOACHASHMEE) \
    EL(_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK) \
    EL(_NOT_SIGN) \
    EL(_SOFT_HYPHEN) \
    EL(_REGISTERED_SIGN) \
    EL(_MACRON) \
    EL(_DEGREE_SIGN) \
    EL(_PLUS_MINUS_SIGN) \
    EL(_SUPERSCRIPT_TWO) \
    EL(_SUPERSCRIPT_THREE) \
    EL(_ACUTE_ACCENT) \
    EL(_MICRO_SIGN) \
    EL(_PILCROW_SIGN) \
    EL(_MIDDLE_DOT) \
    EL(_CEDILLA) \
    EL(_SUPERSCRIPT_ONE) \
    EL(_ARABIC_SEMICOLON) \
    EL(_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK) \
    EL(_VULGAR_FRACTION_ONE_QUARTER) \
    EL(_VULGAR_FRACTION_ONE_HALF) \
    EL(_VULGAR_FRACTION_THREE_QUARTERS) \
    EL(_ARABIC_QUESTION_MARK) \
    EL(_ARABIC_LETTER_HEH_GOAL) \
    EL(_ARABIC_LETTER_HAMZA) \
    EL(_ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE) \
    EL(_ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE) \
    EL(_ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE) \
    EL(_ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW) \
    EL(_ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE) \
    EL(_ARABIC_LETTER_ALEF) \
    EL(_ARABIC_LETTER_BEH) \
    EL(_ARABIC_LETTER_TEH_MARBUTA) \
    EL(_ARABIC_LETTER_TEH) \
    EL(_ARABIC_LETTER_THEH) \
    EL(_ARABIC_LETTER_JEEM) \
    EL(_ARABIC_LETTER_HAH) \
    EL(_ARABIC_LETTER_KHAH) \
    EL(_ARABIC_LETTER_DAL) \
    EL(_ARABIC_LETTER_THAL) \
    EL(_ARABIC_LETTER_REH) \
    EL(_ARABIC_LETTER_ZAIN) \
    EL(_ARABIC_LETTER_SEEN) \
    EL(_ARABIC_LETTER_SHEEN) \
    EL(_ARABIC_LETTER_SAD) \
    EL(_ARABIC_LETTER_DAD) \
    EL(_MULTIPLICATION_SIGN) \
    EL(_ARABIC_LETTER_TAH) \
    EL(_ARABIC_LETTER_ZAH) \
    EL(_ARABIC_LETTER_AIN) \
    EL(_ARABIC_LETTER_GHAIN) \
    EL(_ARABIC_TATWEEL) \
    EL(_ARABIC_LETTER_FEH) \
    EL(_ARABIC_LETTER_QAF) \
    EL(_ARABIC_LETTER_KAF) \
    EL(_LATIN_SMALL_LETTER_A_WITH_GRAVE) \
    EL(_ARABIC_LETTER_LAM) \
    EL(_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX) \
    EL(_ARABIC_LETTER_MEEM) \
    EL(_ARABIC_LETTER_NOON) \
    EL(_ARABIC_LETTER_HEH) \
    EL(_ARABIC_LETTER_WAW) \
    EL(_LATIN_SMALL_LETTER_C_WITH_CEDILLA) \
    EL(_LATIN_SMALL_LETTER_E_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_E_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_E_WITH_DIAERESIS) \
    EL(_ARABIC_LETTER_ALEF_MAKSURA) \
    EL(_ARABIC_LETTER_YEH) \
    EL(_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_I_WITH_DIAERESIS) \
    EL(_ARABIC_FATHATAN) \
    EL(_ARABIC_DAMMATAN) \
    EL(_ARABIC_KASRATAN) \
    EL(_ARABIC_FATHA) \
    EL(_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX) \
    EL(_ARABIC_DAMMA) \
    EL(_ARABIC_KASRA) \
    EL(_DIVISION_SIGN) \
    EL(_ARABIC_SHADDA) \
    EL(_LATIN_SMALL_LETTER_U_WITH_GRAVE) \
    EL(_ARABIC_SUKUN) \
    EL(_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_U_WITH_DIAERESIS) \
    EL(_LEFT_TO_RIGHT_MARK) \
    EL(_RIGHT_TO_LEFT_MARK) \
    EL(_ARABIC_LETTER_YEH_BARREE)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_CP1256(EL) \
    EL(_EURO_SIGN) \
    EL(_ARABIC_LETTER_PEH) \
    EL(_SINGLE_LOW_9_QUOTATION_MARK) \
    EL(_LATIN_SMALL_LETTER_F_WITH_HOOK) \
    EL(_DOUBLE_LOW_9_QUOTATION_MARK) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_DAGGER) \
    EL(_DOUBLE_DAGGER) \
    EL(_MODIFIER_LETTER_CIRCUMFLEX_ACCENT) \
    EL(_PER_MILLE_SIGN) \
    EL(_ARABIC_LETTER_TTEH) \
    EL(_SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_LATIN_CAPITAL_LIGATURE_OE) \
    EL(_ARABIC_LETTER_TCHEH) \
    EL(_ARABIC_LETTER_JEH) \
    EL(_ARABIC_LETTER_DDAL) \
    EL(_ARABIC_LETTER_GAF) \
    EL(_LEFT_SINGLE_QUOTATION_MARK) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_LEFT_DOUBLE_QUOTATION_MARK) \
    EL(_RIGHT_DOUBLE_QUOTATION_MARK) \
    EL(_BULLET) \
    EL(_EN_DASH) \
    EL(_EM_DASH) \
    EL(_ARABIC_LETTER_KEHEH) \
    EL(_TRADE_MARK_SIGN) \
    EL(_ARABIC_LETTER_RREH) \
    EL(_SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_LATIN_SMALL_LIGATURE_OE) \
    EL(_ZERO_WIDTH_NON_JOINER) \
    EL(_ZERO_WIDTH_JOINER) \
    EL(_ARABIC_LETTER_NOON_GHUNNA) \
    EL(_ARABIC_COMMA) \
    EL(_ARABIC_LETTER_HEH_DOACHASHMEE) \
    EL(_ARABIC_SEMICOLON) \
    EL(_ARABIC_QUESTION_MARK) \
    EL(_ARABIC_LETTER_HEH_GOAL) \
    EL(_ARABIC_LETTER_HAMZA) \
    EL(_ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE) \
    EL(_ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE) \
    EL(_ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE) \
    EL(_ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW) \
    EL(_ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE) \
    EL(_ARABIC_LETTER_ALEF) \
    EL(_ARABIC_LETTER_BEH) \
    EL(_ARABIC_LETTER_TEH_MARBUTA) \
    EL(_ARABIC_LETTER_TEH) \
    EL(_ARABIC_LETTER_THEH) \
    EL(_ARABIC_LETTER_JEEM) \
    EL(_ARABIC_LETTER_HAH) \
    EL(_ARABIC_LETTER_KHAH) \
    EL(_ARABIC_LETTER_DAL) \
    EL(_ARABIC_LETTER_THAL) \
    EL(_ARABIC_LETTER_REH) \
    EL(_ARABIC_LETTER_ZAIN) \
    EL(_ARABIC_LETTER_SEEN) \
    EL(_ARABIC_LETTER_SHEEN) \
    EL(_ARABIC_LETTER_SAD) \
    EL(_ARABIC_LETTER_DAD) \
    EL(_ARABIC_LETTER_TAH) \
    EL(_ARABIC_LETTER_ZAH) \
    EL(_ARABIC_LETTER_AIN) \
    EL(_ARABIC_LETTER_GHAIN) \
    EL(_ARABIC_TATWEEL) \
    EL(_ARABIC_LETTER_FEH) \
    EL(_ARABIC_LETTER_QAF) \
    EL(_ARABIC_LETTER_KAF) \
    EL(_ARABIC_LETTER_LAM) \
    EL(_ARABIC_LETTER_MEEM) \
    EL(_ARABIC_LETTER_NOON) \
    EL(_ARABIC_LETTER_HEH) \
    EL(_ARABIC_LETTER_WAW) \
    EL(_ARABIC_LETTER_ALEF_MAKSURA) \
    EL(_ARABIC_LETTER_YEH) \
    EL(_ARABIC_FATHATAN) \
    EL(_ARABIC_DAMMATAN) \
    EL(_ARABIC_KASRATAN) \
    EL(_ARABIC_FATHA) \
    EL(_ARABIC_DAMMA) \
    EL(_ARABIC_KASRA) \
    EL(_ARABIC_SHADDA) \
    EL(_ARABIC_SUKUN) \
    EL(_LEFT_TO_RIGHT_MARK) \
    EL(_RIGHT_TO_LEFT_MARK) \
    EL(_ARABIC_LETTER_YEH_BARREE)

#endif /* _TUTF_CP1256_H */
