
/*
 * This file was automatically generated
 * from Linux kernel sources with "from-kernel.bash"
 * Do not edit!
 */


#ifndef _TUTF_CP874_H
#define _TUTF_CP874_H

#define T_CP874_NULL	0x0000
#define T_CP874_START_OF_HEADING	0x0001
#define T_CP874_START_OF_TEXT	0x0002
#define T_CP874_END_OF_TEXT	0x0003
#define T_CP874_END_OF_TRANSMISSION	0x0004
#define T_CP874_ENQUIRY	0x0005
#define T_CP874_ACKNOWLEDGE	0x0006
#define T_CP874_BELL	0x0007
#define T_CP874_BACKSPACE	0x0008
#define T_CP874_HORIZONTAL_TABULATION	0x0009
#define T_CP874_LINE_FEED	0x000A
#define T_CP874_VERTICAL_TABULATION	0x000B
#define T_CP874_FORM_FEED	0x000C
#define T_CP874_CARRIAGE_RETURN	0x000D
#define T_CP874_SHIFT_OUT	0x000E
#define T_CP874_SHIFT_IN	0x000F
#define T_CP874_DATA_LINK_ESCAPE	0x0010
#define T_CP874_DEVICE_CONTROL_ONE	0x0011
#define T_CP874_DEVICE_CONTROL_TWO	0x0012
#define T_CP874_DEVICE_CONTROL_THREE	0x0013
#define T_CP874_DEVICE_CONTROL_FOUR	0x0014
#define T_CP874_NEGATIVE_ACKNOWLEDGE	0x0015
#define T_CP874_SYNCHRONOUS_IDLE	0x0016
#define T_CP874_END_OF_TRANSMISSION_BLOCK	0x0017
#define T_CP874_CANCEL	0x0018
#define T_CP874_END_OF_MEDIUM	0x0019
#define T_CP874_SUBSTITUTE	0x001A
#define T_CP874_ESCAPE	0x001B
#define T_CP874_FILE_SEPARATOR	0x001C
#define T_CP874_GROUP_SEPARATOR	0x001D
#define T_CP874_RECORD_SEPARATOR	0x001E
#define T_CP874_UNIT_SEPARATOR	0x001F
#define T_CP874_SPACE	0x0020
#define T_CP874_EXCLAMATION_MARK	0x0021
#define T_CP874_QUOTATION_MARK	0x0022
#define T_CP874_NUMBER_SIGN	0x0023
#define T_CP874_DOLLAR_SIGN	0x0024
#define T_CP874_PERCENT_SIGN	0x0025
#define T_CP874_AMPERSAND	0x0026
#define T_CP874_APOSTROPHE	0x0027
#define T_CP874_LEFT_PARENTHESIS	0x0028
#define T_CP874_RIGHT_PARENTHESIS	0x0029
#define T_CP874_ASTERISK	0x002A
#define T_CP874_PLUS_SIGN	0x002B
#define T_CP874_COMMA	0x002C
#define T_CP874_HYPHEN_MINUS	0x002D
#define T_CP874_FULL_STOP	0x002E
#define T_CP874_SOLIDUS	0x002F
#define T_CP874_DIGIT_ZERO	0x0030
#define T_CP874_DIGIT_ONE	0x0031
#define T_CP874_DIGIT_TWO	0x0032
#define T_CP874_DIGIT_THREE	0x0033
#define T_CP874_DIGIT_FOUR	0x0034
#define T_CP874_DIGIT_FIVE	0x0035
#define T_CP874_DIGIT_SIX	0x0036
#define T_CP874_DIGIT_SEVEN	0x0037
#define T_CP874_DIGIT_EIGHT	0x0038
#define T_CP874_DIGIT_NINE	0x0039
#define T_CP874_COLON	0x003A
#define T_CP874_SEMICOLON	0x003B
#define T_CP874_LESS_THAN_SIGN	0x003C
#define T_CP874_EQUALS_SIGN	0x003D
#define T_CP874_GREATER_THAN_SIGN	0x003E
#define T_CP874_QUESTION_MARK	0x003F
#define T_CP874_COMMERCIAL_AT	0x0040
#define T_CP874_LATIN_CAPITAL_LETTER_A	0x0041
#define T_CP874_LATIN_CAPITAL_LETTER_B	0x0042
#define T_CP874_LATIN_CAPITAL_LETTER_C	0x0043
#define T_CP874_LATIN_CAPITAL_LETTER_D	0x0044
#define T_CP874_LATIN_CAPITAL_LETTER_E	0x0045
#define T_CP874_LATIN_CAPITAL_LETTER_F	0x0046
#define T_CP874_LATIN_CAPITAL_LETTER_G	0x0047
#define T_CP874_LATIN_CAPITAL_LETTER_H	0x0048
#define T_CP874_LATIN_CAPITAL_LETTER_I	0x0049
#define T_CP874_LATIN_CAPITAL_LETTER_J	0x004A
#define T_CP874_LATIN_CAPITAL_LETTER_K	0x004B
#define T_CP874_LATIN_CAPITAL_LETTER_L	0x004C
#define T_CP874_LATIN_CAPITAL_LETTER_M	0x004D
#define T_CP874_LATIN_CAPITAL_LETTER_N	0x004E
#define T_CP874_LATIN_CAPITAL_LETTER_O	0x004F
#define T_CP874_LATIN_CAPITAL_LETTER_P	0x0050
#define T_CP874_LATIN_CAPITAL_LETTER_Q	0x0051
#define T_CP874_LATIN_CAPITAL_LETTER_R	0x0052
#define T_CP874_LATIN_CAPITAL_LETTER_S	0x0053
#define T_CP874_LATIN_CAPITAL_LETTER_T	0x0054
#define T_CP874_LATIN_CAPITAL_LETTER_U	0x0055
#define T_CP874_LATIN_CAPITAL_LETTER_V	0x0056
#define T_CP874_LATIN_CAPITAL_LETTER_W	0x0057
#define T_CP874_LATIN_CAPITAL_LETTER_X	0x0058
#define T_CP874_LATIN_CAPITAL_LETTER_Y	0x0059
#define T_CP874_LATIN_CAPITAL_LETTER_Z	0x005A
#define T_CP874_LEFT_SQUARE_BRACKET	0x005B
#define T_CP874_REVERSE_SOLIDUS	0x005C
#define T_CP874_RIGHT_SQUARE_BRACKET	0x005D
#define T_CP874_CIRCUMFLEX_ACCENT	0x005E
#define T_CP874_LOW_LINE	0x005F
#define T_CP874_GRAVE_ACCENT	0x0060
#define T_CP874_LATIN_SMALL_LETTER_A	0x0061
#define T_CP874_LATIN_SMALL_LETTER_B	0x0062
#define T_CP874_LATIN_SMALL_LETTER_C	0x0063
#define T_CP874_LATIN_SMALL_LETTER_D	0x0064
#define T_CP874_LATIN_SMALL_LETTER_E	0x0065
#define T_CP874_LATIN_SMALL_LETTER_F	0x0066
#define T_CP874_LATIN_SMALL_LETTER_G	0x0067
#define T_CP874_LATIN_SMALL_LETTER_H	0x0068
#define T_CP874_LATIN_SMALL_LETTER_I	0x0069
#define T_CP874_LATIN_SMALL_LETTER_J	0x006A
#define T_CP874_LATIN_SMALL_LETTER_K	0x006B
#define T_CP874_LATIN_SMALL_LETTER_L	0x006C
#define T_CP874_LATIN_SMALL_LETTER_M	0x006D
#define T_CP874_LATIN_SMALL_LETTER_N	0x006E
#define T_CP874_LATIN_SMALL_LETTER_O	0x006F
#define T_CP874_LATIN_SMALL_LETTER_P	0x0070
#define T_CP874_LATIN_SMALL_LETTER_Q	0x0071
#define T_CP874_LATIN_SMALL_LETTER_R	0x0072
#define T_CP874_LATIN_SMALL_LETTER_S	0x0073
#define T_CP874_LATIN_SMALL_LETTER_T	0x0074
#define T_CP874_LATIN_SMALL_LETTER_U	0x0075
#define T_CP874_LATIN_SMALL_LETTER_V	0x0076
#define T_CP874_LATIN_SMALL_LETTER_W	0x0077
#define T_CP874_LATIN_SMALL_LETTER_X	0x0078
#define T_CP874_LATIN_SMALL_LETTER_Y	0x0079
#define T_CP874_LATIN_SMALL_LETTER_Z	0x007A
#define T_CP874_LEFT_CURLY_BRACKET	0x007B
#define T_CP874_VERTICAL_LINE	0x007C
#define T_CP874_RIGHT_CURLY_BRACKET	0x007D
#define T_CP874_TILDE	0x007E
#define T_CP874_UNDEFINED_007F	0x007F
#define T_CP874_UNDEFINED_0080	0x0080
#define T_CP874_UNDEFINED_0081	0x0081
#define T_CP874_UNDEFINED_0082	0x0082
#define T_CP874_UNDEFINED_0083	0x0083
#define T_CP874_UNDEFINED_0084	0x0084
#define T_CP874_HORIZONTAL_ELLIPSIS	0x0085
#define T_CP874_UNDEFINED_0086	0x0086
#define T_CP874_UNDEFINED_0087	0x0087
#define T_CP874_UNDEFINED_0088	0x0088
#define T_CP874_UNDEFINED_0089	0x0089
#define T_CP874_UNDEFINED_008A	0x008A
#define T_CP874_UNDEFINED_008B	0x008B
#define T_CP874_UNDEFINED_008C	0x008C
#define T_CP874_UNDEFINED_008D	0x008D
#define T_CP874_UNDEFINED_008E	0x008E
#define T_CP874_UNDEFINED_008F	0x008F
#define T_CP874_UNDEFINED_0090	0x0090
#define T_CP874_LEFT_SINGLE_QUOTATION_MARK	0x0091
#define T_CP874_RIGHT_SINGLE_QUOTATION_MARK	0x0092
#define T_CP874_LEFT_DOUBLE_QUOTATION_MARK	0x0093
#define T_CP874_RIGHT_DOUBLE_QUOTATION_MARK	0x0094
#define T_CP874_BULLET	0x0095
#define T_CP874_EN_DASH	0x0096
#define T_CP874_EM_DASH	0x0097
#define T_CP874_UNDEFINED_0098	0x0098
#define T_CP874_UNDEFINED_0099	0x0099
#define T_CP874_UNDEFINED_009A	0x009A
#define T_CP874_UNDEFINED_009B	0x009B
#define T_CP874_UNDEFINED_009C	0x009C
#define T_CP874_UNDEFINED_009D	0x009D
#define T_CP874_UNDEFINED_009E	0x009E
#define T_CP874_UNDEFINED_009F	0x009F
#define T_CP874_NO_BREAK_SPACE	0x00A0
#define T_CP874_THAI_CHARACTER_KO_KAI	0x00A1
#define T_CP874_THAI_CHARACTER_KHO_KHAI	0x00A2
#define T_CP874_THAI_CHARACTER_KHO_KHUAT	0x00A3
#define T_CP874_THAI_CHARACTER_KHO_KHWAI	0x00A4
#define T_CP874_THAI_CHARACTER_KHO_KHON	0x00A5
#define T_CP874_THAI_CHARACTER_KHO_RAKHANG	0x00A6
#define T_CP874_THAI_CHARACTER_NGO_NGU	0x00A7
#define T_CP874_THAI_CHARACTER_CHO_CHAN	0x00A8
#define T_CP874_THAI_CHARACTER_CHO_CHING	0x00A9
#define T_CP874_THAI_CHARACTER_CHO_CHANG	0x00AA
#define T_CP874_THAI_CHARACTER_SO_SO	0x00AB
#define T_CP874_THAI_CHARACTER_CHO_CHOE	0x00AC
#define T_CP874_THAI_CHARACTER_YO_YING	0x00AD
#define T_CP874_THAI_CHARACTER_DO_CHADA	0x00AE
#define T_CP874_THAI_CHARACTER_TO_PATAK	0x00AF
#define T_CP874_THAI_CHARACTER_THO_THAN	0x00B0
#define T_CP874_THAI_CHARACTER_THO_NANGMONTHO	0x00B1
#define T_CP874_THAI_CHARACTER_THO_PHUTHAO	0x00B2
#define T_CP874_THAI_CHARACTER_NO_NEN	0x00B3
#define T_CP874_THAI_CHARACTER_DO_DEK	0x00B4
#define T_CP874_THAI_CHARACTER_TO_TAO	0x00B5
#define T_CP874_THAI_CHARACTER_THO_THUNG	0x00B6
#define T_CP874_THAI_CHARACTER_THO_THAHAN	0x00B7
#define T_CP874_THAI_CHARACTER_THO_THONG	0x00B8
#define T_CP874_THAI_CHARACTER_NO_NU	0x00B9
#define T_CP874_THAI_CHARACTER_BO_BAIMAI	0x00BA
#define T_CP874_THAI_CHARACTER_PO_PLA	0x00BB
#define T_CP874_THAI_CHARACTER_PHO_PHUNG	0x00BC
#define T_CP874_THAI_CHARACTER_FO_FA	0x00BD
#define T_CP874_THAI_CHARACTER_PHO_PHAN	0x00BE
#define T_CP874_THAI_CHARACTER_FO_FAN	0x00BF
#define T_CP874_THAI_CHARACTER_PHO_SAMPHAO	0x00C0
#define T_CP874_THAI_CHARACTER_MO_MA	0x00C1
#define T_CP874_THAI_CHARACTER_YO_YAK	0x00C2
#define T_CP874_THAI_CHARACTER_RO_RUA	0x00C3
#define T_CP874_THAI_CHARACTER_RU	0x00C4
#define T_CP874_THAI_CHARACTER_LO_LING	0x00C5
#define T_CP874_THAI_CHARACTER_LU	0x00C6
#define T_CP874_THAI_CHARACTER_WO_WAEN	0x00C7
#define T_CP874_THAI_CHARACTER_SO_SALA	0x00C8
#define T_CP874_THAI_CHARACTER_SO_RUSI	0x00C9
#define T_CP874_THAI_CHARACTER_SO_SUA	0x00CA
#define T_CP874_THAI_CHARACTER_HO_HIP	0x00CB
#define T_CP874_THAI_CHARACTER_LO_CHULA	0x00CC
#define T_CP874_THAI_CHARACTER_O_ANG	0x00CD
#define T_CP874_THAI_CHARACTER_HO_NOKHUK	0x00CE
#define T_CP874_THAI_CHARACTER_PAIYANNOI	0x00CF
#define T_CP874_THAI_CHARACTER_SARA_A	0x00D0
#define T_CP874_THAI_CHARACTER_MAI_HAN_AKAT	0x00D1
#define T_CP874_THAI_CHARACTER_SARA_AA	0x00D2
#define T_CP874_THAI_CHARACTER_SARA_AM	0x00D3
#define T_CP874_THAI_CHARACTER_SARA_I	0x00D4
#define T_CP874_THAI_CHARACTER_SARA_II	0x00D5
#define T_CP874_THAI_CHARACTER_SARA_UE	0x00D6
#define T_CP874_THAI_CHARACTER_SARA_UEE	0x00D7
#define T_CP874_THAI_CHARACTER_SARA_U	0x00D8
#define T_CP874_THAI_CHARACTER_SARA_UU	0x00D9
#define T_CP874_THAI_CHARACTER_PHINTHU	0x00DA
#define T_CP874_UNDEFINED_00DB	0x00DB
#define T_CP874_UNDEFINED_00DC	0x00DC
#define T_CP874_UNDEFINED_00DD	0x00DD
#define T_CP874_UNDEFINED_00DE	0x00DE
#define T_CP874_THAI_CURRENCY_SYMBOL_BAHT	0x00DF
#define T_CP874_THAI_CHARACTER_SARA_E	0x00E0
#define T_CP874_THAI_CHARACTER_SARA_AE	0x00E1
#define T_CP874_THAI_CHARACTER_SARA_O	0x00E2
#define T_CP874_THAI_CHARACTER_SARA_AI_MAIMUAN	0x00E3
#define T_CP874_THAI_CHARACTER_SARA_AI_MAIMALAI	0x00E4
#define T_CP874_THAI_CHARACTER_LAKKHANGYAO	0x00E5
#define T_CP874_THAI_CHARACTER_MAIYAMOK	0x00E6
#define T_CP874_THAI_CHARACTER_MAITAIKHU	0x00E7
#define T_CP874_THAI_CHARACTER_MAI_EK	0x00E8
#define T_CP874_THAI_CHARACTER_MAI_THO	0x00E9
#define T_CP874_THAI_CHARACTER_MAI_TRI	0x00EA
#define T_CP874_THAI_CHARACTER_MAI_CHATTAWA	0x00EB
#define T_CP874_THAI_CHARACTER_THANTHAKHAT	0x00EC
#define T_CP874_THAI_CHARACTER_NIKHAHIT	0x00ED
#define T_CP874_THAI_CHARACTER_YAMAKKAN	0x00EE
#define T_CP874_THAI_CHARACTER_FONGMAN	0x00EF
#define T_CP874_THAI_DIGIT_ZERO	0x00F0
#define T_CP874_THAI_DIGIT_ONE	0x00F1
#define T_CP874_THAI_DIGIT_TWO	0x00F2
#define T_CP874_THAI_DIGIT_THREE	0x00F3
#define T_CP874_THAI_DIGIT_FOUR	0x00F4
#define T_CP874_THAI_DIGIT_FIVE	0x00F5
#define T_CP874_THAI_DIGIT_SIX	0x00F6
#define T_CP874_THAI_DIGIT_SEVEN	0x00F7
#define T_CP874_THAI_DIGIT_EIGHT	0x00F8
#define T_CP874_THAI_DIGIT_NINE	0x00F9
#define T_CP874_THAI_CHARACTER_ANGKHANKHU	0x00FA
#define T_CP874_THAI_CHARACTER_KHOMUT	0x00FB
#define T_CP874_UNDEFINED_00FC	0x00FC
#define T_CP874_UNDEFINED_00FD	0x00FD
#define T_CP874_UNDEFINED_00FE	0x00FE
#define T_CP874_UNDEFINED_00FF	0x00FF

/* list of all characters */
#define T_LIST_CP874(EL) \
    EL(_NULL) \
    EL(_START_OF_HEADING) \
    EL(_START_OF_TEXT) \
    EL(_END_OF_TEXT) \
    EL(_END_OF_TRANSMISSION) \
    EL(_ENQUIRY) \
    EL(_ACKNOWLEDGE) \
    EL(_BELL) \
    EL(_BACKSPACE) \
    EL(_HORIZONTAL_TABULATION) \
    EL(_LINE_FEED) \
    EL(_VERTICAL_TABULATION) \
    EL(_FORM_FEED) \
    EL(_CARRIAGE_RETURN) \
    EL(_SHIFT_OUT) \
    EL(_SHIFT_IN) \
    EL(_DATA_LINK_ESCAPE) \
    EL(_DEVICE_CONTROL_ONE) \
    EL(_DEVICE_CONTROL_TWO) \
    EL(_DEVICE_CONTROL_THREE) \
    EL(_DEVICE_CONTROL_FOUR) \
    EL(_NEGATIVE_ACKNOWLEDGE) \
    EL(_SYNCHRONOUS_IDLE) \
    EL(_END_OF_TRANSMISSION_BLOCK) \
    EL(_CANCEL) \
    EL(_END_OF_MEDIUM) \
    EL(_SUBSTITUTE) \
    EL(_ESCAPE) \
    EL(_FILE_SEPARATOR) \
    EL(_GROUP_SEPARATOR) \
    EL(_RECORD_SEPARATOR) \
    EL(_UNIT_SEPARATOR) \
    EL(_SPACE) \
    EL(_EXCLAMATION_MARK) \
    EL(_QUOTATION_MARK) \
    EL(_NUMBER_SIGN) \
    EL(_DOLLAR_SIGN) \
    EL(_PERCENT_SIGN) \
    EL(_AMPERSAND) \
    EL(_APOSTROPHE) \
    EL(_LEFT_PARENTHESIS) \
    EL(_RIGHT_PARENTHESIS) \
    EL(_ASTERISK) \
    EL(_PLUS_SIGN) \
    EL(_COMMA) \
    EL(_HYPHEN_MINUS) \
    EL(_FULL_STOP) \
    EL(_SOLIDUS) \
    EL(_DIGIT_ZERO) \
    EL(_DIGIT_ONE) \
    EL(_DIGIT_TWO) \
    EL(_DIGIT_THREE) \
    EL(_DIGIT_FOUR) \
    EL(_DIGIT_FIVE) \
    EL(_DIGIT_SIX) \
    EL(_DIGIT_SEVEN) \
    EL(_DIGIT_EIGHT) \
    EL(_DIGIT_NINE) \
    EL(_COLON) \
    EL(_SEMICOLON) \
    EL(_LESS_THAN_SIGN) \
    EL(_EQUALS_SIGN) \
    EL(_GREATER_THAN_SIGN) \
    EL(_QUESTION_MARK) \
    EL(_COMMERCIAL_AT) \
    EL(_LATIN_CAPITAL_LETTER_A) \
    EL(_LATIN_CAPITAL_LETTER_B) \
    EL(_LATIN_CAPITAL_LETTER_C) \
    EL(_LATIN_CAPITAL_LETTER_D) \
    EL(_LATIN_CAPITAL_LETTER_E) \
    EL(_LATIN_CAPITAL_LETTER_F) \
    EL(_LATIN_CAPITAL_LETTER_G) \
    EL(_LATIN_CAPITAL_LETTER_H) \
    EL(_LATIN_CAPITAL_LETTER_I) \
    EL(_LATIN_CAPITAL_LETTER_J) \
    EL(_LATIN_CAPITAL_LETTER_K) \
    EL(_LATIN_CAPITAL_LETTER_L) \
    EL(_LATIN_CAPITAL_LETTER_M) \
    EL(_LATIN_CAPITAL_LETTER_N) \
    EL(_LATIN_CAPITAL_LETTER_O) \
    EL(_LATIN_CAPITAL_LETTER_P) \
    EL(_LATIN_CAPITAL_LETTER_Q) \
    EL(_LATIN_CAPITAL_LETTER_R) \
    EL(_LATIN_CAPITAL_LETTER_S) \
    EL(_LATIN_CAPITAL_LETTER_T) \
    EL(_LATIN_CAPITAL_LETTER_U) \
    EL(_LATIN_CAPITAL_LETTER_V) \
    EL(_LATIN_CAPITAL_LETTER_W) \
    EL(_LATIN_CAPITAL_LETTER_X) \
    EL(_LATIN_CAPITAL_LETTER_Y) \
    EL(_LATIN_CAPITAL_LETTER_Z) \
    EL(_LEFT_SQUARE_BRACKET) \
    EL(_REVERSE_SOLIDUS) \
    EL(_RIGHT_SQUARE_BRACKET) \
    EL(_CIRCUMFLEX_ACCENT) \
    EL(_LOW_LINE) \
    EL(_GRAVE_ACCENT) \
    EL(_LATIN_SMALL_LETTER_A) \
    EL(_LATIN_SMALL_LETTER_B) \
    EL(_LATIN_SMALL_LETTER_C) \
    EL(_LATIN_SMALL_LETTER_D) \
    EL(_LATIN_SMALL_LETTER_E) \
    EL(_LATIN_SMALL_LETTER_F) \
    EL(_LATIN_SMALL_LETTER_G) \
    EL(_LATIN_SMALL_LETTER_H) \
    EL(_LATIN_SMALL_LETTER_I) \
    EL(_LATIN_SMALL_LETTER_J) \
    EL(_LATIN_SMALL_LETTER_K) \
    EL(_LATIN_SMALL_LETTER_L) \
    EL(_LATIN_SMALL_LETTER_M) \
    EL(_LATIN_SMALL_LETTER_N) \
    EL(_LATIN_SMALL_LETTER_O) \
    EL(_LATIN_SMALL_LETTER_P) \
    EL(_LATIN_SMALL_LETTER_Q) \
    EL(_LATIN_SMALL_LETTER_R) \
    EL(_LATIN_SMALL_LETTER_S) \
    EL(_LATIN_SMALL_LETTER_T) \
    EL(_LATIN_SMALL_LETTER_U) \
    EL(_LATIN_SMALL_LETTER_V) \
    EL(_LATIN_SMALL_LETTER_W) \
    EL(_LATIN_SMALL_LETTER_X) \
    EL(_LATIN_SMALL_LETTER_Y) \
    EL(_LATIN_SMALL_LETTER_Z) \
    EL(_LEFT_CURLY_BRACKET) \
    EL(_VERTICAL_LINE) \
    EL(_RIGHT_CURLY_BRACKET) \
    EL(_TILDE) \
    EL(_UNDEFINED_007F) \
    EL(_UNDEFINED_0080) \
    EL(_UNDEFINED_0081) \
    EL(_UNDEFINED_0082) \
    EL(_UNDEFINED_0083) \
    EL(_UNDEFINED_0084) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_UNDEFINED_0086) \
    EL(_UNDEFINED_0087) \
    EL(_UNDEFINED_0088) \
    EL(_UNDEFINED_0089) \
    EL(_UNDEFINED_008A) \
    EL(_UNDEFINED_008B) \
    EL(_UNDEFINED_008C) \
    EL(_UNDEFINED_008D) \
    EL(_UNDEFINED_008E) \
    EL(_UNDEFINED_008F) \
    EL(_UNDEFINED_0090) \
    EL(_LEFT_SINGLE_QUOTATION_MARK) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_LEFT_DOUBLE_QUOTATION_MARK) \
    EL(_RIGHT_DOUBLE_QUOTATION_MARK) \
    EL(_BULLET) \
    EL(_EN_DASH) \
    EL(_EM_DASH) \
    EL(_UNDEFINED_0098) \
    EL(_UNDEFINED_0099) \
    EL(_UNDEFINED_009A) \
    EL(_UNDEFINED_009B) \
    EL(_UNDEFINED_009C) \
    EL(_UNDEFINED_009D) \
    EL(_UNDEFINED_009E) \
    EL(_UNDEFINED_009F) \
    EL(_NO_BREAK_SPACE) \
    EL(_THAI_CHARACTER_KO_KAI) \
    EL(_THAI_CHARACTER_KHO_KHAI) \
    EL(_THAI_CHARACTER_KHO_KHUAT) \
    EL(_THAI_CHARACTER_KHO_KHWAI) \
    EL(_THAI_CHARACTER_KHO_KHON) \
    EL(_THAI_CHARACTER_KHO_RAKHANG) \
    EL(_THAI_CHARACTER_NGO_NGU) \
    EL(_THAI_CHARACTER_CHO_CHAN) \
    EL(_THAI_CHARACTER_CHO_CHING) \
    EL(_THAI_CHARACTER_CHO_CHANG) \
    EL(_THAI_CHARACTER_SO_SO) \
    EL(_THAI_CHARACTER_CHO_CHOE) \
    EL(_THAI_CHARACTER_YO_YING) \
    EL(_THAI_CHARACTER_DO_CHADA) \
    EL(_THAI_CHARACTER_TO_PATAK) \
    EL(_THAI_CHARACTER_THO_THAN) \
    EL(_THAI_CHARACTER_THO_NANGMONTHO) \
    EL(_THAI_CHARACTER_THO_PHUTHAO) \
    EL(_THAI_CHARACTER_NO_NEN) \
    EL(_THAI_CHARACTER_DO_DEK) \
    EL(_THAI_CHARACTER_TO_TAO) \
    EL(_THAI_CHARACTER_THO_THUNG) \
    EL(_THAI_CHARACTER_THO_THAHAN) \
    EL(_THAI_CHARACTER_THO_THONG) \
    EL(_THAI_CHARACTER_NO_NU) \
    EL(_THAI_CHARACTER_BO_BAIMAI) \
    EL(_THAI_CHARACTER_PO_PLA) \
    EL(_THAI_CHARACTER_PHO_PHUNG) \
    EL(_THAI_CHARACTER_FO_FA) \
    EL(_THAI_CHARACTER_PHO_PHAN) \
    EL(_THAI_CHARACTER_FO_FAN) \
    EL(_THAI_CHARACTER_PHO_SAMPHAO) \
    EL(_THAI_CHARACTER_MO_MA) \
    EL(_THAI_CHARACTER_YO_YAK) \
    EL(_THAI_CHARACTER_RO_RUA) \
    EL(_THAI_CHARACTER_RU) \
    EL(_THAI_CHARACTER_LO_LING) \
    EL(_THAI_CHARACTER_LU) \
    EL(_THAI_CHARACTER_WO_WAEN) \
    EL(_THAI_CHARACTER_SO_SALA) \
    EL(_THAI_CHARACTER_SO_RUSI) \
    EL(_THAI_CHARACTER_SO_SUA) \
    EL(_THAI_CHARACTER_HO_HIP) \
    EL(_THAI_CHARACTER_LO_CHULA) \
    EL(_THAI_CHARACTER_O_ANG) \
    EL(_THAI_CHARACTER_HO_NOKHUK) \
    EL(_THAI_CHARACTER_PAIYANNOI) \
    EL(_THAI_CHARACTER_SARA_A) \
    EL(_THAI_CHARACTER_MAI_HAN_AKAT) \
    EL(_THAI_CHARACTER_SARA_AA) \
    EL(_THAI_CHARACTER_SARA_AM) \
    EL(_THAI_CHARACTER_SARA_I) \
    EL(_THAI_CHARACTER_SARA_II) \
    EL(_THAI_CHARACTER_SARA_UE) \
    EL(_THAI_CHARACTER_SARA_UEE) \
    EL(_THAI_CHARACTER_SARA_U) \
    EL(_THAI_CHARACTER_SARA_UU) \
    EL(_THAI_CHARACTER_PHINTHU) \
    EL(_UNDEFINED_00DB) \
    EL(_UNDEFINED_00DC) \
    EL(_UNDEFINED_00DD) \
    EL(_UNDEFINED_00DE) \
    EL(_THAI_CURRENCY_SYMBOL_BAHT) \
    EL(_THAI_CHARACTER_SARA_E) \
    EL(_THAI_CHARACTER_SARA_AE) \
    EL(_THAI_CHARACTER_SARA_O) \
    EL(_THAI_CHARACTER_SARA_AI_MAIMUAN) \
    EL(_THAI_CHARACTER_SARA_AI_MAIMALAI) \
    EL(_THAI_CHARACTER_LAKKHANGYAO) \
    EL(_THAI_CHARACTER_MAIYAMOK) \
    EL(_THAI_CHARACTER_MAITAIKHU) \
    EL(_THAI_CHARACTER_MAI_EK) \
    EL(_THAI_CHARACTER_MAI_THO) \
    EL(_THAI_CHARACTER_MAI_TRI) \
    EL(_THAI_CHARACTER_MAI_CHATTAWA) \
    EL(_THAI_CHARACTER_THANTHAKHAT) \
    EL(_THAI_CHARACTER_NIKHAHIT) \
    EL(_THAI_CHARACTER_YAMAKKAN) \
    EL(_THAI_CHARACTER_FONGMAN) \
    EL(_THAI_DIGIT_ZERO) \
    EL(_THAI_DIGIT_ONE) \
    EL(_THAI_DIGIT_TWO) \
    EL(_THAI_DIGIT_THREE) \
    EL(_THAI_DIGIT_FOUR) \
    EL(_THAI_DIGIT_FIVE) \
    EL(_THAI_DIGIT_SIX) \
    EL(_THAI_DIGIT_SEVEN) \
    EL(_THAI_DIGIT_EIGHT) \
    EL(_THAI_DIGIT_NINE) \
    EL(_THAI_CHARACTER_ANGKHANKHU) \
    EL(_THAI_CHARACTER_KHOMUT) \
    EL(_UNDEFINED_00FC) \
    EL(_UNDEFINED_00FD) \
    EL(_UNDEFINED_00FE) \
    EL(_UNDEFINED_00FF)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_CP874(EL) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_LEFT_SINGLE_QUOTATION_MARK) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_LEFT_DOUBLE_QUOTATION_MARK) \
    EL(_RIGHT_DOUBLE_QUOTATION_MARK) \
    EL(_BULLET) \
    EL(_EN_DASH) \
    EL(_EM_DASH) \
    EL(_THAI_CHARACTER_KO_KAI) \
    EL(_THAI_CHARACTER_KHO_KHAI) \
    EL(_THAI_CHARACTER_KHO_KHUAT) \
    EL(_THAI_CHARACTER_KHO_KHWAI) \
    EL(_THAI_CHARACTER_KHO_KHON) \
    EL(_THAI_CHARACTER_KHO_RAKHANG) \
    EL(_THAI_CHARACTER_NGO_NGU) \
    EL(_THAI_CHARACTER_CHO_CHAN) \
    EL(_THAI_CHARACTER_CHO_CHING) \
    EL(_THAI_CHARACTER_CHO_CHANG) \
    EL(_THAI_CHARACTER_SO_SO) \
    EL(_THAI_CHARACTER_CHO_CHOE) \
    EL(_THAI_CHARACTER_YO_YING) \
    EL(_THAI_CHARACTER_DO_CHADA) \
    EL(_THAI_CHARACTER_TO_PATAK) \
    EL(_THAI_CHARACTER_THO_THAN) \
    EL(_THAI_CHARACTER_THO_NANGMONTHO) \
    EL(_THAI_CHARACTER_THO_PHUTHAO) \
    EL(_THAI_CHARACTER_NO_NEN) \
    EL(_THAI_CHARACTER_DO_DEK) \
    EL(_THAI_CHARACTER_TO_TAO) \
    EL(_THAI_CHARACTER_THO_THUNG) \
    EL(_THAI_CHARACTER_THO_THAHAN) \
    EL(_THAI_CHARACTER_THO_THONG) \
    EL(_THAI_CHARACTER_NO_NU) \
    EL(_THAI_CHARACTER_BO_BAIMAI) \
    EL(_THAI_CHARACTER_PO_PLA) \
    EL(_THAI_CHARACTER_PHO_PHUNG) \
    EL(_THAI_CHARACTER_FO_FA) \
    EL(_THAI_CHARACTER_PHO_PHAN) \
    EL(_THAI_CHARACTER_FO_FAN) \
    EL(_THAI_CHARACTER_PHO_SAMPHAO) \
    EL(_THAI_CHARACTER_MO_MA) \
    EL(_THAI_CHARACTER_YO_YAK) \
    EL(_THAI_CHARACTER_RO_RUA) \
    EL(_THAI_CHARACTER_RU) \
    EL(_THAI_CHARACTER_LO_LING) \
    EL(_THAI_CHARACTER_LU) \
    EL(_THAI_CHARACTER_WO_WAEN) \
    EL(_THAI_CHARACTER_SO_SALA) \
    EL(_THAI_CHARACTER_SO_RUSI) \
    EL(_THAI_CHARACTER_SO_SUA) \
    EL(_THAI_CHARACTER_HO_HIP) \
    EL(_THAI_CHARACTER_LO_CHULA) \
    EL(_THAI_CHARACTER_O_ANG) \
    EL(_THAI_CHARACTER_HO_NOKHUK) \
    EL(_THAI_CHARACTER_PAIYANNOI) \
    EL(_THAI_CHARACTER_SARA_A) \
    EL(_THAI_CHARACTER_MAI_HAN_AKAT) \
    EL(_THAI_CHARACTER_SARA_AA) \
    EL(_THAI_CHARACTER_SARA_AM) \
    EL(_THAI_CHARACTER_SARA_I) \
    EL(_THAI_CHARACTER_SARA_II) \
    EL(_THAI_CHARACTER_SARA_UE) \
    EL(_THAI_CHARACTER_SARA_UEE) \
    EL(_THAI_CHARACTER_SARA_U) \
    EL(_THAI_CHARACTER_SARA_UU) \
    EL(_THAI_CHARACTER_PHINTHU) \
    EL(_UNDEFINED_00DB) \
    EL(_UNDEFINED_00DC) \
    EL(_UNDEFINED_00DD) \
    EL(_UNDEFINED_00DE) \
    EL(_THAI_CURRENCY_SYMBOL_BAHT) \
    EL(_THAI_CHARACTER_SARA_E) \
    EL(_THAI_CHARACTER_SARA_AE) \
    EL(_THAI_CHARACTER_SARA_O) \
    EL(_THAI_CHARACTER_SARA_AI_MAIMUAN) \
    EL(_THAI_CHARACTER_SARA_AI_MAIMALAI) \
    EL(_THAI_CHARACTER_LAKKHANGYAO) \
    EL(_THAI_CHARACTER_MAIYAMOK) \
    EL(_THAI_CHARACTER_MAITAIKHU) \
    EL(_THAI_CHARACTER_MAI_EK) \
    EL(_THAI_CHARACTER_MAI_THO) \
    EL(_THAI_CHARACTER_MAI_TRI) \
    EL(_THAI_CHARACTER_MAI_CHATTAWA) \
    EL(_THAI_CHARACTER_THANTHAKHAT) \
    EL(_THAI_CHARACTER_NIKHAHIT) \
    EL(_THAI_CHARACTER_YAMAKKAN) \
    EL(_THAI_CHARACTER_FONGMAN) \
    EL(_THAI_DIGIT_ZERO) \
    EL(_THAI_DIGIT_ONE) \
    EL(_THAI_DIGIT_TWO) \
    EL(_THAI_DIGIT_THREE) \
    EL(_THAI_DIGIT_FOUR) \
    EL(_THAI_DIGIT_FIVE) \
    EL(_THAI_DIGIT_SIX) \
    EL(_THAI_DIGIT_SEVEN) \
    EL(_THAI_DIGIT_EIGHT) \
    EL(_THAI_DIGIT_NINE) \
    EL(_THAI_CHARACTER_ANGKHANKHU) \
    EL(_THAI_CHARACTER_KHOMUT) \
    EL(_UNDEFINED_00FC) \
    EL(_UNDEFINED_00FD) \
    EL(_UNDEFINED_00FE) \
    EL(_UNDEFINED_00FF)

#endif /* _TUTF_CP874_H */
