
/*
 * This file was automatically generated from unicode
 * charset definition files http://unicode.org/Public/MAPPINGS/
 * using the script twin/scripts/helper-from-unicode.org.bash
 *
 * PLEASE DO NOT EDIT!
 */


#ifndef _TUTF_MAC_GURMUKHI_H
#define _TUTF_MAC_GURMUKHI_H

#define T_MAC_GURMUKHI_CTRL_NULL	0x0000
#define T_MAC_GURMUKHI_CTRL_START_OF_HEADING	0x0001
#define T_MAC_GURMUKHI_CTRL_START_OF_TEXT	0x0002
#define T_MAC_GURMUKHI_CTRL_END_OF_TEXT	0x0003
#define T_MAC_GURMUKHI_CTRL_END_OF_TRANSMISSION	0x0004
#define T_MAC_GURMUKHI_CTRL_ENQUIRY	0x0005
#define T_MAC_GURMUKHI_CTRL_ACKNOWLEDGE	0x0006
#define T_MAC_GURMUKHI_CTRL_BELL	0x0007
#define T_MAC_GURMUKHI_CTRL_BACKSPACE	0x0008
#define T_MAC_GURMUKHI_CTRL_CHARACTER_TABULATION	0x0009
#define T_MAC_GURMUKHI_CTRL_LINE_FEED	0x000A
#define T_MAC_GURMUKHI_CTRL_LINE_TABULATION	0x000B
#define T_MAC_GURMUKHI_CTRL_FORM_FEED	0x000C
#define T_MAC_GURMUKHI_CTRL_CARRIAGE_RETURN	0x000D
#define T_MAC_GURMUKHI_CTRL_SHIFT_OUT	0x000E
#define T_MAC_GURMUKHI_CTRL_SHIFT_IN	0x000F
#define T_MAC_GURMUKHI_CTRL_DATA_LINK_ESCAPE	0x0010
#define T_MAC_GURMUKHI_CTRL_DEVICE_CONTROL_ONE	0x0011
#define T_MAC_GURMUKHI_CTRL_DEVICE_CONTROL_TWO	0x0012
#define T_MAC_GURMUKHI_CTRL_DEVICE_CONTROL_THREE	0x0013
#define T_MAC_GURMUKHI_CTRL_DEVICE_CONTROL_FOUR	0x0014
#define T_MAC_GURMUKHI_CTRL_NEGATIVE_ACKNOWLEDGE	0x0015
#define T_MAC_GURMUKHI_CTRL_SYNCHRONOUS_IDLE	0x0016
#define T_MAC_GURMUKHI_CTRL_END_OF_TRANSMISSION_BLOCK	0x0017
#define T_MAC_GURMUKHI_CTRL_CANCEL	0x0018
#define T_MAC_GURMUKHI_CTRL_END_OF_MEDIUM	0x0019
#define T_MAC_GURMUKHI_CTRL_SUBSTITUTE	0x001A
#define T_MAC_GURMUKHI_CTRL_ESCAPE	0x001B
#define T_MAC_GURMUKHI_CTRL_INFORMATION_SEPARATOR_FOUR	0x001C
#define T_MAC_GURMUKHI_CTRL_INFORMATION_SEPARATOR_THREE	0x001D
#define T_MAC_GURMUKHI_CTRL_INFORMATION_SEPARATOR_TWO	0x001E
#define T_MAC_GURMUKHI_CTRL_INFORMATION_SEPARATOR_ONE	0x001F
#define T_MAC_GURMUKHI_SPACE	0x0020
#define T_MAC_GURMUKHI_EXCLAMATION_MARK	0x0021
#define T_MAC_GURMUKHI_QUOTATION_MARK	0x0022
#define T_MAC_GURMUKHI_NUMBER_SIGN	0x0023
#define T_MAC_GURMUKHI_DOLLAR_SIGN	0x0024
#define T_MAC_GURMUKHI_PERCENT_SIGN	0x0025
#define T_MAC_GURMUKHI_AMPERSAND	0x0026
#define T_MAC_GURMUKHI_APOSTROPHE	0x0027
#define T_MAC_GURMUKHI_LEFT_PARENTHESIS	0x0028
#define T_MAC_GURMUKHI_RIGHT_PARENTHESIS	0x0029
#define T_MAC_GURMUKHI_ASTERISK	0x002A
#define T_MAC_GURMUKHI_PLUS_SIGN	0x002B
#define T_MAC_GURMUKHI_COMMA	0x002C
#define T_MAC_GURMUKHI_HYPHEN_MINUS	0x002D
#define T_MAC_GURMUKHI_FULL_STOP	0x002E
#define T_MAC_GURMUKHI_SOLIDUS	0x002F
#define T_MAC_GURMUKHI_DIGIT_ZERO	0x0030
#define T_MAC_GURMUKHI_DIGIT_ONE	0x0031
#define T_MAC_GURMUKHI_DIGIT_TWO	0x0032
#define T_MAC_GURMUKHI_DIGIT_THREE	0x0033
#define T_MAC_GURMUKHI_DIGIT_FOUR	0x0034
#define T_MAC_GURMUKHI_DIGIT_FIVE	0x0035
#define T_MAC_GURMUKHI_DIGIT_SIX	0x0036
#define T_MAC_GURMUKHI_DIGIT_SEVEN	0x0037
#define T_MAC_GURMUKHI_DIGIT_EIGHT	0x0038
#define T_MAC_GURMUKHI_DIGIT_NINE	0x0039
#define T_MAC_GURMUKHI_COLON	0x003A
#define T_MAC_GURMUKHI_SEMICOLON	0x003B
#define T_MAC_GURMUKHI_LESS_THAN_SIGN	0x003C
#define T_MAC_GURMUKHI_EQUALS_SIGN	0x003D
#define T_MAC_GURMUKHI_GREATER_THAN_SIGN	0x003E
#define T_MAC_GURMUKHI_QUESTION_MARK	0x003F
#define T_MAC_GURMUKHI_COMMERCIAL_AT	0x0040
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_A	0x0041
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_B	0x0042
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_C	0x0043
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_D	0x0044
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_E	0x0045
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_F	0x0046
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_G	0x0047
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_H	0x0048
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_I	0x0049
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_J	0x004A
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_K	0x004B
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_L	0x004C
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_M	0x004D
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_N	0x004E
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_O	0x004F
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_P	0x0050
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_Q	0x0051
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_R	0x0052
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_S	0x0053
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_T	0x0054
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_U	0x0055
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_V	0x0056
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_W	0x0057
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_X	0x0058
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_Y	0x0059
#define T_MAC_GURMUKHI_LATIN_CAPITAL_LETTER_Z	0x005A
#define T_MAC_GURMUKHI_LEFT_SQUARE_BRACKET	0x005B
#define T_MAC_GURMUKHI_REVERSE_SOLIDUS	0x005C
#define T_MAC_GURMUKHI_RIGHT_SQUARE_BRACKET	0x005D
#define T_MAC_GURMUKHI_CIRCUMFLEX_ACCENT	0x005E
#define T_MAC_GURMUKHI_LOW_LINE	0x005F
#define T_MAC_GURMUKHI_GRAVE_ACCENT	0x0060
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_A	0x0061
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_B	0x0062
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_C	0x0063
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_D	0x0064
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_E	0x0065
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_F	0x0066
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_G	0x0067
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_H	0x0068
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_I	0x0069
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_J	0x006A
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_K	0x006B
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_L	0x006C
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_M	0x006D
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_N	0x006E
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_O	0x006F
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_P	0x0070
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_Q	0x0071
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_R	0x0072
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_S	0x0073
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_T	0x0074
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_U	0x0075
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_V	0x0076
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_W	0x0077
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_X	0x0078
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_Y	0x0079
#define T_MAC_GURMUKHI_LATIN_SMALL_LETTER_Z	0x007A
#define T_MAC_GURMUKHI_LEFT_CURLY_BRACKET	0x007B
#define T_MAC_GURMUKHI_VERTICAL_LINE	0x007C
#define T_MAC_GURMUKHI_RIGHT_CURLY_BRACKET	0x007D
#define T_MAC_GURMUKHI_TILDE	0x007E
#define T_MAC_GURMUKHI_CTRL_DELETE	0x007F
#define T_MAC_GURMUKHI_MULTIPLICATION_SIGN	0x0080
#define T_MAC_GURMUKHI_MINUS_SIGN	0x0081
#define T_MAC_GURMUKHI_EN_DASH	0x0082
#define T_MAC_GURMUKHI_EM_DASH	0x0083
#define T_MAC_GURMUKHI_LEFT_SINGLE_QUOTATION_MARK	0x0084
#define T_MAC_GURMUKHI_RIGHT_SINGLE_QUOTATION_MARK	0x0085
#define T_MAC_GURMUKHI_HORIZONTAL_ELLIPSIS	0x0086
#define T_MAC_GURMUKHI_BULLET	0x0087
#define T_MAC_GURMUKHI_COPYRIGHT_SIGN	0x0088
#define T_MAC_GURMUKHI_REGISTERED_SIGN	0x0089
#define T_MAC_GURMUKHI_TRADE_MARK_SIGN	0x008A
#define T_MAC_GURMUKHI_UNDEFINED_008B	0x008B
#define T_MAC_GURMUKHI_UNDEFINED_008C	0x008C
#define T_MAC_GURMUKHI_UNDEFINED_008D	0x008D
#define T_MAC_GURMUKHI_UNDEFINED_008E	0x008E
#define T_MAC_GURMUKHI_UNDEFINED_008F	0x008F
#define T_MAC_GURMUKHI_GURMUKHI_ADDAK	0x0090
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_RRA	0x0091
#define T_MAC_GURMUKHI_GURMUKHI_URA	0x0092
#define T_MAC_GURMUKHI_GURMUKHI_IRI	0x0093
#define T_MAC_GURMUKHI_GURMUKHI_EK_ONKAR	0x0094
#define T_MAC_GURMUKHI_UNDEFINED_0095	0x0095
#define T_MAC_GURMUKHI_UNDEFINED_0096	0x0096
#define T_MAC_GURMUKHI_UNDEFINED_0097	0x0097
#define T_MAC_GURMUKHI_UNDEFINED_0098	0x0098
#define T_MAC_GURMUKHI_UNDEFINED_0099	0x0099
#define T_MAC_GURMUKHI_UNDEFINED_009A	0x009A
#define T_MAC_GURMUKHI_UNDEFINED_009B	0x009B
#define T_MAC_GURMUKHI_UNDEFINED_009C	0x009C
#define T_MAC_GURMUKHI_UNDEFINED_009D	0x009D
#define T_MAC_GURMUKHI_UNDEFINED_009E	0x009E
#define T_MAC_GURMUKHI_UNDEFINED_009F	0x009F
#define T_MAC_GURMUKHI_UNDEFINED_00A0	0x00A0
#define T_MAC_GURMUKHI_UNDEFINED_00A1	0x00A1
#define T_MAC_GURMUKHI_GURMUKHI_SIGN_BINDI	0x00A2
#define T_MAC_GURMUKHI_UNDEFINED_00A3	0x00A3
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_A	0x00A4
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_AA	0x00A5
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_I	0x00A6
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_II	0x00A7
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_U	0x00A8
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_UU	0x00A9
#define T_MAC_GURMUKHI_UNDEFINED_00AA	0x00AA
#define T_MAC_GURMUKHI_UNDEFINED_00AB	0x00AB
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_EE	0x00AC
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_AI	0x00AD
#define T_MAC_GURMUKHI_UNDEFINED_00AE	0x00AE
#define T_MAC_GURMUKHI_UNDEFINED_00AF	0x00AF
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_OO	0x00B0
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_AU	0x00B1
#define T_MAC_GURMUKHI_UNDEFINED_00B2	0x00B2
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_KA	0x00B3
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_KHA	0x00B4
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_GA	0x00B5
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_GHA	0x00B6
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_NGA	0x00B7
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_CA	0x00B8
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_CHA	0x00B9
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_JA	0x00BA
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_JHA	0x00BB
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_NYA	0x00BC
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_TTA	0x00BD
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_TTHA	0x00BE
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_DDA	0x00BF
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_DDHA	0x00C0
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_NNA	0x00C1
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_TA	0x00C2
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_THA	0x00C3
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_DA	0x00C4
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_DHA	0x00C5
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_NA	0x00C6
#define T_MAC_GURMUKHI_UNDEFINED_00C7	0x00C7
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_PA	0x00C8
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_PHA	0x00C9
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_BA	0x00CA
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_BHA	0x00CB
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_MA	0x00CC
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_YA	0x00CD
#define T_MAC_GURMUKHI_UNDEFINED_00CE	0x00CE
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_RA	0x00CF
#define T_MAC_GURMUKHI_UNDEFINED_00D0	0x00D0
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_LA	0x00D1
#define T_MAC_GURMUKHI_UNDEFINED_00D2	0x00D2
#define T_MAC_GURMUKHI_UNDEFINED_00D3	0x00D3
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_VA	0x00D4
#define T_MAC_GURMUKHI_UNDEFINED_00D5	0x00D5
#define T_MAC_GURMUKHI_UNDEFINED_00D6	0x00D6
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_SA	0x00D7
#define T_MAC_GURMUKHI_GURMUKHI_LETTER_HA	0x00D8
#define T_MAC_GURMUKHI_LEFT_TO_RIGHT_MARK	0x00D9
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_AA	0x00DA
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_I	0x00DB
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_II	0x00DC
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_U	0x00DD
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_UU	0x00DE
#define T_MAC_GURMUKHI_UNDEFINED_00DF	0x00DF
#define T_MAC_GURMUKHI_UNDEFINED_00E0	0x00E0
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_EE	0x00E1
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_AI	0x00E2
#define T_MAC_GURMUKHI_UNDEFINED_00E3	0x00E3
#define T_MAC_GURMUKHI_UNDEFINED_00E4	0x00E4
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_OO	0x00E5
#define T_MAC_GURMUKHI_GURMUKHI_VOWEL_SIGN_AU	0x00E6
#define T_MAC_GURMUKHI_UNDEFINED_00E7	0x00E7
#define T_MAC_GURMUKHI_GURMUKHI_SIGN_VIRAMA	0x00E8
#define T_MAC_GURMUKHI_GURMUKHI_SIGN_NUKTA	0x00E9
#define T_MAC_GURMUKHI_DEVANAGARI_DANDA	0x00EA
#define T_MAC_GURMUKHI_UNDEFINED_00EB	0x00EB
#define T_MAC_GURMUKHI_UNDEFINED_00EC	0x00EC
#define T_MAC_GURMUKHI_UNDEFINED_00ED	0x00ED
#define T_MAC_GURMUKHI_UNDEFINED_00EE	0x00EE
#define T_MAC_GURMUKHI_UNDEFINED_00EF	0x00EF
#define T_MAC_GURMUKHI_UNDEFINED_00F0	0x00F0
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_ZERO	0x00F1
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_ONE	0x00F2
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_TWO	0x00F3
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_THREE	0x00F4
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_FOUR	0x00F5
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_FIVE	0x00F6
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_SIX	0x00F7
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_SEVEN	0x00F8
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_EIGHT	0x00F9
#define T_MAC_GURMUKHI_GURMUKHI_DIGIT_NINE	0x00FA
#define T_MAC_GURMUKHI_UNDEFINED_00FB	0x00FB
#define T_MAC_GURMUKHI_UNDEFINED_00FC	0x00FC
#define T_MAC_GURMUKHI_UNDEFINED_00FD	0x00FD
#define T_MAC_GURMUKHI_UNDEFINED_00FE	0x00FE
#define T_MAC_GURMUKHI_UNDEFINED_00FF	0x00FF

/* list of all characters */
#define T_LIST_MAC_GURMUKHI(EL) \
    EL(_CTRL_NULL) \
    EL(_CTRL_START_OF_HEADING) \
    EL(_CTRL_START_OF_TEXT) \
    EL(_CTRL_END_OF_TEXT) \
    EL(_CTRL_END_OF_TRANSMISSION) \
    EL(_CTRL_ENQUIRY) \
    EL(_CTRL_ACKNOWLEDGE) \
    EL(_CTRL_BELL) \
    EL(_CTRL_BACKSPACE) \
    EL(_CTRL_CHARACTER_TABULATION) \
    EL(_CTRL_LINE_FEED) \
    EL(_CTRL_LINE_TABULATION) \
    EL(_CTRL_FORM_FEED) \
    EL(_CTRL_CARRIAGE_RETURN) \
    EL(_CTRL_SHIFT_OUT) \
    EL(_CTRL_SHIFT_IN) \
    EL(_CTRL_DATA_LINK_ESCAPE) \
    EL(_CTRL_DEVICE_CONTROL_ONE) \
    EL(_CTRL_DEVICE_CONTROL_TWO) \
    EL(_CTRL_DEVICE_CONTROL_THREE) \
    EL(_CTRL_DEVICE_CONTROL_FOUR) \
    EL(_CTRL_NEGATIVE_ACKNOWLEDGE) \
    EL(_CTRL_SYNCHRONOUS_IDLE) \
    EL(_CTRL_END_OF_TRANSMISSION_BLOCK) \
    EL(_CTRL_CANCEL) \
    EL(_CTRL_END_OF_MEDIUM) \
    EL(_CTRL_SUBSTITUTE) \
    EL(_CTRL_ESCAPE) \
    EL(_CTRL_INFORMATION_SEPARATOR_FOUR) \
    EL(_CTRL_INFORMATION_SEPARATOR_THREE) \
    EL(_CTRL_INFORMATION_SEPARATOR_TWO) \
    EL(_CTRL_INFORMATION_SEPARATOR_ONE) \
    EL(_SPACE) \
    EL(_EXCLAMATION_MARK) \
    EL(_QUOTATION_MARK) \
    EL(_NUMBER_SIGN) \
    EL(_DOLLAR_SIGN) \
    EL(_PERCENT_SIGN) \
    EL(_AMPERSAND) \
    EL(_APOSTROPHE) \
    EL(_LEFT_PARENTHESIS) \
    EL(_RIGHT_PARENTHESIS) \
    EL(_ASTERISK) \
    EL(_PLUS_SIGN) \
    EL(_COMMA) \
    EL(_HYPHEN_MINUS) \
    EL(_FULL_STOP) \
    EL(_SOLIDUS) \
    EL(_DIGIT_ZERO) \
    EL(_DIGIT_ONE) \
    EL(_DIGIT_TWO) \
    EL(_DIGIT_THREE) \
    EL(_DIGIT_FOUR) \
    EL(_DIGIT_FIVE) \
    EL(_DIGIT_SIX) \
    EL(_DIGIT_SEVEN) \
    EL(_DIGIT_EIGHT) \
    EL(_DIGIT_NINE) \
    EL(_COLON) \
    EL(_SEMICOLON) \
    EL(_LESS_THAN_SIGN) \
    EL(_EQUALS_SIGN) \
    EL(_GREATER_THAN_SIGN) \
    EL(_QUESTION_MARK) \
    EL(_COMMERCIAL_AT) \
    EL(_LATIN_CAPITAL_LETTER_A) \
    EL(_LATIN_CAPITAL_LETTER_B) \
    EL(_LATIN_CAPITAL_LETTER_C) \
    EL(_LATIN_CAPITAL_LETTER_D) \
    EL(_LATIN_CAPITAL_LETTER_E) \
    EL(_LATIN_CAPITAL_LETTER_F) \
    EL(_LATIN_CAPITAL_LETTER_G) \
    EL(_LATIN_CAPITAL_LETTER_H) \
    EL(_LATIN_CAPITAL_LETTER_I) \
    EL(_LATIN_CAPITAL_LETTER_J) \
    EL(_LATIN_CAPITAL_LETTER_K) \
    EL(_LATIN_CAPITAL_LETTER_L) \
    EL(_LATIN_CAPITAL_LETTER_M) \
    EL(_LATIN_CAPITAL_LETTER_N) \
    EL(_LATIN_CAPITAL_LETTER_O) \
    EL(_LATIN_CAPITAL_LETTER_P) \
    EL(_LATIN_CAPITAL_LETTER_Q) \
    EL(_LATIN_CAPITAL_LETTER_R) \
    EL(_LATIN_CAPITAL_LETTER_S) \
    EL(_LATIN_CAPITAL_LETTER_T) \
    EL(_LATIN_CAPITAL_LETTER_U) \
    EL(_LATIN_CAPITAL_LETTER_V) \
    EL(_LATIN_CAPITAL_LETTER_W) \
    EL(_LATIN_CAPITAL_LETTER_X) \
    EL(_LATIN_CAPITAL_LETTER_Y) \
    EL(_LATIN_CAPITAL_LETTER_Z) \
    EL(_LEFT_SQUARE_BRACKET) \
    EL(_REVERSE_SOLIDUS) \
    EL(_RIGHT_SQUARE_BRACKET) \
    EL(_CIRCUMFLEX_ACCENT) \
    EL(_LOW_LINE) \
    EL(_GRAVE_ACCENT) \
    EL(_LATIN_SMALL_LETTER_A) \
    EL(_LATIN_SMALL_LETTER_B) \
    EL(_LATIN_SMALL_LETTER_C) \
    EL(_LATIN_SMALL_LETTER_D) \
    EL(_LATIN_SMALL_LETTER_E) \
    EL(_LATIN_SMALL_LETTER_F) \
    EL(_LATIN_SMALL_LETTER_G) \
    EL(_LATIN_SMALL_LETTER_H) \
    EL(_LATIN_SMALL_LETTER_I) \
    EL(_LATIN_SMALL_LETTER_J) \
    EL(_LATIN_SMALL_LETTER_K) \
    EL(_LATIN_SMALL_LETTER_L) \
    EL(_LATIN_SMALL_LETTER_M) \
    EL(_LATIN_SMALL_LETTER_N) \
    EL(_LATIN_SMALL_LETTER_O) \
    EL(_LATIN_SMALL_LETTER_P) \
    EL(_LATIN_SMALL_LETTER_Q) \
    EL(_LATIN_SMALL_LETTER_R) \
    EL(_LATIN_SMALL_LETTER_S) \
    EL(_LATIN_SMALL_LETTER_T) \
    EL(_LATIN_SMALL_LETTER_U) \
    EL(_LATIN_SMALL_LETTER_V) \
    EL(_LATIN_SMALL_LETTER_W) \
    EL(_LATIN_SMALL_LETTER_X) \
    EL(_LATIN_SMALL_LETTER_Y) \
    EL(_LATIN_SMALL_LETTER_Z) \
    EL(_LEFT_CURLY_BRACKET) \
    EL(_VERTICAL_LINE) \
    EL(_RIGHT_CURLY_BRACKET) \
    EL(_TILDE) \
    EL(_CTRL_DELETE) \
    EL(_MULTIPLICATION_SIGN) \
    EL(_MINUS_SIGN) \
    EL(_EN_DASH) \
    EL(_EM_DASH) \
    EL(_LEFT_SINGLE_QUOTATION_MARK) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_BULLET) \
    EL(_COPYRIGHT_SIGN) \
    EL(_REGISTERED_SIGN) \
    EL(_TRADE_MARK_SIGN) \
    EL(_GURMUKHI_ADDAK) \
    EL(_GURMUKHI_LETTER_RRA) \
    EL(_GURMUKHI_URA) \
    EL(_GURMUKHI_IRI) \
    EL(_GURMUKHI_EK_ONKAR) \
    EL(_GURMUKHI_SIGN_BINDI) \
    EL(_GURMUKHI_LETTER_A) \
    EL(_GURMUKHI_LETTER_AA) \
    EL(_GURMUKHI_LETTER_I) \
    EL(_GURMUKHI_LETTER_II) \
    EL(_GURMUKHI_LETTER_U) \
    EL(_GURMUKHI_LETTER_UU) \
    EL(_GURMUKHI_LETTER_EE) \
    EL(_GURMUKHI_LETTER_AI) \
    EL(_GURMUKHI_LETTER_OO) \
    EL(_GURMUKHI_LETTER_AU) \
    EL(_GURMUKHI_LETTER_KA) \
    EL(_GURMUKHI_LETTER_KHA) \
    EL(_GURMUKHI_LETTER_GA) \
    EL(_GURMUKHI_LETTER_GHA) \
    EL(_GURMUKHI_LETTER_NGA) \
    EL(_GURMUKHI_LETTER_CA) \
    EL(_GURMUKHI_LETTER_CHA) \
    EL(_GURMUKHI_LETTER_JA) \
    EL(_GURMUKHI_LETTER_JHA) \
    EL(_GURMUKHI_LETTER_NYA) \
    EL(_GURMUKHI_LETTER_TTA) \
    EL(_GURMUKHI_LETTER_TTHA) \
    EL(_GURMUKHI_LETTER_DDA) \
    EL(_GURMUKHI_LETTER_DDHA) \
    EL(_GURMUKHI_LETTER_NNA) \
    EL(_GURMUKHI_LETTER_TA) \
    EL(_GURMUKHI_LETTER_THA) \
    EL(_GURMUKHI_LETTER_DA) \
    EL(_GURMUKHI_LETTER_DHA) \
    EL(_GURMUKHI_LETTER_NA) \
    EL(_GURMUKHI_LETTER_PA) \
    EL(_GURMUKHI_LETTER_PHA) \
    EL(_GURMUKHI_LETTER_BA) \
    EL(_GURMUKHI_LETTER_BHA) \
    EL(_GURMUKHI_LETTER_MA) \
    EL(_GURMUKHI_LETTER_YA) \
    EL(_GURMUKHI_LETTER_RA) \
    EL(_GURMUKHI_LETTER_LA) \
    EL(_GURMUKHI_LETTER_VA) \
    EL(_GURMUKHI_LETTER_SA) \
    EL(_GURMUKHI_LETTER_HA) \
    EL(_LEFT_TO_RIGHT_MARK) \
    EL(_GURMUKHI_VOWEL_SIGN_AA) \
    EL(_GURMUKHI_VOWEL_SIGN_I) \
    EL(_GURMUKHI_VOWEL_SIGN_II) \
    EL(_GURMUKHI_VOWEL_SIGN_U) \
    EL(_GURMUKHI_VOWEL_SIGN_UU) \
    EL(_GURMUKHI_VOWEL_SIGN_EE) \
    EL(_GURMUKHI_VOWEL_SIGN_AI) \
    EL(_GURMUKHI_VOWEL_SIGN_OO) \
    EL(_GURMUKHI_VOWEL_SIGN_AU) \
    EL(_GURMUKHI_SIGN_VIRAMA) \
    EL(_GURMUKHI_SIGN_NUKTA) \
    EL(_DEVANAGARI_DANDA) \
    EL(_GURMUKHI_DIGIT_ZERO) \
    EL(_GURMUKHI_DIGIT_ONE) \
    EL(_GURMUKHI_DIGIT_TWO) \
    EL(_GURMUKHI_DIGIT_THREE) \
    EL(_GURMUKHI_DIGIT_FOUR) \
    EL(_GURMUKHI_DIGIT_FIVE) \
    EL(_GURMUKHI_DIGIT_SIX) \
    EL(_GURMUKHI_DIGIT_SEVEN) \
    EL(_GURMUKHI_DIGIT_EIGHT) \
    EL(_GURMUKHI_DIGIT_NINE)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_MAC_GURMUKHI(EL) \
    EL(_MULTIPLICATION_SIGN) \
    EL(_MINUS_SIGN) \
    EL(_EN_DASH) \
    EL(_EM_DASH) \
    EL(_LEFT_SINGLE_QUOTATION_MARK) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_BULLET) \
    EL(_COPYRIGHT_SIGN) \
    EL(_REGISTERED_SIGN) \
    EL(_TRADE_MARK_SIGN) \
    EL(_GURMUKHI_ADDAK) \
    EL(_GURMUKHI_LETTER_RRA) \
    EL(_GURMUKHI_URA) \
    EL(_GURMUKHI_IRI) \
    EL(_GURMUKHI_EK_ONKAR) \
    EL(_GURMUKHI_SIGN_BINDI) \
    EL(_GURMUKHI_LETTER_A) \
    EL(_GURMUKHI_LETTER_AA) \
    EL(_GURMUKHI_LETTER_I) \
    EL(_GURMUKHI_LETTER_II) \
    EL(_GURMUKHI_LETTER_U) \
    EL(_GURMUKHI_LETTER_UU) \
    EL(_GURMUKHI_LETTER_EE) \
    EL(_GURMUKHI_LETTER_AI) \
    EL(_GURMUKHI_LETTER_OO) \
    EL(_GURMUKHI_LETTER_AU) \
    EL(_GURMUKHI_LETTER_KA) \
    EL(_GURMUKHI_LETTER_KHA) \
    EL(_GURMUKHI_LETTER_GA) \
    EL(_GURMUKHI_LETTER_GHA) \
    EL(_GURMUKHI_LETTER_NGA) \
    EL(_GURMUKHI_LETTER_CA) \
    EL(_GURMUKHI_LETTER_CHA) \
    EL(_GURMUKHI_LETTER_JA) \
    EL(_GURMUKHI_LETTER_JHA) \
    EL(_GURMUKHI_LETTER_NYA) \
    EL(_GURMUKHI_LETTER_TTA) \
    EL(_GURMUKHI_LETTER_TTHA) \
    EL(_GURMUKHI_LETTER_DDA) \
    EL(_GURMUKHI_LETTER_DDHA) \
    EL(_GURMUKHI_LETTER_NNA) \
    EL(_GURMUKHI_LETTER_TA) \
    EL(_GURMUKHI_LETTER_THA) \
    EL(_GURMUKHI_LETTER_DA) \
    EL(_GURMUKHI_LETTER_DHA) \
    EL(_GURMUKHI_LETTER_NA) \
    EL(_GURMUKHI_LETTER_PA) \
    EL(_GURMUKHI_LETTER_PHA) \
    EL(_GURMUKHI_LETTER_BA) \
    EL(_GURMUKHI_LETTER_BHA) \
    EL(_GURMUKHI_LETTER_MA) \
    EL(_GURMUKHI_LETTER_YA) \
    EL(_GURMUKHI_LETTER_RA) \
    EL(_GURMUKHI_LETTER_LA) \
    EL(_GURMUKHI_LETTER_VA) \
    EL(_GURMUKHI_LETTER_SA) \
    EL(_GURMUKHI_LETTER_HA) \
    EL(_LEFT_TO_RIGHT_MARK) \
    EL(_GURMUKHI_VOWEL_SIGN_AA) \
    EL(_GURMUKHI_VOWEL_SIGN_I) \
    EL(_GURMUKHI_VOWEL_SIGN_II) \
    EL(_GURMUKHI_VOWEL_SIGN_U) \
    EL(_GURMUKHI_VOWEL_SIGN_UU) \
    EL(_GURMUKHI_VOWEL_SIGN_EE) \
    EL(_GURMUKHI_VOWEL_SIGN_AI) \
    EL(_GURMUKHI_VOWEL_SIGN_OO) \
    EL(_GURMUKHI_VOWEL_SIGN_AU) \
    EL(_GURMUKHI_SIGN_VIRAMA) \
    EL(_GURMUKHI_SIGN_NUKTA) \
    EL(_DEVANAGARI_DANDA) \
    EL(_GURMUKHI_DIGIT_ZERO) \
    EL(_GURMUKHI_DIGIT_ONE) \
    EL(_GURMUKHI_DIGIT_TWO) \
    EL(_GURMUKHI_DIGIT_THREE) \
    EL(_GURMUKHI_DIGIT_FOUR) \
    EL(_GURMUKHI_DIGIT_FIVE) \
    EL(_GURMUKHI_DIGIT_SIX) \
    EL(_GURMUKHI_DIGIT_SEVEN) \
    EL(_GURMUKHI_DIGIT_EIGHT) \
    EL(_GURMUKHI_DIGIT_NINE)


#endif /* _TUTF_MAC_GURMUKHI_H */
