
/*
 * This file was automatically generated from unicode
 * charset definition files http://unicode.org/Public/MAPPINGS/
 * using the script twin/scripts/helper-from-unicode.org.bash
 *
 * PLEASE DO NOT EDIT!
 */


#ifndef _TUTF_MAC_DINGBATS_H
#define _TUTF_MAC_DINGBATS_H

#define T_MAC_DINGBATS_CTRL_NULL	0x0000
#define T_MAC_DINGBATS_CTRL_START_OF_HEADING	0x0001
#define T_MAC_DINGBATS_CTRL_START_OF_TEXT	0x0002
#define T_MAC_DINGBATS_CTRL_END_OF_TEXT	0x0003
#define T_MAC_DINGBATS_CTRL_END_OF_TRANSMISSION	0x0004
#define T_MAC_DINGBATS_CTRL_ENQUIRY	0x0005
#define T_MAC_DINGBATS_CTRL_ACKNOWLEDGE	0x0006
#define T_MAC_DINGBATS_CTRL_BELL	0x0007
#define T_MAC_DINGBATS_CTRL_BACKSPACE	0x0008
#define T_MAC_DINGBATS_CTRL_CHARACTER_TABULATION	0x0009
#define T_MAC_DINGBATS_CTRL_LINE_FEED	0x000A
#define T_MAC_DINGBATS_CTRL_LINE_TABULATION	0x000B
#define T_MAC_DINGBATS_CTRL_FORM_FEED	0x000C
#define T_MAC_DINGBATS_CTRL_CARRIAGE_RETURN	0x000D
#define T_MAC_DINGBATS_CTRL_SHIFT_OUT	0x000E
#define T_MAC_DINGBATS_CTRL_SHIFT_IN	0x000F
#define T_MAC_DINGBATS_CTRL_DATA_LINK_ESCAPE	0x0010
#define T_MAC_DINGBATS_CTRL_DEVICE_CONTROL_ONE	0x0011
#define T_MAC_DINGBATS_CTRL_DEVICE_CONTROL_TWO	0x0012
#define T_MAC_DINGBATS_CTRL_DEVICE_CONTROL_THREE	0x0013
#define T_MAC_DINGBATS_CTRL_DEVICE_CONTROL_FOUR	0x0014
#define T_MAC_DINGBATS_CTRL_NEGATIVE_ACKNOWLEDGE	0x0015
#define T_MAC_DINGBATS_CTRL_SYNCHRONOUS_IDLE	0x0016
#define T_MAC_DINGBATS_CTRL_END_OF_TRANSMISSION_BLOCK	0x0017
#define T_MAC_DINGBATS_CTRL_CANCEL	0x0018
#define T_MAC_DINGBATS_CTRL_END_OF_MEDIUM	0x0019
#define T_MAC_DINGBATS_CTRL_SUBSTITUTE	0x001A
#define T_MAC_DINGBATS_CTRL_ESCAPE	0x001B
#define T_MAC_DINGBATS_CTRL_INFORMATION_SEPARATOR_FOUR	0x001C
#define T_MAC_DINGBATS_CTRL_INFORMATION_SEPARATOR_THREE	0x001D
#define T_MAC_DINGBATS_CTRL_INFORMATION_SEPARATOR_TWO	0x001E
#define T_MAC_DINGBATS_CTRL_INFORMATION_SEPARATOR_ONE	0x001F
#define T_MAC_DINGBATS_SPACE	0x0020
#define T_MAC_DINGBATS_EXCLAMATION_MARK	0x0021
#define T_MAC_DINGBATS_QUOTATION_MARK	0x0022
#define T_MAC_DINGBATS_NUMBER_SIGN	0x0023
#define T_MAC_DINGBATS_DOLLAR_SIGN	0x0024
#define T_MAC_DINGBATS_PERCENT_SIGN	0x0025
#define T_MAC_DINGBATS_AMPERSAND	0x0026
#define T_MAC_DINGBATS_APOSTROPHE	0x0027
#define T_MAC_DINGBATS_LEFT_PARENTHESIS	0x0028
#define T_MAC_DINGBATS_RIGHT_PARENTHESIS	0x0029
#define T_MAC_DINGBATS_ASTERISK	0x002A
#define T_MAC_DINGBATS_PLUS_SIGN	0x002B
#define T_MAC_DINGBATS_COMMA	0x002C
#define T_MAC_DINGBATS_HYPHEN_MINUS	0x002D
#define T_MAC_DINGBATS_FULL_STOP	0x002E
#define T_MAC_DINGBATS_SOLIDUS	0x002F
#define T_MAC_DINGBATS_DIGIT_ZERO	0x0030
#define T_MAC_DINGBATS_DIGIT_ONE	0x0031
#define T_MAC_DINGBATS_DIGIT_TWO	0x0032
#define T_MAC_DINGBATS_DIGIT_THREE	0x0033
#define T_MAC_DINGBATS_DIGIT_FOUR	0x0034
#define T_MAC_DINGBATS_DIGIT_FIVE	0x0035
#define T_MAC_DINGBATS_DIGIT_SIX	0x0036
#define T_MAC_DINGBATS_DIGIT_SEVEN	0x0037
#define T_MAC_DINGBATS_DIGIT_EIGHT	0x0038
#define T_MAC_DINGBATS_DIGIT_NINE	0x0039
#define T_MAC_DINGBATS_COLON	0x003A
#define T_MAC_DINGBATS_SEMICOLON	0x003B
#define T_MAC_DINGBATS_LESS_THAN_SIGN	0x003C
#define T_MAC_DINGBATS_EQUALS_SIGN	0x003D
#define T_MAC_DINGBATS_GREATER_THAN_SIGN	0x003E
#define T_MAC_DINGBATS_QUESTION_MARK	0x003F
#define T_MAC_DINGBATS_COMMERCIAL_AT	0x0040
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_A	0x0041
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_B	0x0042
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_C	0x0043
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_D	0x0044
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_E	0x0045
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_F	0x0046
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_G	0x0047
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_H	0x0048
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_I	0x0049
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_J	0x004A
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_K	0x004B
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_L	0x004C
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_M	0x004D
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_N	0x004E
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_O	0x004F
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_P	0x0050
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_Q	0x0051
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_R	0x0052
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_S	0x0053
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_T	0x0054
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_U	0x0055
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_V	0x0056
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_W	0x0057
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_X	0x0058
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_Y	0x0059
#define T_MAC_DINGBATS_LATIN_CAPITAL_LETTER_Z	0x005A
#define T_MAC_DINGBATS_LEFT_SQUARE_BRACKET	0x005B
#define T_MAC_DINGBATS_REVERSE_SOLIDUS	0x005C
#define T_MAC_DINGBATS_RIGHT_SQUARE_BRACKET	0x005D
#define T_MAC_DINGBATS_CIRCUMFLEX_ACCENT	0x005E
#define T_MAC_DINGBATS_LOW_LINE	0x005F
#define T_MAC_DINGBATS_GRAVE_ACCENT	0x0060
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_A	0x0061
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_B	0x0062
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_C	0x0063
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_D	0x0064
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_E	0x0065
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_F	0x0066
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_G	0x0067
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_H	0x0068
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_I	0x0069
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_J	0x006A
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_K	0x006B
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_L	0x006C
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_M	0x006D
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_N	0x006E
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_O	0x006F
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_P	0x0070
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_Q	0x0071
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_R	0x0072
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_S	0x0073
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_T	0x0074
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_U	0x0075
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_V	0x0076
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_W	0x0077
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_X	0x0078
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_Y	0x0079
#define T_MAC_DINGBATS_LATIN_SMALL_LETTER_Z	0x007A
#define T_MAC_DINGBATS_LEFT_CURLY_BRACKET	0x007B
#define T_MAC_DINGBATS_VERTICAL_LINE	0x007C
#define T_MAC_DINGBATS_RIGHT_CURLY_BRACKET	0x007D
#define T_MAC_DINGBATS_TILDE	0x007E
#define T_MAC_DINGBATS_CTRL_DELETE	0x007F
#define T_MAC_DINGBATS_MEDIUM_LEFT_PARENTHESIS_ORNAMENT	0x0080
#define T_MAC_DINGBATS_MEDIUM_RIGHT_PARENTHESIS_ORNAMENT	0x0081
#define T_MAC_DINGBATS_MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT	0x0082
#define T_MAC_DINGBATS_MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT	0x0083
#define T_MAC_DINGBATS_MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0084
#define T_MAC_DINGBATS_MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0085
#define T_MAC_DINGBATS_HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT	0x0086
#define T_MAC_DINGBATS_HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT	0x0087
#define T_MAC_DINGBATS_HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0088
#define T_MAC_DINGBATS_HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT	0x0089
#define T_MAC_DINGBATS_LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT	0x008A
#define T_MAC_DINGBATS_LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT	0x008B
#define T_MAC_DINGBATS_MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT	0x008C
#define T_MAC_DINGBATS_MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT	0x008D
#define T_MAC_DINGBATS_UNDEFINED_008E	0x008E
#define T_MAC_DINGBATS_UNDEFINED_008F	0x008F
#define T_MAC_DINGBATS_UNDEFINED_0090	0x0090
#define T_MAC_DINGBATS_UNDEFINED_0091	0x0091
#define T_MAC_DINGBATS_UNDEFINED_0092	0x0092
#define T_MAC_DINGBATS_UNDEFINED_0093	0x0093
#define T_MAC_DINGBATS_UNDEFINED_0094	0x0094
#define T_MAC_DINGBATS_UNDEFINED_0095	0x0095
#define T_MAC_DINGBATS_UNDEFINED_0096	0x0096
#define T_MAC_DINGBATS_UNDEFINED_0097	0x0097
#define T_MAC_DINGBATS_UNDEFINED_0098	0x0098
#define T_MAC_DINGBATS_UNDEFINED_0099	0x0099
#define T_MAC_DINGBATS_UNDEFINED_009A	0x009A
#define T_MAC_DINGBATS_UNDEFINED_009B	0x009B
#define T_MAC_DINGBATS_UNDEFINED_009C	0x009C
#define T_MAC_DINGBATS_UNDEFINED_009D	0x009D
#define T_MAC_DINGBATS_UNDEFINED_009E	0x009E
#define T_MAC_DINGBATS_UNDEFINED_009F	0x009F
#define T_MAC_DINGBATS_UNDEFINED_00A0	0x00A0
#define T_MAC_DINGBATS_CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT	0x00A1
#define T_MAC_DINGBATS_HEAVY_EXCLAMATION_MARK_ORNAMENT	0x00A2
#define T_MAC_DINGBATS_HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT	0x00A3
#define T_MAC_DINGBATS_HEAVY_BLACK_HEART	0x00A4
#define T_MAC_DINGBATS_ROTATED_HEAVY_BLACK_HEART_BULLET	0x00A5
#define T_MAC_DINGBATS_FLORAL_HEART	0x00A6
#define T_MAC_DINGBATS_ROTATED_FLORAL_HEART_BULLET	0x00A7
#define T_MAC_DINGBATS_BLACK_CLUB_SUIT	0x00A8
#define T_MAC_DINGBATS_BLACK_DIAMOND_SUIT	0x00A9
#define T_MAC_DINGBATS_BLACK_HEART_SUIT	0x00AA
#define T_MAC_DINGBATS_BLACK_SPADE_SUIT	0x00AB
#define T_MAC_DINGBATS_CIRCLED_DIGIT_ONE	0x00AC
#define T_MAC_DINGBATS_CIRCLED_DIGIT_TWO	0x00AD
#define T_MAC_DINGBATS_CIRCLED_DIGIT_THREE	0x00AE
#define T_MAC_DINGBATS_CIRCLED_DIGIT_FOUR	0x00AF
#define T_MAC_DINGBATS_CIRCLED_DIGIT_FIVE	0x00B0
#define T_MAC_DINGBATS_CIRCLED_DIGIT_SIX	0x00B1
#define T_MAC_DINGBATS_CIRCLED_DIGIT_SEVEN	0x00B2
#define T_MAC_DINGBATS_CIRCLED_DIGIT_EIGHT	0x00B3
#define T_MAC_DINGBATS_CIRCLED_DIGIT_NINE	0x00B4
#define T_MAC_DINGBATS_CIRCLED_NUMBER_TEN	0x00B5
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE	0x00B6
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO	0x00B7
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE	0x00B8
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR	0x00B9
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE	0x00BA
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX	0x00BB
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN	0x00BC
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT	0x00BD
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE	0x00BE
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN	0x00BF
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE	0x00C0
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO	0x00C1
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE	0x00C2
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR	0x00C3
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE	0x00C4
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX	0x00C5
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN	0x00C6
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT	0x00C7
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE	0x00C8
#define T_MAC_DINGBATS_DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN	0x00C9
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE	0x00CA
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO	0x00CB
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE	0x00CC
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR	0x00CD
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE	0x00CE
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX	0x00CF
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN	0x00D0
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT	0x00D1
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE	0x00D2
#define T_MAC_DINGBATS_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN	0x00D3
#define T_MAC_DINGBATS_HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW	0x00D4
#define T_MAC_DINGBATS_RIGHTWARDS_ARROW	0x00D5
#define T_MAC_DINGBATS_LEFT_RIGHT_ARROW	0x00D6
#define T_MAC_DINGBATS_UP_DOWN_ARROW	0x00D7
#define T_MAC_DINGBATS_HEAVY_SOUTH_EAST_ARROW	0x00D8
#define T_MAC_DINGBATS_HEAVY_RIGHTWARDS_ARROW	0x00D9
#define T_MAC_DINGBATS_HEAVY_NORTH_EAST_ARROW	0x00DA
#define T_MAC_DINGBATS_DRAFTING_POINT_RIGHTWARDS_ARROW	0x00DB
#define T_MAC_DINGBATS_HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW	0x00DC
#define T_MAC_DINGBATS_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00DD
#define T_MAC_DINGBATS_HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00DE
#define T_MAC_DINGBATS_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00DF
#define T_MAC_DINGBATS_HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW	0x00E0
#define T_MAC_DINGBATS_BLACK_RIGHTWARDS_ARROW	0x00E1
#define T_MAC_DINGBATS_THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD	0x00E2
#define T_MAC_DINGBATS_THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD	0x00E3
#define T_MAC_DINGBATS_BLACK_RIGHTWARDS_ARROWHEAD	0x00E4
#define T_MAC_DINGBATS_HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW	0x00E5
#define T_MAC_DINGBATS_HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW	0x00E6
#define T_MAC_DINGBATS_SQUAT_BLACK_RIGHTWARDS_ARROW	0x00E7
#define T_MAC_DINGBATS_HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW	0x00E8
#define T_MAC_DINGBATS_RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW	0x00E9
#define T_MAC_DINGBATS_LEFT_SHADED_WHITE_RIGHTWARDS_ARROW	0x00EA
#define T_MAC_DINGBATS_BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EB
#define T_MAC_DINGBATS_FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EC
#define T_MAC_DINGBATS_HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00ED
#define T_MAC_DINGBATS_HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EE
#define T_MAC_DINGBATS_NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00EF
#define T_MAC_DINGBATS_UNDEFINED_00F0	0x00F0
#define T_MAC_DINGBATS_NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW	0x00F1
#define T_MAC_DINGBATS_CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW	0x00F2
#define T_MAC_DINGBATS_WHITE_FEATHERED_RIGHTWARDS_ARROW	0x00F3
#define T_MAC_DINGBATS_BLACK_FEATHERED_SOUTH_EAST_ARROW	0x00F4
#define T_MAC_DINGBATS_BLACK_FEATHERED_RIGHTWARDS_ARROW	0x00F5
#define T_MAC_DINGBATS_BLACK_FEATHERED_NORTH_EAST_ARROW	0x00F6
#define T_MAC_DINGBATS_HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW	0x00F7
#define T_MAC_DINGBATS_HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW	0x00F8
#define T_MAC_DINGBATS_HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW	0x00F9
#define T_MAC_DINGBATS_TEARDROP_BARBED_RIGHTWARDS_ARROW	0x00FA
#define T_MAC_DINGBATS_HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW	0x00FB
#define T_MAC_DINGBATS_WEDGE_TAILED_RIGHTWARDS_ARROW	0x00FC
#define T_MAC_DINGBATS_HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW	0x00FD
#define T_MAC_DINGBATS_OPEN_OUTLINED_RIGHTWARDS_ARROW	0x00FE
#define T_MAC_DINGBATS_UNDEFINED_00FF	0x00FF

/* list of all characters */
#define T_LIST_MAC_DINGBATS(EL) \
    EL(_CTRL_NULL) \
    EL(_CTRL_START_OF_HEADING) \
    EL(_CTRL_START_OF_TEXT) \
    EL(_CTRL_END_OF_TEXT) \
    EL(_CTRL_END_OF_TRANSMISSION) \
    EL(_CTRL_ENQUIRY) \
    EL(_CTRL_ACKNOWLEDGE) \
    EL(_CTRL_BELL) \
    EL(_CTRL_BACKSPACE) \
    EL(_CTRL_CHARACTER_TABULATION) \
    EL(_CTRL_LINE_FEED) \
    EL(_CTRL_LINE_TABULATION) \
    EL(_CTRL_FORM_FEED) \
    EL(_CTRL_CARRIAGE_RETURN) \
    EL(_CTRL_SHIFT_OUT) \
    EL(_CTRL_SHIFT_IN) \
    EL(_CTRL_DATA_LINK_ESCAPE) \
    EL(_CTRL_DEVICE_CONTROL_ONE) \
    EL(_CTRL_DEVICE_CONTROL_TWO) \
    EL(_CTRL_DEVICE_CONTROL_THREE) \
    EL(_CTRL_DEVICE_CONTROL_FOUR) \
    EL(_CTRL_NEGATIVE_ACKNOWLEDGE) \
    EL(_CTRL_SYNCHRONOUS_IDLE) \
    EL(_CTRL_END_OF_TRANSMISSION_BLOCK) \
    EL(_CTRL_CANCEL) \
    EL(_CTRL_END_OF_MEDIUM) \
    EL(_CTRL_SUBSTITUTE) \
    EL(_CTRL_ESCAPE) \
    EL(_CTRL_INFORMATION_SEPARATOR_FOUR) \
    EL(_CTRL_INFORMATION_SEPARATOR_THREE) \
    EL(_CTRL_INFORMATION_SEPARATOR_TWO) \
    EL(_CTRL_INFORMATION_SEPARATOR_ONE) \
    EL(_SPACE) \
    EL(_EXCLAMATION_MARK) \
    EL(_QUOTATION_MARK) \
    EL(_NUMBER_SIGN) \
    EL(_DOLLAR_SIGN) \
    EL(_PERCENT_SIGN) \
    EL(_AMPERSAND) \
    EL(_APOSTROPHE) \
    EL(_LEFT_PARENTHESIS) \
    EL(_RIGHT_PARENTHESIS) \
    EL(_ASTERISK) \
    EL(_PLUS_SIGN) \
    EL(_COMMA) \
    EL(_HYPHEN_MINUS) \
    EL(_FULL_STOP) \
    EL(_SOLIDUS) \
    EL(_DIGIT_ZERO) \
    EL(_DIGIT_ONE) \
    EL(_DIGIT_TWO) \
    EL(_DIGIT_THREE) \
    EL(_DIGIT_FOUR) \
    EL(_DIGIT_FIVE) \
    EL(_DIGIT_SIX) \
    EL(_DIGIT_SEVEN) \
    EL(_DIGIT_EIGHT) \
    EL(_DIGIT_NINE) \
    EL(_COLON) \
    EL(_SEMICOLON) \
    EL(_LESS_THAN_SIGN) \
    EL(_EQUALS_SIGN) \
    EL(_GREATER_THAN_SIGN) \
    EL(_QUESTION_MARK) \
    EL(_COMMERCIAL_AT) \
    EL(_LATIN_CAPITAL_LETTER_A) \
    EL(_LATIN_CAPITAL_LETTER_B) \
    EL(_LATIN_CAPITAL_LETTER_C) \
    EL(_LATIN_CAPITAL_LETTER_D) \
    EL(_LATIN_CAPITAL_LETTER_E) \
    EL(_LATIN_CAPITAL_LETTER_F) \
    EL(_LATIN_CAPITAL_LETTER_G) \
    EL(_LATIN_CAPITAL_LETTER_H) \
    EL(_LATIN_CAPITAL_LETTER_I) \
    EL(_LATIN_CAPITAL_LETTER_J) \
    EL(_LATIN_CAPITAL_LETTER_K) \
    EL(_LATIN_CAPITAL_LETTER_L) \
    EL(_LATIN_CAPITAL_LETTER_M) \
    EL(_LATIN_CAPITAL_LETTER_N) \
    EL(_LATIN_CAPITAL_LETTER_O) \
    EL(_LATIN_CAPITAL_LETTER_P) \
    EL(_LATIN_CAPITAL_LETTER_Q) \
    EL(_LATIN_CAPITAL_LETTER_R) \
    EL(_LATIN_CAPITAL_LETTER_S) \
    EL(_LATIN_CAPITAL_LETTER_T) \
    EL(_LATIN_CAPITAL_LETTER_U) \
    EL(_LATIN_CAPITAL_LETTER_V) \
    EL(_LATIN_CAPITAL_LETTER_W) \
    EL(_LATIN_CAPITAL_LETTER_X) \
    EL(_LATIN_CAPITAL_LETTER_Y) \
    EL(_LATIN_CAPITAL_LETTER_Z) \
    EL(_LEFT_SQUARE_BRACKET) \
    EL(_REVERSE_SOLIDUS) \
    EL(_RIGHT_SQUARE_BRACKET) \
    EL(_CIRCUMFLEX_ACCENT) \
    EL(_LOW_LINE) \
    EL(_GRAVE_ACCENT) \
    EL(_LATIN_SMALL_LETTER_A) \
    EL(_LATIN_SMALL_LETTER_B) \
    EL(_LATIN_SMALL_LETTER_C) \
    EL(_LATIN_SMALL_LETTER_D) \
    EL(_LATIN_SMALL_LETTER_E) \
    EL(_LATIN_SMALL_LETTER_F) \
    EL(_LATIN_SMALL_LETTER_G) \
    EL(_LATIN_SMALL_LETTER_H) \
    EL(_LATIN_SMALL_LETTER_I) \
    EL(_LATIN_SMALL_LETTER_J) \
    EL(_LATIN_SMALL_LETTER_K) \
    EL(_LATIN_SMALL_LETTER_L) \
    EL(_LATIN_SMALL_LETTER_M) \
    EL(_LATIN_SMALL_LETTER_N) \
    EL(_LATIN_SMALL_LETTER_O) \
    EL(_LATIN_SMALL_LETTER_P) \
    EL(_LATIN_SMALL_LETTER_Q) \
    EL(_LATIN_SMALL_LETTER_R) \
    EL(_LATIN_SMALL_LETTER_S) \
    EL(_LATIN_SMALL_LETTER_T) \
    EL(_LATIN_SMALL_LETTER_U) \
    EL(_LATIN_SMALL_LETTER_V) \
    EL(_LATIN_SMALL_LETTER_W) \
    EL(_LATIN_SMALL_LETTER_X) \
    EL(_LATIN_SMALL_LETTER_Y) \
    EL(_LATIN_SMALL_LETTER_Z) \
    EL(_LEFT_CURLY_BRACKET) \
    EL(_VERTICAL_LINE) \
    EL(_RIGHT_CURLY_BRACKET) \
    EL(_TILDE) \
    EL(_CTRL_DELETE) \
    EL(_MEDIUM_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT) \
    EL(_CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT) \
    EL(_HEAVY_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_BLACK_HEART) \
    EL(_ROTATED_HEAVY_BLACK_HEART_BULLET) \
    EL(_FLORAL_HEART) \
    EL(_ROTATED_FLORAL_HEART_BULLET) \
    EL(_BLACK_CLUB_SUIT) \
    EL(_BLACK_DIAMOND_SUIT) \
    EL(_BLACK_HEART_SUIT) \
    EL(_BLACK_SPADE_SUIT) \
    EL(_CIRCLED_DIGIT_ONE) \
    EL(_CIRCLED_DIGIT_TWO) \
    EL(_CIRCLED_DIGIT_THREE) \
    EL(_CIRCLED_DIGIT_FOUR) \
    EL(_CIRCLED_DIGIT_FIVE) \
    EL(_CIRCLED_DIGIT_SIX) \
    EL(_CIRCLED_DIGIT_SEVEN) \
    EL(_CIRCLED_DIGIT_EIGHT) \
    EL(_CIRCLED_DIGIT_NINE) \
    EL(_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW) \
    EL(_RIGHTWARDS_ARROW) \
    EL(_LEFT_RIGHT_ARROW) \
    EL(_UP_DOWN_ARROW) \
    EL(_HEAVY_SOUTH_EAST_ARROW) \
    EL(_HEAVY_RIGHTWARDS_ARROW) \
    EL(_HEAVY_NORTH_EAST_ARROW) \
    EL(_DRAFTING_POINT_RIGHTWARDS_ARROW) \
    EL(_HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW) \
    EL(_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_BLACK_RIGHTWARDS_ARROW) \
    EL(_THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_BLACK_RIGHTWARDS_ARROWHEAD) \
    EL(_HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_SQUAT_BLACK_RIGHTWARDS_ARROW) \
    EL(_HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW) \
    EL(_RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_LEFT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW) \
    EL(_WHITE_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_TEARDROP_BARBED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW) \
    EL(_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_OPEN_OUTLINED_RIGHTWARDS_ARROW)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_MAC_DINGBATS(EL) \
    EL(_MEDIUM_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT) \
    EL(_MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT) \
    EL(_HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT) \
    EL(_LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT) \
    EL(_MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT) \
    EL(_MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT) \
    EL(_CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT) \
    EL(_HEAVY_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT) \
    EL(_HEAVY_BLACK_HEART) \
    EL(_ROTATED_HEAVY_BLACK_HEART_BULLET) \
    EL(_FLORAL_HEART) \
    EL(_ROTATED_FLORAL_HEART_BULLET) \
    EL(_BLACK_CLUB_SUIT) \
    EL(_BLACK_DIAMOND_SUIT) \
    EL(_BLACK_HEART_SUIT) \
    EL(_BLACK_SPADE_SUIT) \
    EL(_CIRCLED_DIGIT_ONE) \
    EL(_CIRCLED_DIGIT_TWO) \
    EL(_CIRCLED_DIGIT_THREE) \
    EL(_CIRCLED_DIGIT_FOUR) \
    EL(_CIRCLED_DIGIT_FIVE) \
    EL(_CIRCLED_DIGIT_SIX) \
    EL(_CIRCLED_DIGIT_SEVEN) \
    EL(_CIRCLED_DIGIT_EIGHT) \
    EL(_CIRCLED_DIGIT_NINE) \
    EL(_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE) \
    EL(_DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN) \
    EL(_HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW) \
    EL(_RIGHTWARDS_ARROW) \
    EL(_LEFT_RIGHT_ARROW) \
    EL(_UP_DOWN_ARROW) \
    EL(_HEAVY_SOUTH_EAST_ARROW) \
    EL(_HEAVY_RIGHTWARDS_ARROW) \
    EL(_HEAVY_NORTH_EAST_ARROW) \
    EL(_DRAFTING_POINT_RIGHTWARDS_ARROW) \
    EL(_HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW) \
    EL(_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW) \
    EL(_BLACK_RIGHTWARDS_ARROW) \
    EL(_THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD) \
    EL(_BLACK_RIGHTWARDS_ARROWHEAD) \
    EL(_HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW) \
    EL(_SQUAT_BLACK_RIGHTWARDS_ARROW) \
    EL(_HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW) \
    EL(_RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_LEFT_SHADED_WHITE_RIGHTWARDS_ARROW) \
    EL(_BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW) \
    EL(_CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW) \
    EL(_WHITE_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW) \
    EL(_TEARDROP_BARBED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW) \
    EL(_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW) \
    EL(_OPEN_OUTLINED_RIGHTWARDS_ARROW)


#endif /* _TUTF_MAC_DINGBATS_H */
