
/*
 * This file was automatically generated from unicode
 * charset definition files http://unicode.org/Public/MAPPINGS/
 * using the script twin/scripts/helper-from-unicode.org.bash
 *
 * PLEASE DO NOT EDIT!
 */


#ifndef _TUTF_MAC_SYMBOL_H
#define _TUTF_MAC_SYMBOL_H

#define T_MAC_SYMBOL_CTRL_NULL	0x0000
#define T_MAC_SYMBOL_CTRL_START_OF_HEADING	0x0001
#define T_MAC_SYMBOL_CTRL_START_OF_TEXT	0x0002
#define T_MAC_SYMBOL_CTRL_END_OF_TEXT	0x0003
#define T_MAC_SYMBOL_CTRL_END_OF_TRANSMISSION	0x0004
#define T_MAC_SYMBOL_CTRL_ENQUIRY	0x0005
#define T_MAC_SYMBOL_CTRL_ACKNOWLEDGE	0x0006
#define T_MAC_SYMBOL_CTRL_BELL	0x0007
#define T_MAC_SYMBOL_CTRL_BACKSPACE	0x0008
#define T_MAC_SYMBOL_CTRL_CHARACTER_TABULATION	0x0009
#define T_MAC_SYMBOL_CTRL_LINE_FEED	0x000A
#define T_MAC_SYMBOL_CTRL_LINE_TABULATION	0x000B
#define T_MAC_SYMBOL_CTRL_FORM_FEED	0x000C
#define T_MAC_SYMBOL_CTRL_CARRIAGE_RETURN	0x000D
#define T_MAC_SYMBOL_CTRL_SHIFT_OUT	0x000E
#define T_MAC_SYMBOL_CTRL_SHIFT_IN	0x000F
#define T_MAC_SYMBOL_CTRL_DATA_LINK_ESCAPE	0x0010
#define T_MAC_SYMBOL_CTRL_DEVICE_CONTROL_ONE	0x0011
#define T_MAC_SYMBOL_CTRL_DEVICE_CONTROL_TWO	0x0012
#define T_MAC_SYMBOL_CTRL_DEVICE_CONTROL_THREE	0x0013
#define T_MAC_SYMBOL_CTRL_DEVICE_CONTROL_FOUR	0x0014
#define T_MAC_SYMBOL_CTRL_NEGATIVE_ACKNOWLEDGE	0x0015
#define T_MAC_SYMBOL_CTRL_SYNCHRONOUS_IDLE	0x0016
#define T_MAC_SYMBOL_CTRL_END_OF_TRANSMISSION_BLOCK	0x0017
#define T_MAC_SYMBOL_CTRL_CANCEL	0x0018
#define T_MAC_SYMBOL_CTRL_END_OF_MEDIUM	0x0019
#define T_MAC_SYMBOL_CTRL_SUBSTITUTE	0x001A
#define T_MAC_SYMBOL_CTRL_ESCAPE	0x001B
#define T_MAC_SYMBOL_CTRL_INFORMATION_SEPARATOR_FOUR	0x001C
#define T_MAC_SYMBOL_CTRL_INFORMATION_SEPARATOR_THREE	0x001D
#define T_MAC_SYMBOL_CTRL_INFORMATION_SEPARATOR_TWO	0x001E
#define T_MAC_SYMBOL_CTRL_INFORMATION_SEPARATOR_ONE	0x001F
#define T_MAC_SYMBOL_SPACE	0x0020
#define T_MAC_SYMBOL_EXCLAMATION_MARK	0x0021
#define T_MAC_SYMBOL_QUOTATION_MARK	0x0022
#define T_MAC_SYMBOL_NUMBER_SIGN	0x0023
#define T_MAC_SYMBOL_DOLLAR_SIGN	0x0024
#define T_MAC_SYMBOL_PERCENT_SIGN	0x0025
#define T_MAC_SYMBOL_AMPERSAND	0x0026
#define T_MAC_SYMBOL_APOSTROPHE	0x0027
#define T_MAC_SYMBOL_LEFT_PARENTHESIS	0x0028
#define T_MAC_SYMBOL_RIGHT_PARENTHESIS	0x0029
#define T_MAC_SYMBOL_ASTERISK	0x002A
#define T_MAC_SYMBOL_PLUS_SIGN	0x002B
#define T_MAC_SYMBOL_COMMA	0x002C
#define T_MAC_SYMBOL_HYPHEN_MINUS	0x002D
#define T_MAC_SYMBOL_FULL_STOP	0x002E
#define T_MAC_SYMBOL_SOLIDUS	0x002F
#define T_MAC_SYMBOL_DIGIT_ZERO	0x0030
#define T_MAC_SYMBOL_DIGIT_ONE	0x0031
#define T_MAC_SYMBOL_DIGIT_TWO	0x0032
#define T_MAC_SYMBOL_DIGIT_THREE	0x0033
#define T_MAC_SYMBOL_DIGIT_FOUR	0x0034
#define T_MAC_SYMBOL_DIGIT_FIVE	0x0035
#define T_MAC_SYMBOL_DIGIT_SIX	0x0036
#define T_MAC_SYMBOL_DIGIT_SEVEN	0x0037
#define T_MAC_SYMBOL_DIGIT_EIGHT	0x0038
#define T_MAC_SYMBOL_DIGIT_NINE	0x0039
#define T_MAC_SYMBOL_COLON	0x003A
#define T_MAC_SYMBOL_SEMICOLON	0x003B
#define T_MAC_SYMBOL_LESS_THAN_SIGN	0x003C
#define T_MAC_SYMBOL_EQUALS_SIGN	0x003D
#define T_MAC_SYMBOL_GREATER_THAN_SIGN	0x003E
#define T_MAC_SYMBOL_QUESTION_MARK	0x003F
#define T_MAC_SYMBOL_COMMERCIAL_AT	0x0040
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_A	0x0041
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_B	0x0042
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_C	0x0043
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_D	0x0044
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_E	0x0045
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_F	0x0046
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_G	0x0047
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_H	0x0048
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_I	0x0049
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_J	0x004A
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_K	0x004B
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_L	0x004C
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_M	0x004D
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_N	0x004E
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_O	0x004F
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_P	0x0050
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_Q	0x0051
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_R	0x0052
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_S	0x0053
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_T	0x0054
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_U	0x0055
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_V	0x0056
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_W	0x0057
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_X	0x0058
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_Y	0x0059
#define T_MAC_SYMBOL_LATIN_CAPITAL_LETTER_Z	0x005A
#define T_MAC_SYMBOL_LEFT_SQUARE_BRACKET	0x005B
#define T_MAC_SYMBOL_REVERSE_SOLIDUS	0x005C
#define T_MAC_SYMBOL_RIGHT_SQUARE_BRACKET	0x005D
#define T_MAC_SYMBOL_CIRCUMFLEX_ACCENT	0x005E
#define T_MAC_SYMBOL_LOW_LINE	0x005F
#define T_MAC_SYMBOL_GRAVE_ACCENT	0x0060
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_A	0x0061
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_B	0x0062
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_C	0x0063
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_D	0x0064
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_E	0x0065
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_F	0x0066
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_G	0x0067
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_H	0x0068
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_I	0x0069
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_J	0x006A
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_K	0x006B
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_L	0x006C
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_M	0x006D
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_N	0x006E
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_O	0x006F
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_P	0x0070
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_Q	0x0071
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_R	0x0072
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_S	0x0073
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_T	0x0074
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_U	0x0075
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_V	0x0076
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_W	0x0077
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_X	0x0078
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_Y	0x0079
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_Z	0x007A
#define T_MAC_SYMBOL_LEFT_CURLY_BRACKET	0x007B
#define T_MAC_SYMBOL_VERTICAL_LINE	0x007C
#define T_MAC_SYMBOL_RIGHT_CURLY_BRACKET	0x007D
#define T_MAC_SYMBOL_TILDE	0x007E
#define T_MAC_SYMBOL_CTRL_DELETE	0x007F
#define T_MAC_SYMBOL_UNDEFINED_0080	0x0080
#define T_MAC_SYMBOL_UNDEFINED_0081	0x0081
#define T_MAC_SYMBOL_UNDEFINED_0082	0x0082
#define T_MAC_SYMBOL_UNDEFINED_0083	0x0083
#define T_MAC_SYMBOL_UNDEFINED_0084	0x0084
#define T_MAC_SYMBOL_UNDEFINED_0085	0x0085
#define T_MAC_SYMBOL_UNDEFINED_0086	0x0086
#define T_MAC_SYMBOL_UNDEFINED_0087	0x0087
#define T_MAC_SYMBOL_UNDEFINED_0088	0x0088
#define T_MAC_SYMBOL_UNDEFINED_0089	0x0089
#define T_MAC_SYMBOL_UNDEFINED_008A	0x008A
#define T_MAC_SYMBOL_UNDEFINED_008B	0x008B
#define T_MAC_SYMBOL_UNDEFINED_008C	0x008C
#define T_MAC_SYMBOL_UNDEFINED_008D	0x008D
#define T_MAC_SYMBOL_UNDEFINED_008E	0x008E
#define T_MAC_SYMBOL_UNDEFINED_008F	0x008F
#define T_MAC_SYMBOL_UNDEFINED_0090	0x0090
#define T_MAC_SYMBOL_UNDEFINED_0091	0x0091
#define T_MAC_SYMBOL_UNDEFINED_0092	0x0092
#define T_MAC_SYMBOL_UNDEFINED_0093	0x0093
#define T_MAC_SYMBOL_UNDEFINED_0094	0x0094
#define T_MAC_SYMBOL_UNDEFINED_0095	0x0095
#define T_MAC_SYMBOL_UNDEFINED_0096	0x0096
#define T_MAC_SYMBOL_UNDEFINED_0097	0x0097
#define T_MAC_SYMBOL_UNDEFINED_0098	0x0098
#define T_MAC_SYMBOL_UNDEFINED_0099	0x0099
#define T_MAC_SYMBOL_UNDEFINED_009A	0x009A
#define T_MAC_SYMBOL_UNDEFINED_009B	0x009B
#define T_MAC_SYMBOL_UNDEFINED_009C	0x009C
#define T_MAC_SYMBOL_UNDEFINED_009D	0x009D
#define T_MAC_SYMBOL_UNDEFINED_009E	0x009E
#define T_MAC_SYMBOL_UNDEFINED_009F	0x009F
#define T_MAC_SYMBOL_EURO_SIGN	0x00A0
#define T_MAC_SYMBOL_GREEK_UPSILON_WITH_HOOK_SYMBOL	0x00A1
#define T_MAC_SYMBOL_PRIME	0x00A2
#define T_MAC_SYMBOL_LESS_THAN_OR_EQUAL_TO	0x00A3
#define T_MAC_SYMBOL_FRACTION_SLASH	0x00A4
#define T_MAC_SYMBOL_INFINITY	0x00A5
#define T_MAC_SYMBOL_LATIN_SMALL_LETTER_F_WITH_HOOK	0x00A6
#define T_MAC_SYMBOL_BLACK_CLUB_SUIT	0x00A7
#define T_MAC_SYMBOL_BLACK_DIAMOND_SUIT	0x00A8
#define T_MAC_SYMBOL_BLACK_HEART_SUIT	0x00A9
#define T_MAC_SYMBOL_BLACK_SPADE_SUIT	0x00AA
#define T_MAC_SYMBOL_LEFT_RIGHT_ARROW	0x00AB
#define T_MAC_SYMBOL_LEFTWARDS_ARROW	0x00AC
#define T_MAC_SYMBOL_UPWARDS_ARROW	0x00AD
#define T_MAC_SYMBOL_RIGHTWARDS_ARROW	0x00AE
#define T_MAC_SYMBOL_DOWNWARDS_ARROW	0x00AF
#define T_MAC_SYMBOL_DEGREE_SIGN	0x00B0
#define T_MAC_SYMBOL_PLUS_MINUS_SIGN	0x00B1
#define T_MAC_SYMBOL_DOUBLE_PRIME	0x00B2
#define T_MAC_SYMBOL_GREATER_THAN_OR_EQUAL_TO	0x00B3
#define T_MAC_SYMBOL_MULTIPLICATION_SIGN	0x00B4
#define T_MAC_SYMBOL_PROPORTIONAL_TO	0x00B5
#define T_MAC_SYMBOL_PARTIAL_DIFFERENTIAL	0x00B6
#define T_MAC_SYMBOL_BULLET	0x00B7
#define T_MAC_SYMBOL_DIVISION_SIGN	0x00B8
#define T_MAC_SYMBOL_NOT_EQUAL_TO	0x00B9
#define T_MAC_SYMBOL_IDENTICAL_TO	0x00BA
#define T_MAC_SYMBOL_ALMOST_EQUAL_TO	0x00BB
#define T_MAC_SYMBOL_HORIZONTAL_ELLIPSIS	0x00BC
#define T_MAC_SYMBOL_VERTICAL_LINE_EXTENSION	0x00BD
#define T_MAC_SYMBOL_HORIZONTAL_LINE_EXTENSION	0x00BE
#define T_MAC_SYMBOL_DOWNWARDS_ARROW_WITH_CORNER_LEFTWARDS	0x00BF
#define T_MAC_SYMBOL_ALEF_SYMBOL	0x00C0
#define T_MAC_SYMBOL_BLACK_LETTER_CAPITAL_I	0x00C1
#define T_MAC_SYMBOL_BLACK_LETTER_CAPITAL_R	0x00C2
#define T_MAC_SYMBOL_SCRIPT_CAPITAL_P	0x00C3
#define T_MAC_SYMBOL_CIRCLED_TIMES	0x00C4
#define T_MAC_SYMBOL_CIRCLED_PLUS	0x00C5
#define T_MAC_SYMBOL_EMPTY_SET	0x00C6
#define T_MAC_SYMBOL_INTERSECTION	0x00C7
#define T_MAC_SYMBOL_UNION	0x00C8
#define T_MAC_SYMBOL_SUPERSET_OF	0x00C9
#define T_MAC_SYMBOL_SUPERSET_OF_OR_EQUAL_TO	0x00CA
#define T_MAC_SYMBOL_NOT_A_SUBSET_OF	0x00CB
#define T_MAC_SYMBOL_SUBSET_OF	0x00CC
#define T_MAC_SYMBOL_SUBSET_OF_OR_EQUAL_TO	0x00CD
#define T_MAC_SYMBOL_ELEMENT_OF	0x00CE
#define T_MAC_SYMBOL_NOT_AN_ELEMENT_OF	0x00CF
#define T_MAC_SYMBOL_ANGLE	0x00D0
#define T_MAC_SYMBOL_NABLA	0x00D1
#define T_MAC_SYMBOL_REGISTERED_SIGN	0x00D2
#define T_MAC_SYMBOL_COPYRIGHT_SIGN	0x00D3
#define T_MAC_SYMBOL_TRADE_MARK_SIGN	0x00D4
#define T_MAC_SYMBOL_N_ARY_PRODUCT	0x00D5
#define T_MAC_SYMBOL_SQUARE_ROOT	0x00D6
#define T_MAC_SYMBOL_DOT_OPERATOR	0x00D7
#define T_MAC_SYMBOL_NOT_SIGN	0x00D8
#define T_MAC_SYMBOL_LOGICAL_AND	0x00D9
#define T_MAC_SYMBOL_LOGICAL_OR	0x00DA
#define T_MAC_SYMBOL_LEFT_RIGHT_DOUBLE_ARROW	0x00DB
#define T_MAC_SYMBOL_LEFTWARDS_DOUBLE_ARROW	0x00DC
#define T_MAC_SYMBOL_UPWARDS_DOUBLE_ARROW	0x00DD
#define T_MAC_SYMBOL_RIGHTWARDS_DOUBLE_ARROW	0x00DE
#define T_MAC_SYMBOL_DOWNWARDS_DOUBLE_ARROW	0x00DF
#define T_MAC_SYMBOL_LOZENGE	0x00E0
#define T_MAC_SYMBOL_LEFT_ANGLE_BRACKET	0x00E1
#define T_MAC_SYMBOL_CJK_COMPATIBILITY_IDEOGRAPH_F92D	0x00E2
#define T_MAC_SYMBOL_CJK_COMPATIBILITY_IDEOGRAPH_F928	0x00E3
#define T_MAC_SYMBOL_UNDEFINED_00E4	0x00E4
#define T_MAC_SYMBOL_N_ARY_SUMMATION	0x00E5
#define T_MAC_SYMBOL_LEFT_PARENTHESIS_UPPER_HOOK	0x00E6
#define T_MAC_SYMBOL_LEFT_PARENTHESIS_EXTENSION	0x00E7
#define T_MAC_SYMBOL_LEFT_PARENTHESIS_LOWER_HOOK	0x00E8
#define T_MAC_SYMBOL_LEFT_SQUARE_BRACKET_UPPER_CORNER	0x00E9
#define T_MAC_SYMBOL_LEFT_SQUARE_BRACKET_EXTENSION	0x00EA
#define T_MAC_SYMBOL_LEFT_SQUARE_BRACKET_LOWER_CORNER	0x00EB
#define T_MAC_SYMBOL_LEFT_CURLY_BRACKET_UPPER_HOOK	0x00EC
#define T_MAC_SYMBOL_LEFT_CURLY_BRACKET_MIDDLE_PIECE	0x00ED
#define T_MAC_SYMBOL_LEFT_CURLY_BRACKET_LOWER_HOOK	0x00EE
#define T_MAC_SYMBOL_CURLY_BRACKET_EXTENSION	0x00EF
#define T_MAC_SYMBOL_UNDEFINED_00F0	0x00F0
#define T_MAC_SYMBOL_RIGHT_ANGLE_BRACKET	0x00F1
#define T_MAC_SYMBOL_INTEGRAL	0x00F2
#define T_MAC_SYMBOL_TOP_HALF_INTEGRAL	0x00F3
#define T_MAC_SYMBOL_INTEGRAL_EXTENSION	0x00F4
#define T_MAC_SYMBOL_BOTTOM_HALF_INTEGRAL	0x00F5
#define T_MAC_SYMBOL_RIGHT_PARENTHESIS_UPPER_HOOK	0x00F6
#define T_MAC_SYMBOL_RIGHT_PARENTHESIS_EXTENSION	0x00F7
#define T_MAC_SYMBOL_RIGHT_PARENTHESIS_LOWER_HOOK	0x00F8
#define T_MAC_SYMBOL_RIGHT_SQUARE_BRACKET_UPPER_CORNER	0x00F9
#define T_MAC_SYMBOL_RIGHT_SQUARE_BRACKET_EXTENSION	0x00FA
#define T_MAC_SYMBOL_RIGHT_SQUARE_BRACKET_LOWER_CORNER	0x00FB
#define T_MAC_SYMBOL_RIGHT_CURLY_BRACKET_UPPER_HOOK	0x00FC
#define T_MAC_SYMBOL_RIGHT_CURLY_BRACKET_MIDDLE_PIECE	0x00FD
#define T_MAC_SYMBOL_RIGHT_CURLY_BRACKET_LOWER_HOOK	0x00FE
#define T_MAC_SYMBOL_UNDEFINED_00FF	0x00FF

/* list of all characters */
#define T_LIST_MAC_SYMBOL(EL) \
    EL(_CTRL_NULL) \
    EL(_CTRL_START_OF_HEADING) \
    EL(_CTRL_START_OF_TEXT) \
    EL(_CTRL_END_OF_TEXT) \
    EL(_CTRL_END_OF_TRANSMISSION) \
    EL(_CTRL_ENQUIRY) \
    EL(_CTRL_ACKNOWLEDGE) \
    EL(_CTRL_BELL) \
    EL(_CTRL_BACKSPACE) \
    EL(_CTRL_CHARACTER_TABULATION) \
    EL(_CTRL_LINE_FEED) \
    EL(_CTRL_LINE_TABULATION) \
    EL(_CTRL_FORM_FEED) \
    EL(_CTRL_CARRIAGE_RETURN) \
    EL(_CTRL_SHIFT_OUT) \
    EL(_CTRL_SHIFT_IN) \
    EL(_CTRL_DATA_LINK_ESCAPE) \
    EL(_CTRL_DEVICE_CONTROL_ONE) \
    EL(_CTRL_DEVICE_CONTROL_TWO) \
    EL(_CTRL_DEVICE_CONTROL_THREE) \
    EL(_CTRL_DEVICE_CONTROL_FOUR) \
    EL(_CTRL_NEGATIVE_ACKNOWLEDGE) \
    EL(_CTRL_SYNCHRONOUS_IDLE) \
    EL(_CTRL_END_OF_TRANSMISSION_BLOCK) \
    EL(_CTRL_CANCEL) \
    EL(_CTRL_END_OF_MEDIUM) \
    EL(_CTRL_SUBSTITUTE) \
    EL(_CTRL_ESCAPE) \
    EL(_CTRL_INFORMATION_SEPARATOR_FOUR) \
    EL(_CTRL_INFORMATION_SEPARATOR_THREE) \
    EL(_CTRL_INFORMATION_SEPARATOR_TWO) \
    EL(_CTRL_INFORMATION_SEPARATOR_ONE) \
    EL(_SPACE) \
    EL(_EXCLAMATION_MARK) \
    EL(_QUOTATION_MARK) \
    EL(_NUMBER_SIGN) \
    EL(_DOLLAR_SIGN) \
    EL(_PERCENT_SIGN) \
    EL(_AMPERSAND) \
    EL(_APOSTROPHE) \
    EL(_LEFT_PARENTHESIS) \
    EL(_RIGHT_PARENTHESIS) \
    EL(_ASTERISK) \
    EL(_PLUS_SIGN) \
    EL(_COMMA) \
    EL(_HYPHEN_MINUS) \
    EL(_FULL_STOP) \
    EL(_SOLIDUS) \
    EL(_DIGIT_ZERO) \
    EL(_DIGIT_ONE) \
    EL(_DIGIT_TWO) \
    EL(_DIGIT_THREE) \
    EL(_DIGIT_FOUR) \
    EL(_DIGIT_FIVE) \
    EL(_DIGIT_SIX) \
    EL(_DIGIT_SEVEN) \
    EL(_DIGIT_EIGHT) \
    EL(_DIGIT_NINE) \
    EL(_COLON) \
    EL(_SEMICOLON) \
    EL(_LESS_THAN_SIGN) \
    EL(_EQUALS_SIGN) \
    EL(_GREATER_THAN_SIGN) \
    EL(_QUESTION_MARK) \
    EL(_COMMERCIAL_AT) \
    EL(_LATIN_CAPITAL_LETTER_A) \
    EL(_LATIN_CAPITAL_LETTER_B) \
    EL(_LATIN_CAPITAL_LETTER_C) \
    EL(_LATIN_CAPITAL_LETTER_D) \
    EL(_LATIN_CAPITAL_LETTER_E) \
    EL(_LATIN_CAPITAL_LETTER_F) \
    EL(_LATIN_CAPITAL_LETTER_G) \
    EL(_LATIN_CAPITAL_LETTER_H) \
    EL(_LATIN_CAPITAL_LETTER_I) \
    EL(_LATIN_CAPITAL_LETTER_J) \
    EL(_LATIN_CAPITAL_LETTER_K) \
    EL(_LATIN_CAPITAL_LETTER_L) \
    EL(_LATIN_CAPITAL_LETTER_M) \
    EL(_LATIN_CAPITAL_LETTER_N) \
    EL(_LATIN_CAPITAL_LETTER_O) \
    EL(_LATIN_CAPITAL_LETTER_P) \
    EL(_LATIN_CAPITAL_LETTER_Q) \
    EL(_LATIN_CAPITAL_LETTER_R) \
    EL(_LATIN_CAPITAL_LETTER_S) \
    EL(_LATIN_CAPITAL_LETTER_T) \
    EL(_LATIN_CAPITAL_LETTER_U) \
    EL(_LATIN_CAPITAL_LETTER_V) \
    EL(_LATIN_CAPITAL_LETTER_W) \
    EL(_LATIN_CAPITAL_LETTER_X) \
    EL(_LATIN_CAPITAL_LETTER_Y) \
    EL(_LATIN_CAPITAL_LETTER_Z) \
    EL(_LEFT_SQUARE_BRACKET) \
    EL(_REVERSE_SOLIDUS) \
    EL(_RIGHT_SQUARE_BRACKET) \
    EL(_CIRCUMFLEX_ACCENT) \
    EL(_LOW_LINE) \
    EL(_GRAVE_ACCENT) \
    EL(_LATIN_SMALL_LETTER_A) \
    EL(_LATIN_SMALL_LETTER_B) \
    EL(_LATIN_SMALL_LETTER_C) \
    EL(_LATIN_SMALL_LETTER_D) \
    EL(_LATIN_SMALL_LETTER_E) \
    EL(_LATIN_SMALL_LETTER_F) \
    EL(_LATIN_SMALL_LETTER_G) \
    EL(_LATIN_SMALL_LETTER_H) \
    EL(_LATIN_SMALL_LETTER_I) \
    EL(_LATIN_SMALL_LETTER_J) \
    EL(_LATIN_SMALL_LETTER_K) \
    EL(_LATIN_SMALL_LETTER_L) \
    EL(_LATIN_SMALL_LETTER_M) \
    EL(_LATIN_SMALL_LETTER_N) \
    EL(_LATIN_SMALL_LETTER_O) \
    EL(_LATIN_SMALL_LETTER_P) \
    EL(_LATIN_SMALL_LETTER_Q) \
    EL(_LATIN_SMALL_LETTER_R) \
    EL(_LATIN_SMALL_LETTER_S) \
    EL(_LATIN_SMALL_LETTER_T) \
    EL(_LATIN_SMALL_LETTER_U) \
    EL(_LATIN_SMALL_LETTER_V) \
    EL(_LATIN_SMALL_LETTER_W) \
    EL(_LATIN_SMALL_LETTER_X) \
    EL(_LATIN_SMALL_LETTER_Y) \
    EL(_LATIN_SMALL_LETTER_Z) \
    EL(_LEFT_CURLY_BRACKET) \
    EL(_VERTICAL_LINE) \
    EL(_RIGHT_CURLY_BRACKET) \
    EL(_TILDE) \
    EL(_CTRL_DELETE) \
    EL(_EURO_SIGN) \
    EL(_GREEK_UPSILON_WITH_HOOK_SYMBOL) \
    EL(_PRIME) \
    EL(_LESS_THAN_OR_EQUAL_TO) \
    EL(_FRACTION_SLASH) \
    EL(_INFINITY) \
    EL(_LATIN_SMALL_LETTER_F_WITH_HOOK) \
    EL(_BLACK_CLUB_SUIT) \
    EL(_BLACK_DIAMOND_SUIT) \
    EL(_BLACK_HEART_SUIT) \
    EL(_BLACK_SPADE_SUIT) \
    EL(_LEFT_RIGHT_ARROW) \
    EL(_LEFTWARDS_ARROW) \
    EL(_UPWARDS_ARROW) \
    EL(_RIGHTWARDS_ARROW) \
    EL(_DOWNWARDS_ARROW) \
    EL(_DEGREE_SIGN) \
    EL(_PLUS_MINUS_SIGN) \
    EL(_DOUBLE_PRIME) \
    EL(_GREATER_THAN_OR_EQUAL_TO) \
    EL(_MULTIPLICATION_SIGN) \
    EL(_PROPORTIONAL_TO) \
    EL(_PARTIAL_DIFFERENTIAL) \
    EL(_BULLET) \
    EL(_DIVISION_SIGN) \
    EL(_NOT_EQUAL_TO) \
    EL(_IDENTICAL_TO) \
    EL(_ALMOST_EQUAL_TO) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_VERTICAL_LINE_EXTENSION) \
    EL(_HORIZONTAL_LINE_EXTENSION) \
    EL(_DOWNWARDS_ARROW_WITH_CORNER_LEFTWARDS) \
    EL(_ALEF_SYMBOL) \
    EL(_BLACK_LETTER_CAPITAL_I) \
    EL(_BLACK_LETTER_CAPITAL_R) \
    EL(_SCRIPT_CAPITAL_P) \
    EL(_CIRCLED_TIMES) \
    EL(_CIRCLED_PLUS) \
    EL(_EMPTY_SET) \
    EL(_INTERSECTION) \
    EL(_UNION) \
    EL(_SUPERSET_OF) \
    EL(_SUPERSET_OF_OR_EQUAL_TO) \
    EL(_NOT_A_SUBSET_OF) \
    EL(_SUBSET_OF) \
    EL(_SUBSET_OF_OR_EQUAL_TO) \
    EL(_ELEMENT_OF) \
    EL(_NOT_AN_ELEMENT_OF) \
    EL(_ANGLE) \
    EL(_NABLA) \
    EL(_REGISTERED_SIGN) \
    EL(_COPYRIGHT_SIGN) \
    EL(_TRADE_MARK_SIGN) \
    EL(_N_ARY_PRODUCT) \
    EL(_SQUARE_ROOT) \
    EL(_DOT_OPERATOR) \
    EL(_NOT_SIGN) \
    EL(_LOGICAL_AND) \
    EL(_LOGICAL_OR) \
    EL(_LEFT_RIGHT_DOUBLE_ARROW) \
    EL(_LEFTWARDS_DOUBLE_ARROW) \
    EL(_UPWARDS_DOUBLE_ARROW) \
    EL(_RIGHTWARDS_DOUBLE_ARROW) \
    EL(_DOWNWARDS_DOUBLE_ARROW) \
    EL(_LOZENGE) \
    EL(_LEFT_ANGLE_BRACKET) \
    EL(_CJK_COMPATIBILITY_IDEOGRAPH_F92D) \
    EL(_CJK_COMPATIBILITY_IDEOGRAPH_F928) \
    EL(_N_ARY_SUMMATION) \
    EL(_LEFT_PARENTHESIS_UPPER_HOOK) \
    EL(_LEFT_PARENTHESIS_EXTENSION) \
    EL(_LEFT_PARENTHESIS_LOWER_HOOK) \
    EL(_LEFT_SQUARE_BRACKET_UPPER_CORNER) \
    EL(_LEFT_SQUARE_BRACKET_EXTENSION) \
    EL(_LEFT_SQUARE_BRACKET_LOWER_CORNER) \
    EL(_LEFT_CURLY_BRACKET_UPPER_HOOK) \
    EL(_LEFT_CURLY_BRACKET_MIDDLE_PIECE) \
    EL(_LEFT_CURLY_BRACKET_LOWER_HOOK) \
    EL(_CURLY_BRACKET_EXTENSION) \
    EL(_UNDEFINED_00F0) \
    EL(_RIGHT_ANGLE_BRACKET) \
    EL(_INTEGRAL) \
    EL(_TOP_HALF_INTEGRAL) \
    EL(_INTEGRAL_EXTENSION) \
    EL(_BOTTOM_HALF_INTEGRAL) \
    EL(_RIGHT_PARENTHESIS_UPPER_HOOK) \
    EL(_RIGHT_PARENTHESIS_EXTENSION) \
    EL(_RIGHT_PARENTHESIS_LOWER_HOOK) \
    EL(_RIGHT_SQUARE_BRACKET_UPPER_CORNER) \
    EL(_RIGHT_SQUARE_BRACKET_EXTENSION) \
    EL(_RIGHT_SQUARE_BRACKET_LOWER_CORNER) \
    EL(_RIGHT_CURLY_BRACKET_UPPER_HOOK) \
    EL(_RIGHT_CURLY_BRACKET_MIDDLE_PIECE) \
    EL(_RIGHT_CURLY_BRACKET_LOWER_HOOK)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_MAC_SYMBOL(EL) \
    EL(_EURO_SIGN) \
    EL(_GREEK_UPSILON_WITH_HOOK_SYMBOL) \
    EL(_PRIME) \
    EL(_LESS_THAN_OR_EQUAL_TO) \
    EL(_FRACTION_SLASH) \
    EL(_INFINITY) \
    EL(_LATIN_SMALL_LETTER_F_WITH_HOOK) \
    EL(_BLACK_CLUB_SUIT) \
    EL(_BLACK_DIAMOND_SUIT) \
    EL(_BLACK_HEART_SUIT) \
    EL(_BLACK_SPADE_SUIT) \
    EL(_LEFT_RIGHT_ARROW) \
    EL(_LEFTWARDS_ARROW) \
    EL(_UPWARDS_ARROW) \
    EL(_RIGHTWARDS_ARROW) \
    EL(_DOWNWARDS_ARROW) \
    EL(_DOUBLE_PRIME) \
    EL(_GREATER_THAN_OR_EQUAL_TO) \
    EL(_MULTIPLICATION_SIGN) \
    EL(_PROPORTIONAL_TO) \
    EL(_PARTIAL_DIFFERENTIAL) \
    EL(_BULLET) \
    EL(_DIVISION_SIGN) \
    EL(_NOT_EQUAL_TO) \
    EL(_IDENTICAL_TO) \
    EL(_ALMOST_EQUAL_TO) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_VERTICAL_LINE_EXTENSION) \
    EL(_HORIZONTAL_LINE_EXTENSION) \
    EL(_DOWNWARDS_ARROW_WITH_CORNER_LEFTWARDS) \
    EL(_ALEF_SYMBOL) \
    EL(_BLACK_LETTER_CAPITAL_I) \
    EL(_BLACK_LETTER_CAPITAL_R) \
    EL(_SCRIPT_CAPITAL_P) \
    EL(_CIRCLED_TIMES) \
    EL(_CIRCLED_PLUS) \
    EL(_EMPTY_SET) \
    EL(_INTERSECTION) \
    EL(_UNION) \
    EL(_SUPERSET_OF) \
    EL(_SUPERSET_OF_OR_EQUAL_TO) \
    EL(_NOT_A_SUBSET_OF) \
    EL(_SUBSET_OF) \
    EL(_SUBSET_OF_OR_EQUAL_TO) \
    EL(_ELEMENT_OF) \
    EL(_NOT_AN_ELEMENT_OF) \
    EL(_ANGLE) \
    EL(_NABLA) \
    EL(_REGISTERED_SIGN) \
    EL(_COPYRIGHT_SIGN) \
    EL(_TRADE_MARK_SIGN) \
    EL(_N_ARY_PRODUCT) \
    EL(_SQUARE_ROOT) \
    EL(_DOT_OPERATOR) \
    EL(_NOT_SIGN) \
    EL(_LOGICAL_AND) \
    EL(_LOGICAL_OR) \
    EL(_LEFT_RIGHT_DOUBLE_ARROW) \
    EL(_LEFTWARDS_DOUBLE_ARROW) \
    EL(_UPWARDS_DOUBLE_ARROW) \
    EL(_RIGHTWARDS_DOUBLE_ARROW) \
    EL(_DOWNWARDS_DOUBLE_ARROW) \
    EL(_LOZENGE) \
    EL(_LEFT_ANGLE_BRACKET) \
    EL(_CJK_COMPATIBILITY_IDEOGRAPH_F92D) \
    EL(_CJK_COMPATIBILITY_IDEOGRAPH_F928) \
    EL(_N_ARY_SUMMATION) \
    EL(_LEFT_PARENTHESIS_UPPER_HOOK) \
    EL(_LEFT_PARENTHESIS_EXTENSION) \
    EL(_LEFT_PARENTHESIS_LOWER_HOOK) \
    EL(_LEFT_SQUARE_BRACKET_UPPER_CORNER) \
    EL(_LEFT_SQUARE_BRACKET_EXTENSION) \
    EL(_LEFT_SQUARE_BRACKET_LOWER_CORNER) \
    EL(_LEFT_CURLY_BRACKET_UPPER_HOOK) \
    EL(_LEFT_CURLY_BRACKET_MIDDLE_PIECE) \
    EL(_LEFT_CURLY_BRACKET_LOWER_HOOK) \
    EL(_CURLY_BRACKET_EXTENSION) \
    EL(_UNDEFINED_00F0) \
    EL(_RIGHT_ANGLE_BRACKET) \
    EL(_INTEGRAL) \
    EL(_TOP_HALF_INTEGRAL) \
    EL(_INTEGRAL_EXTENSION) \
    EL(_BOTTOM_HALF_INTEGRAL) \
    EL(_RIGHT_PARENTHESIS_UPPER_HOOK) \
    EL(_RIGHT_PARENTHESIS_EXTENSION) \
    EL(_RIGHT_PARENTHESIS_LOWER_HOOK) \
    EL(_RIGHT_SQUARE_BRACKET_UPPER_CORNER) \
    EL(_RIGHT_SQUARE_BRACKET_EXTENSION) \
    EL(_RIGHT_SQUARE_BRACKET_LOWER_CORNER) \
    EL(_RIGHT_CURLY_BRACKET_UPPER_HOOK) \
    EL(_RIGHT_CURLY_BRACKET_MIDDLE_PIECE) \
    EL(_RIGHT_CURLY_BRACKET_LOWER_HOOK)


#endif /* _TUTF_MAC_SYMBOL_H */
