
/*
 * This file was automatically generated from unicode
 * charset definition files http://unicode.org/Public/MAPPINGS/
 * using the script twin/scripts/helper-from-unicode.org.bash
 *
 * PLEASE DO NOT EDIT!
 */


#ifndef _TUTF_NEXTSTEP_H
#define _TUTF_NEXTSTEP_H

#define T_NEXTSTEP_UNDEFINED_0000	0x0000
#define T_NEXTSTEP_UNDEFINED_0001	0x0001
#define T_NEXTSTEP_UNDEFINED_0002	0x0002
#define T_NEXTSTEP_UNDEFINED_0003	0x0003
#define T_NEXTSTEP_UNDEFINED_0004	0x0004
#define T_NEXTSTEP_UNDEFINED_0005	0x0005
#define T_NEXTSTEP_UNDEFINED_0006	0x0006
#define T_NEXTSTEP_UNDEFINED_0007	0x0007
#define T_NEXTSTEP_UNDEFINED_0008	0x0008
#define T_NEXTSTEP_UNDEFINED_0009	0x0009
#define T_NEXTSTEP_UNDEFINED_000A	0x000A
#define T_NEXTSTEP_UNDEFINED_000B	0x000B
#define T_NEXTSTEP_UNDEFINED_000C	0x000C
#define T_NEXTSTEP_UNDEFINED_000D	0x000D
#define T_NEXTSTEP_UNDEFINED_000E	0x000E
#define T_NEXTSTEP_UNDEFINED_000F	0x000F
#define T_NEXTSTEP_UNDEFINED_0010	0x0010
#define T_NEXTSTEP_UNDEFINED_0011	0x0011
#define T_NEXTSTEP_UNDEFINED_0012	0x0012
#define T_NEXTSTEP_UNDEFINED_0013	0x0013
#define T_NEXTSTEP_UNDEFINED_0014	0x0014
#define T_NEXTSTEP_UNDEFINED_0015	0x0015
#define T_NEXTSTEP_UNDEFINED_0016	0x0016
#define T_NEXTSTEP_UNDEFINED_0017	0x0017
#define T_NEXTSTEP_UNDEFINED_0018	0x0018
#define T_NEXTSTEP_UNDEFINED_0019	0x0019
#define T_NEXTSTEP_UNDEFINED_001A	0x001A
#define T_NEXTSTEP_UNDEFINED_001B	0x001B
#define T_NEXTSTEP_UNDEFINED_001C	0x001C
#define T_NEXTSTEP_UNDEFINED_001D	0x001D
#define T_NEXTSTEP_UNDEFINED_001E	0x001E
#define T_NEXTSTEP_UNDEFINED_001F	0x001F
#define T_NEXTSTEP_UNDEFINED_0020	0x0020
#define T_NEXTSTEP_UNDEFINED_0021	0x0021
#define T_NEXTSTEP_UNDEFINED_0022	0x0022
#define T_NEXTSTEP_UNDEFINED_0023	0x0023
#define T_NEXTSTEP_UNDEFINED_0024	0x0024
#define T_NEXTSTEP_UNDEFINED_0025	0x0025
#define T_NEXTSTEP_UNDEFINED_0026	0x0026
#define T_NEXTSTEP_UNDEFINED_0027	0x0027
#define T_NEXTSTEP_UNDEFINED_0028	0x0028
#define T_NEXTSTEP_UNDEFINED_0029	0x0029
#define T_NEXTSTEP_UNDEFINED_002A	0x002A
#define T_NEXTSTEP_UNDEFINED_002B	0x002B
#define T_NEXTSTEP_UNDEFINED_002C	0x002C
#define T_NEXTSTEP_UNDEFINED_002D	0x002D
#define T_NEXTSTEP_UNDEFINED_002E	0x002E
#define T_NEXTSTEP_UNDEFINED_002F	0x002F
#define T_NEXTSTEP_UNDEFINED_0030	0x0030
#define T_NEXTSTEP_UNDEFINED_0031	0x0031
#define T_NEXTSTEP_UNDEFINED_0032	0x0032
#define T_NEXTSTEP_UNDEFINED_0033	0x0033
#define T_NEXTSTEP_UNDEFINED_0034	0x0034
#define T_NEXTSTEP_UNDEFINED_0035	0x0035
#define T_NEXTSTEP_UNDEFINED_0036	0x0036
#define T_NEXTSTEP_UNDEFINED_0037	0x0037
#define T_NEXTSTEP_UNDEFINED_0038	0x0038
#define T_NEXTSTEP_UNDEFINED_0039	0x0039
#define T_NEXTSTEP_UNDEFINED_003A	0x003A
#define T_NEXTSTEP_UNDEFINED_003B	0x003B
#define T_NEXTSTEP_UNDEFINED_003C	0x003C
#define T_NEXTSTEP_UNDEFINED_003D	0x003D
#define T_NEXTSTEP_UNDEFINED_003E	0x003E
#define T_NEXTSTEP_UNDEFINED_003F	0x003F
#define T_NEXTSTEP_UNDEFINED_0040	0x0040
#define T_NEXTSTEP_UNDEFINED_0041	0x0041
#define T_NEXTSTEP_UNDEFINED_0042	0x0042
#define T_NEXTSTEP_UNDEFINED_0043	0x0043
#define T_NEXTSTEP_UNDEFINED_0044	0x0044
#define T_NEXTSTEP_UNDEFINED_0045	0x0045
#define T_NEXTSTEP_UNDEFINED_0046	0x0046
#define T_NEXTSTEP_UNDEFINED_0047	0x0047
#define T_NEXTSTEP_UNDEFINED_0048	0x0048
#define T_NEXTSTEP_UNDEFINED_0049	0x0049
#define T_NEXTSTEP_UNDEFINED_004A	0x004A
#define T_NEXTSTEP_UNDEFINED_004B	0x004B
#define T_NEXTSTEP_UNDEFINED_004C	0x004C
#define T_NEXTSTEP_UNDEFINED_004D	0x004D
#define T_NEXTSTEP_UNDEFINED_004E	0x004E
#define T_NEXTSTEP_UNDEFINED_004F	0x004F
#define T_NEXTSTEP_UNDEFINED_0050	0x0050
#define T_NEXTSTEP_UNDEFINED_0051	0x0051
#define T_NEXTSTEP_UNDEFINED_0052	0x0052
#define T_NEXTSTEP_UNDEFINED_0053	0x0053
#define T_NEXTSTEP_UNDEFINED_0054	0x0054
#define T_NEXTSTEP_UNDEFINED_0055	0x0055
#define T_NEXTSTEP_UNDEFINED_0056	0x0056
#define T_NEXTSTEP_UNDEFINED_0057	0x0057
#define T_NEXTSTEP_UNDEFINED_0058	0x0058
#define T_NEXTSTEP_UNDEFINED_0059	0x0059
#define T_NEXTSTEP_UNDEFINED_005A	0x005A
#define T_NEXTSTEP_UNDEFINED_005B	0x005B
#define T_NEXTSTEP_UNDEFINED_005C	0x005C
#define T_NEXTSTEP_UNDEFINED_005D	0x005D
#define T_NEXTSTEP_UNDEFINED_005E	0x005E
#define T_NEXTSTEP_UNDEFINED_005F	0x005F
#define T_NEXTSTEP_UNDEFINED_0060	0x0060
#define T_NEXTSTEP_UNDEFINED_0061	0x0061
#define T_NEXTSTEP_UNDEFINED_0062	0x0062
#define T_NEXTSTEP_UNDEFINED_0063	0x0063
#define T_NEXTSTEP_UNDEFINED_0064	0x0064
#define T_NEXTSTEP_UNDEFINED_0065	0x0065
#define T_NEXTSTEP_UNDEFINED_0066	0x0066
#define T_NEXTSTEP_UNDEFINED_0067	0x0067
#define T_NEXTSTEP_UNDEFINED_0068	0x0068
#define T_NEXTSTEP_UNDEFINED_0069	0x0069
#define T_NEXTSTEP_UNDEFINED_006A	0x006A
#define T_NEXTSTEP_UNDEFINED_006B	0x006B
#define T_NEXTSTEP_UNDEFINED_006C	0x006C
#define T_NEXTSTEP_UNDEFINED_006D	0x006D
#define T_NEXTSTEP_UNDEFINED_006E	0x006E
#define T_NEXTSTEP_UNDEFINED_006F	0x006F
#define T_NEXTSTEP_UNDEFINED_0070	0x0070
#define T_NEXTSTEP_UNDEFINED_0071	0x0071
#define T_NEXTSTEP_UNDEFINED_0072	0x0072
#define T_NEXTSTEP_UNDEFINED_0073	0x0073
#define T_NEXTSTEP_UNDEFINED_0074	0x0074
#define T_NEXTSTEP_UNDEFINED_0075	0x0075
#define T_NEXTSTEP_UNDEFINED_0076	0x0076
#define T_NEXTSTEP_UNDEFINED_0077	0x0077
#define T_NEXTSTEP_UNDEFINED_0078	0x0078
#define T_NEXTSTEP_UNDEFINED_0079	0x0079
#define T_NEXTSTEP_UNDEFINED_007A	0x007A
#define T_NEXTSTEP_UNDEFINED_007B	0x007B
#define T_NEXTSTEP_UNDEFINED_007C	0x007C
#define T_NEXTSTEP_UNDEFINED_007D	0x007D
#define T_NEXTSTEP_UNDEFINED_007E	0x007E
#define T_NEXTSTEP_UNDEFINED_007F	0x007F
#define T_NEXTSTEP_NO_BREAK_SPACE	0x0080
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_A_WITH_GRAVE	0x0081
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_A_WITH_ACUTE	0x0082
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX	0x0083
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_A_WITH_TILDE	0x0084
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS	0x0085
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE	0x0086
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_C_WITH_CEDILLA	0x0087
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_E_WITH_GRAVE	0x0088
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_E_WITH_ACUTE	0x0089
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX	0x008A
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS	0x008B
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_I_WITH_GRAVE	0x008C
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_I_WITH_ACUTE	0x008D
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX	0x008E
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS	0x008F
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_ETH	0x0090
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_N_WITH_TILDE	0x0091
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_O_WITH_GRAVE	0x0092
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_O_WITH_ACUTE	0x0093
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX	0x0094
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_O_WITH_TILDE	0x0095
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS	0x0096
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_U_WITH_GRAVE	0x0097
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_U_WITH_ACUTE	0x0098
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX	0x0099
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS	0x009A
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_Y_WITH_ACUTE	0x009B
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_THORN	0x009C
#define T_NEXTSTEP_MICRO_SIGN	0x009D
#define T_NEXTSTEP_MULTIPLICATION_SIGN	0x009E
#define T_NEXTSTEP_DIVISION_SIGN	0x009F
#define T_NEXTSTEP_COPYRIGHT_SIGN	0x00A0
#define T_NEXTSTEP_INVERTED_EXCLAMATION_MARK	0x00A1
#define T_NEXTSTEP_CENT_SIGN	0x00A2
#define T_NEXTSTEP_POUND_SIGN	0x00A3
#define T_NEXTSTEP_FRACTION_SLASH	0x00A4
#define T_NEXTSTEP_YEN_SIGN	0x00A5
#define T_NEXTSTEP_LATIN_SMALL_LETTER_F_WITH_HOOK	0x00A6
#define T_NEXTSTEP_SECTION_SIGN	0x00A7
#define T_NEXTSTEP_CURRENCY_SIGN	0x00A8
#define T_NEXTSTEP_RIGHT_SINGLE_QUOTATION_MARK	0x00A9
#define T_NEXTSTEP_LEFT_DOUBLE_QUOTATION_MARK	0x00AA
#define T_NEXTSTEP_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK	0x00AB
#define T_NEXTSTEP_SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK	0x00AC
#define T_NEXTSTEP_SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK	0x00AD
#define T_NEXTSTEP_LATIN_SMALL_LIGATURE_FI	0x00AE
#define T_NEXTSTEP_LATIN_SMALL_LIGATURE_FL	0x00AF
#define T_NEXTSTEP_REGISTERED_SIGN	0x00B0
#define T_NEXTSTEP_EN_DASH	0x00B1
#define T_NEXTSTEP_DAGGER	0x00B2
#define T_NEXTSTEP_DOUBLE_DAGGER	0x00B3
#define T_NEXTSTEP_MIDDLE_DOT	0x00B4
#define T_NEXTSTEP_BROKEN_BAR	0x00B5
#define T_NEXTSTEP_PILCROW_SIGN	0x00B6
#define T_NEXTSTEP_BULLET	0x00B7
#define T_NEXTSTEP_SINGLE_LOW_9_QUOTATION_MARK	0x00B8
#define T_NEXTSTEP_DOUBLE_LOW_9_QUOTATION_MARK	0x00B9
#define T_NEXTSTEP_RIGHT_DOUBLE_QUOTATION_MARK	0x00BA
#define T_NEXTSTEP_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK	0x00BB
#define T_NEXTSTEP_HORIZONTAL_ELLIPSIS	0x00BC
#define T_NEXTSTEP_PER_MILLE_SIGN	0x00BD
#define T_NEXTSTEP_NOT_SIGN	0x00BE
#define T_NEXTSTEP_INVERTED_QUESTION_MARK	0x00BF
#define T_NEXTSTEP_SUPERSCRIPT_ONE	0x00C0
#define T_NEXTSTEP_MODIFIER_LETTER_GRAVE_ACCENT	0x00C1
#define T_NEXTSTEP_ACUTE_ACCENT	0x00C2
#define T_NEXTSTEP_MODIFIER_LETTER_CIRCUMFLEX_ACCENT	0x00C3
#define T_NEXTSTEP_SMALL_TILDE	0x00C4
#define T_NEXTSTEP_MACRON	0x00C5
#define T_NEXTSTEP_BREVE	0x00C6
#define T_NEXTSTEP_DOT_ABOVE	0x00C7
#define T_NEXTSTEP_DIAERESIS	0x00C8
#define T_NEXTSTEP_SUPERSCRIPT_TWO	0x00C9
#define T_NEXTSTEP_RING_ABOVE	0x00CA
#define T_NEXTSTEP_CEDILLA	0x00CB
#define T_NEXTSTEP_SUPERSCRIPT_THREE	0x00CC
#define T_NEXTSTEP_DOUBLE_ACUTE_ACCENT	0x00CD
#define T_NEXTSTEP_OGONEK	0x00CE
#define T_NEXTSTEP_CARON	0x00CF
#define T_NEXTSTEP_EM_DASH	0x00D0
#define T_NEXTSTEP_PLUS_MINUS_SIGN	0x00D1
#define T_NEXTSTEP_VULGAR_FRACTION_ONE_QUARTER	0x00D2
#define T_NEXTSTEP_VULGAR_FRACTION_ONE_HALF	0x00D3
#define T_NEXTSTEP_VULGAR_FRACTION_THREE_QUARTERS	0x00D4
#define T_NEXTSTEP_LATIN_SMALL_LETTER_A_WITH_GRAVE	0x00D5
#define T_NEXTSTEP_LATIN_SMALL_LETTER_A_WITH_ACUTE	0x00D6
#define T_NEXTSTEP_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX	0x00D7
#define T_NEXTSTEP_LATIN_SMALL_LETTER_A_WITH_TILDE	0x00D8
#define T_NEXTSTEP_LATIN_SMALL_LETTER_A_WITH_DIAERESIS	0x00D9
#define T_NEXTSTEP_LATIN_SMALL_LETTER_A_WITH_RING_ABOVE	0x00DA
#define T_NEXTSTEP_LATIN_SMALL_LETTER_C_WITH_CEDILLA	0x00DB
#define T_NEXTSTEP_LATIN_SMALL_LETTER_E_WITH_GRAVE	0x00DC
#define T_NEXTSTEP_LATIN_SMALL_LETTER_E_WITH_ACUTE	0x00DD
#define T_NEXTSTEP_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX	0x00DE
#define T_NEXTSTEP_LATIN_SMALL_LETTER_E_WITH_DIAERESIS	0x00DF
#define T_NEXTSTEP_LATIN_SMALL_LETTER_I_WITH_GRAVE	0x00E0
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_AE	0x00E1
#define T_NEXTSTEP_LATIN_SMALL_LETTER_I_WITH_ACUTE	0x00E2
#define T_NEXTSTEP_FEMININE_ORDINAL_INDICATOR	0x00E3
#define T_NEXTSTEP_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX	0x00E4
#define T_NEXTSTEP_LATIN_SMALL_LETTER_I_WITH_DIAERESIS	0x00E5
#define T_NEXTSTEP_LATIN_SMALL_LETTER_ETH	0x00E6
#define T_NEXTSTEP_LATIN_SMALL_LETTER_N_WITH_TILDE	0x00E7
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_L_WITH_STROKE	0x00E8
#define T_NEXTSTEP_LATIN_CAPITAL_LETTER_O_WITH_STROKE	0x00E9
#define T_NEXTSTEP_LATIN_CAPITAL_LIGATURE_OE	0x00EA
#define T_NEXTSTEP_MASCULINE_ORDINAL_INDICATOR	0x00EB
#define T_NEXTSTEP_LATIN_SMALL_LETTER_O_WITH_GRAVE	0x00EC
#define T_NEXTSTEP_LATIN_SMALL_LETTER_O_WITH_ACUTE	0x00ED
#define T_NEXTSTEP_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX	0x00EE
#define T_NEXTSTEP_LATIN_SMALL_LETTER_O_WITH_TILDE	0x00EF
#define T_NEXTSTEP_LATIN_SMALL_LETTER_O_WITH_DIAERESIS	0x00F0
#define T_NEXTSTEP_LATIN_SMALL_LETTER_AE	0x00F1
#define T_NEXTSTEP_LATIN_SMALL_LETTER_U_WITH_GRAVE	0x00F2
#define T_NEXTSTEP_LATIN_SMALL_LETTER_U_WITH_ACUTE	0x00F3
#define T_NEXTSTEP_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX	0x00F4
#define T_NEXTSTEP_LATIN_SMALL_LETTER_DOTLESS_I	0x00F5
#define T_NEXTSTEP_LATIN_SMALL_LETTER_U_WITH_DIAERESIS	0x00F6
#define T_NEXTSTEP_LATIN_SMALL_LETTER_Y_WITH_ACUTE	0x00F7
#define T_NEXTSTEP_LATIN_SMALL_LETTER_L_WITH_STROKE	0x00F8
#define T_NEXTSTEP_LATIN_SMALL_LETTER_O_WITH_STROKE	0x00F9
#define T_NEXTSTEP_LATIN_SMALL_LIGATURE_OE	0x00FA
#define T_NEXTSTEP_LATIN_SMALL_LETTER_SHARP_S	0x00FB
#define T_NEXTSTEP_LATIN_SMALL_LETTER_THORN	0x00FC
#define T_NEXTSTEP_LATIN_SMALL_LETTER_Y_WITH_DIAERESIS	0x00FD
#define T_NEXTSTEP_UNDEFINED_00FE	0x00FE
#define T_NEXTSTEP_UNDEFINED_00FF	0x00FF

/* list of all characters */
#define T_LIST_NEXTSTEP(EL) \
    EL(_NO_BREAK_SPACE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE) \
    EL(_LATIN_CAPITAL_LETTER_C_WITH_CEDILLA) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_ETH) \
    EL(_LATIN_CAPITAL_LETTER_N_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_Y_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_THORN) \
    EL(_MICRO_SIGN) \
    EL(_MULTIPLICATION_SIGN) \
    EL(_DIVISION_SIGN) \
    EL(_COPYRIGHT_SIGN) \
    EL(_INVERTED_EXCLAMATION_MARK) \
    EL(_CENT_SIGN) \
    EL(_POUND_SIGN) \
    EL(_FRACTION_SLASH) \
    EL(_YEN_SIGN) \
    EL(_LATIN_SMALL_LETTER_F_WITH_HOOK) \
    EL(_SECTION_SIGN) \
    EL(_CURRENCY_SIGN) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_LEFT_DOUBLE_QUOTATION_MARK) \
    EL(_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK) \
    EL(_SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_LATIN_SMALL_LIGATURE_FI) \
    EL(_LATIN_SMALL_LIGATURE_FL) \
    EL(_REGISTERED_SIGN) \
    EL(_EN_DASH) \
    EL(_DAGGER) \
    EL(_DOUBLE_DAGGER) \
    EL(_MIDDLE_DOT) \
    EL(_BROKEN_BAR) \
    EL(_PILCROW_SIGN) \
    EL(_BULLET) \
    EL(_SINGLE_LOW_9_QUOTATION_MARK) \
    EL(_DOUBLE_LOW_9_QUOTATION_MARK) \
    EL(_RIGHT_DOUBLE_QUOTATION_MARK) \
    EL(_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_PER_MILLE_SIGN) \
    EL(_NOT_SIGN) \
    EL(_INVERTED_QUESTION_MARK) \
    EL(_SUPERSCRIPT_ONE) \
    EL(_MODIFIER_LETTER_GRAVE_ACCENT) \
    EL(_ACUTE_ACCENT) \
    EL(_MODIFIER_LETTER_CIRCUMFLEX_ACCENT) \
    EL(_SMALL_TILDE) \
    EL(_MACRON) \
    EL(_BREVE) \
    EL(_DOT_ABOVE) \
    EL(_DIAERESIS) \
    EL(_SUPERSCRIPT_TWO) \
    EL(_RING_ABOVE) \
    EL(_CEDILLA) \
    EL(_SUPERSCRIPT_THREE) \
    EL(_DOUBLE_ACUTE_ACCENT) \
    EL(_OGONEK) \
    EL(_CARON) \
    EL(_EM_DASH) \
    EL(_PLUS_MINUS_SIGN) \
    EL(_VULGAR_FRACTION_ONE_QUARTER) \
    EL(_VULGAR_FRACTION_ONE_HALF) \
    EL(_VULGAR_FRACTION_THREE_QUARTERS) \
    EL(_LATIN_SMALL_LETTER_A_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_A_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_A_WITH_TILDE) \
    EL(_LATIN_SMALL_LETTER_A_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_A_WITH_RING_ABOVE) \
    EL(_LATIN_SMALL_LETTER_C_WITH_CEDILLA) \
    EL(_LATIN_SMALL_LETTER_E_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_E_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_E_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_I_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_AE) \
    EL(_LATIN_SMALL_LETTER_I_WITH_ACUTE) \
    EL(_FEMININE_ORDINAL_INDICATOR) \
    EL(_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_I_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_ETH) \
    EL(_LATIN_SMALL_LETTER_N_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_L_WITH_STROKE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_STROKE) \
    EL(_LATIN_CAPITAL_LIGATURE_OE) \
    EL(_MASCULINE_ORDINAL_INDICATOR) \
    EL(_LATIN_SMALL_LETTER_O_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_O_WITH_TILDE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_AE) \
    EL(_LATIN_SMALL_LETTER_U_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_U_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_DOTLESS_I) \
    EL(_LATIN_SMALL_LETTER_U_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_Y_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_L_WITH_STROKE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_STROKE) \
    EL(_LATIN_SMALL_LIGATURE_OE) \
    EL(_LATIN_SMALL_LETTER_SHARP_S) \
    EL(_LATIN_SMALL_LETTER_THORN) \
    EL(_LATIN_SMALL_LETTER_Y_WITH_DIAERESIS)

/* list of all characters NOT IDENTICALLY MAPPED to UTF-16 */
#define T_NLIST_NEXTSTEP(EL) \
    EL(_NO_BREAK_SPACE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE) \
    EL(_LATIN_CAPITAL_LETTER_C_WITH_CEDILLA) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_ETH) \
    EL(_LATIN_CAPITAL_LETTER_N_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX) \
    EL(_LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS) \
    EL(_LATIN_CAPITAL_LETTER_Y_WITH_ACUTE) \
    EL(_LATIN_CAPITAL_LETTER_THORN) \
    EL(_MICRO_SIGN) \
    EL(_MULTIPLICATION_SIGN) \
    EL(_DIVISION_SIGN) \
    EL(_COPYRIGHT_SIGN) \
    EL(_FRACTION_SLASH) \
    EL(_LATIN_SMALL_LETTER_F_WITH_HOOK) \
    EL(_CURRENCY_SIGN) \
    EL(_RIGHT_SINGLE_QUOTATION_MARK) \
    EL(_LEFT_DOUBLE_QUOTATION_MARK) \
    EL(_SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK) \
    EL(_LATIN_SMALL_LIGATURE_FI) \
    EL(_LATIN_SMALL_LIGATURE_FL) \
    EL(_REGISTERED_SIGN) \
    EL(_EN_DASH) \
    EL(_DAGGER) \
    EL(_DOUBLE_DAGGER) \
    EL(_MIDDLE_DOT) \
    EL(_BROKEN_BAR) \
    EL(_BULLET) \
    EL(_SINGLE_LOW_9_QUOTATION_MARK) \
    EL(_DOUBLE_LOW_9_QUOTATION_MARK) \
    EL(_RIGHT_DOUBLE_QUOTATION_MARK) \
    EL(_HORIZONTAL_ELLIPSIS) \
    EL(_PER_MILLE_SIGN) \
    EL(_NOT_SIGN) \
    EL(_SUPERSCRIPT_ONE) \
    EL(_MODIFIER_LETTER_GRAVE_ACCENT) \
    EL(_ACUTE_ACCENT) \
    EL(_MODIFIER_LETTER_CIRCUMFLEX_ACCENT) \
    EL(_SMALL_TILDE) \
    EL(_MACRON) \
    EL(_BREVE) \
    EL(_DOT_ABOVE) \
    EL(_DIAERESIS) \
    EL(_SUPERSCRIPT_TWO) \
    EL(_RING_ABOVE) \
    EL(_CEDILLA) \
    EL(_SUPERSCRIPT_THREE) \
    EL(_DOUBLE_ACUTE_ACCENT) \
    EL(_OGONEK) \
    EL(_CARON) \
    EL(_EM_DASH) \
    EL(_PLUS_MINUS_SIGN) \
    EL(_VULGAR_FRACTION_ONE_QUARTER) \
    EL(_VULGAR_FRACTION_ONE_HALF) \
    EL(_VULGAR_FRACTION_THREE_QUARTERS) \
    EL(_LATIN_SMALL_LETTER_A_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_A_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_A_WITH_TILDE) \
    EL(_LATIN_SMALL_LETTER_A_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_A_WITH_RING_ABOVE) \
    EL(_LATIN_SMALL_LETTER_C_WITH_CEDILLA) \
    EL(_LATIN_SMALL_LETTER_E_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_E_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_E_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_I_WITH_GRAVE) \
    EL(_LATIN_CAPITAL_LETTER_AE) \
    EL(_LATIN_SMALL_LETTER_I_WITH_ACUTE) \
    EL(_FEMININE_ORDINAL_INDICATOR) \
    EL(_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_I_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_ETH) \
    EL(_LATIN_SMALL_LETTER_N_WITH_TILDE) \
    EL(_LATIN_CAPITAL_LETTER_L_WITH_STROKE) \
    EL(_LATIN_CAPITAL_LETTER_O_WITH_STROKE) \
    EL(_LATIN_CAPITAL_LIGATURE_OE) \
    EL(_MASCULINE_ORDINAL_INDICATOR) \
    EL(_LATIN_SMALL_LETTER_O_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_O_WITH_TILDE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_AE) \
    EL(_LATIN_SMALL_LETTER_U_WITH_GRAVE) \
    EL(_LATIN_SMALL_LETTER_U_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX) \
    EL(_LATIN_SMALL_LETTER_DOTLESS_I) \
    EL(_LATIN_SMALL_LETTER_U_WITH_DIAERESIS) \
    EL(_LATIN_SMALL_LETTER_Y_WITH_ACUTE) \
    EL(_LATIN_SMALL_LETTER_L_WITH_STROKE) \
    EL(_LATIN_SMALL_LETTER_O_WITH_STROKE) \
    EL(_LATIN_SMALL_LIGATURE_OE) \
    EL(_LATIN_SMALL_LETTER_SHARP_S) \
    EL(_LATIN_SMALL_LETTER_THORN) \
    EL(_LATIN_SMALL_LETTER_Y_WITH_DIAERESIS)


#endif /* _TUTF_NEXTSTEP_H */
