
#ifndef _TUTF_VERSION_H
#define _TUTF_VERSION_H

#define TUTF_PROTOCOL_VERSION_MAJOR 0
#define TUTF_PROTOCOL_VERSION_MINOR 0
#define TUTF_PROTOCOL_VERSION_PATCH 2
#define TUTF_PROTOCOL_VERSION       ((TUTF_PROTOCOL_VERSION_MAJOR<<16)|(TUTF_PROTOCOL_VERSION_MINOR<<8)|TUTF_PROTOCOL_VERSION_PATCH)
#define TUTF_PROTOCOL_VERSION_STR   TT_STR(TUTF_PROTOCOL_VERSION_MAJOR) "." TT_STR(TUTF_PROTOCOL_VERSION_MINOR) "." TT_STR(TUTF_PROTOCOL_VERSION_PATCH)

#define TTVER_MAJOR(n) ((n)>>16)
#define TTVER_MINOR(n) (((n)>>8) & 0xFF)
#define TTVER_PATCH(n) ((n) & 0xFF)
#define TTVER_BUILD(M, m, p) (((M)<<16)|((m)<<8)|(p))

#endif _TUTF_VERSION_H
