
#ifndef _TT_COMPILER_H
#define _TT_COMPILER_H

#define TT_CAT(a,b)		TW__CAT(a,b)
#define TT_STR(a)		TW__STR(a)
#define TT_CONST		TW_CONST
#define TT_INLINE		TW_INLINE
#define TT_VOLATILE		TW_VOLATILE
#define TT_FN_ATTR_CONST	TW_FN_ATTR_CONST
#define TT_TYPE_ATTR_PACKED	TW_TYPE_ATTR_PACKED

#endif /* _TT_COMPILER_H */

