




/* This file was automatically generated from m4/TTdefs.m4, do not edit! */


/*
 *  TTdefsm4.h  --  public header for libTT types declarations
 *
 *  Copyright (C) 2001 by Massimiliano Ghilardi
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 */

#ifndef _TT_DEFSM4_H
#define _TT_DEFSM4_H





/*
 *  m4/m4_TTtypes.m4  --  header for libTT objects inheritance
 *                        used as template for a lot of autogenerated files.
 *
 *  Copyright (C) 2001 by Massimiliano Ghilardi
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 */

/* ttobj: The superclass of all objects */



/* ttvisible: The superclass of all visible objects */




/* ttnative: class representing all server visible objects not created by us */



/* ttwidget: The superclass of all window-like visible containers */



/* ttlabel: A simple text label */





















/* ttframe: A toplevel window */









/* ttscroller: A scrollable container. You can put any ttwidget inside it */



/* ttmenuitem: Represents a single line in a menu */



/* ttcheckmenuitem: A checkable line in a menu. */



/* ttradiomenuitem: A radio line in a menu. */



/* ttmenuwindow: Represents a menu window */



/* ttmenu: Represents an entry in a menu, pointing to a ttmenuwindow */



/* ttmenubar: A complete menu bar. */



/* ttanytext: The superclass of all text-only widgets */



/* tttextfield: A one-line user-editable text-only widget */



/* tttextarea: A multi-line user-editable text-only widget */



/* tttheme: The look-n-feel of the application */



/* ttapplication: The topmost object */














    
    
     
    
    
    
    
    
    
       
    
     
    
    
    
    
    
         
        
    
     
        
      
    
       
    
    
    
     
    











#define TT_LIST(el) \
el(ttobj) el(ttvisible) el(ttnative) el(ttwidget) el(ttlabel) el(ttanybutton) el(ttbutton) el(ttcheckbutton) el(ttradiobutton) el(ttbuttongroup) el(ttwindow) el(ttframe) el(ttscrollbar) el(ttslider) el(ttscroller) el(ttmenuitem) el(ttcheckmenuitem) el(ttradiomenuitem) el(ttmenuwindow) el(ttmenu) el(ttmenubar) el(ttanytext) el(tttextfield) el(tttextarea) el(tttheme) el(ttapplication)

#define TT_NLIST(el) \
el(ttvisible) el(ttnative) el(ttwidget) el(ttlabel) el(ttanybutton) el(ttbutton) el(ttcheckbutton) el(ttradiobutton) el(ttbuttongroup) el(ttwindow) el(ttframe) el(ttscrollbar) el(ttslider) el(ttscroller) el(ttmenuitem) el(ttcheckmenuitem) el(ttradiomenuitem) el(ttmenuwindow) el(ttmenu) el(ttmenubar) el(ttanytext) el(tttextfield) el(tttextarea) el(tttheme) el(ttapplication)

/* typedefs for objects structures */


typedef struct s_ttobj	* ttobj; 
typedef struct s_ttvisible	* ttvisible; 
typedef struct s_ttnative	* ttnative; 
typedef struct s_ttwidget	* ttwidget; 
typedef struct s_ttlabel	* ttlabel; 
typedef struct s_ttanybutton	* ttanybutton; 
typedef struct s_ttbutton	* ttbutton; 
typedef struct s_ttcheckbutton	* ttcheckbutton; 
typedef struct s_ttradiobutton	* ttradiobutton; 
typedef struct s_ttbuttongroup	* ttbuttongroup; 
typedef struct s_ttwindow	* ttwindow; 
typedef struct s_ttframe	* ttframe; 
typedef struct s_ttscrollbar	* ttscrollbar; 
typedef struct s_ttslider	* ttslider; 
typedef struct s_ttscroller	* ttscroller; 
typedef struct s_ttmenuitem	* ttmenuitem; 
typedef struct s_ttcheckmenuitem	* ttcheckmenuitem; 
typedef struct s_ttradiomenuitem	* ttradiomenuitem; 
typedef struct s_ttmenuwindow	* ttmenuwindow; 
typedef struct s_ttmenu	* ttmenu; 
typedef struct s_ttmenubar	* ttmenubar; 
typedef struct s_ttanytext	* ttanytext; 
typedef struct s_tttextfield	* tttextfield; 
typedef struct s_tttextarea	* tttextarea; 
typedef struct s_tttheme	* tttheme; 
typedef struct s_ttapplication	* ttapplication;


/* typedefs for methods structures */


typedef struct s_ttfn_ttobj	* ttfn_ttobj; 
typedef struct s_ttfn_ttvisible	* ttfn_ttvisible; 
typedef struct s_ttfn_ttnative	* ttfn_ttnative; 
typedef struct s_ttfn_ttwidget	* ttfn_ttwidget; 
typedef struct s_ttfn_ttlabel	* ttfn_ttlabel; 
typedef struct s_ttfn_ttanybutton	* ttfn_ttanybutton; 
typedef struct s_ttfn_ttbutton	* ttfn_ttbutton; 
typedef struct s_ttfn_ttcheckbutton	* ttfn_ttcheckbutton; 
typedef struct s_ttfn_ttradiobutton	* ttfn_ttradiobutton; 
typedef struct s_ttfn_ttbuttongroup	* ttfn_ttbuttongroup; 
typedef struct s_ttfn_ttwindow	* ttfn_ttwindow; 
typedef struct s_ttfn_ttframe	* ttfn_ttframe; 
typedef struct s_ttfn_ttscrollbar	* ttfn_ttscrollbar; 
typedef struct s_ttfn_ttslider	* ttfn_ttslider; 
typedef struct s_ttfn_ttscroller	* ttfn_ttscroller; 
typedef struct s_ttfn_ttmenuitem	* ttfn_ttmenuitem; 
typedef struct s_ttfn_ttcheckmenuitem	* ttfn_ttcheckmenuitem; 
typedef struct s_ttfn_ttradiomenuitem	* ttfn_ttradiomenuitem; 
typedef struct s_ttfn_ttmenuwindow	* ttfn_ttmenuwindow; 
typedef struct s_ttfn_ttmenu	* ttfn_ttmenu; 
typedef struct s_ttfn_ttmenubar	* ttfn_ttmenubar; 
typedef struct s_ttfn_ttanytext	* ttfn_ttanytext; 
typedef struct s_ttfn_tttextfield	* ttfn_tttextfield; 
typedef struct s_ttfn_tttextarea	* ttfn_tttextarea; 
typedef struct s_ttfn_tttheme	* ttfn_tttheme; 
typedef struct s_ttfn_ttapplication	* ttfn_ttapplication;


/* global methods structures */


extern ttfn_ttobj	TTFN_ttobj; 
extern ttfn_ttvisible	TTFN_ttvisible; 
extern ttfn_ttnative	TTFN_ttnative; 
extern ttfn_ttwidget	TTFN_ttwidget; 
extern ttfn_ttlabel	TTFN_ttlabel; 
extern ttfn_ttanybutton	TTFN_ttanybutton; 
extern ttfn_ttbutton	TTFN_ttbutton; 
extern ttfn_ttcheckbutton	TTFN_ttcheckbutton; 
extern ttfn_ttradiobutton	TTFN_ttradiobutton; 
extern ttfn_ttbuttongroup	TTFN_ttbuttongroup; 
extern ttfn_ttwindow	TTFN_ttwindow; 
extern ttfn_ttframe	TTFN_ttframe; 
extern ttfn_ttscrollbar	TTFN_ttscrollbar; 
extern ttfn_ttslider	TTFN_ttslider; 
extern ttfn_ttscroller	TTFN_ttscroller; 
extern ttfn_ttmenuitem	TTFN_ttmenuitem; 
extern ttfn_ttcheckmenuitem	TTFN_ttcheckmenuitem; 
extern ttfn_ttradiomenuitem	TTFN_ttradiomenuitem; 
extern ttfn_ttmenuwindow	TTFN_ttmenuwindow; 
extern ttfn_ttmenu	TTFN_ttmenu; 
extern ttfn_ttmenubar	TTFN_ttmenubar; 
extern ttfn_ttanytext	TTFN_ttanytext; 
extern ttfn_tttextfield	TTFN_tttextfield; 
extern ttfn_tttextarea	TTFN_tttextarea; 
extern ttfn_tttheme	TTFN_tttheme; 
extern ttfn_ttapplication	TTFN_ttapplication;


/* #defines for objects hierarchy */




    
    
     
#define TTsuper_ttvisible	ttobj
    
    
    
    
    
    
     
#define TTsuper_ttnative	ttvisible 
#define TTsuper_ttwidget	ttvisible 
#define TTsuper_ttlabel	ttwidget
    
     
#define TTsuper_ttanybutton	ttwidget
    
    
    
    
    
     
#define TTsuper_ttbutton	ttanybutton 
#define TTsuper_ttcheckbutton	ttbutton 
#define TTsuper_ttradiobutton	ttcheckbutton 
#define TTsuper_ttbuttongroup	ttobj 
#define TTsuper_ttwindow	ttwidget
     
#define TTsuper_ttframe	ttwindow 
#define TTsuper_ttscrollbar	ttanybutton 
#define TTsuper_ttslider	ttanybutton 
#define TTsuper_ttscroller	ttwindow
    
     
#define TTsuper_ttmenuitem	ttvisible
     
#define TTsuper_ttcheckmenuitem	ttmenuitem 
#define TTsuper_ttradiomenuitem	ttcheckmenuitem 
#define TTsuper_ttmenuwindow	ttwindow 
#define TTsuper_ttmenu	ttmenuitem
     
#define TTsuper_ttmenubar	ttvisible 
#define TTsuper_ttanytext	ttwindow
    
     
#define TTsuper_tttextfield	ttanytext 
#define TTsuper_tttextarea	tttextfield 
#define TTsuper_tttheme	ttobj
    
    
    
     
#define TTsuper_ttapplication	ttobj
    




/* costructors */


#define TTNew_ttobj()	TT_NEW(ttobj) 
#define TTNew_ttvisible()	TT_NEW(ttvisible) 
#define TTNew_ttnative()	TT_NEW(ttnative) 
#define TTNew_ttwidget()	TT_NEW(ttwidget) 
#define TTNew_ttlabel()	TT_NEW(ttlabel) 
#define TTNew_ttanybutton()	TT_NEW(ttanybutton) 
#define TTNew_ttbutton()	TT_NEW(ttbutton) 
#define TTNew_ttcheckbutton()	TT_NEW(ttcheckbutton) 
#define TTNew_ttradiobutton()	TT_NEW(ttradiobutton) 
#define TTNew_ttbuttongroup()	TT_NEW(ttbuttongroup) 
#define TTNew_ttwindow()	TT_NEW(ttwindow) 
#define TTNew_ttframe()	TT_NEW(ttframe) 
#define TTNew_ttscrollbar()	TT_NEW(ttscrollbar) 
#define TTNew_ttslider()	TT_NEW(ttslider) 
#define TTNew_ttscroller()	TT_NEW(ttscroller) 
#define TTNew_ttmenuitem()	TT_NEW(ttmenuitem) 
#define TTNew_ttcheckmenuitem()	TT_NEW(ttcheckmenuitem) 
#define TTNew_ttradiomenuitem()	TT_NEW(ttradiomenuitem) 
#define TTNew_ttmenuwindow()	TT_NEW(ttmenuwindow) 
#define TTNew_ttmenu()	TT_NEW(ttmenu) 
#define TTNew_ttmenubar()	TT_NEW(ttmenubar) 
#define TTNew_ttanytext()	TT_NEW(ttanytext) 
#define TTNew_tttextfield()	TT_NEW(tttextfield) 
#define TTNew_tttextarea()	TT_NEW(tttextarea) 
#define TTNew_tttheme()	TT_NEW(tttheme) 
#define TTNew_ttapplication()	TT_NEW(ttapplication)


/* and destructors */


#define TTDel_ttobj(o)	TT_DEL(o) 
#define TTDel_ttvisible(o)	TT_DEL(o) 
#define TTDel_ttnative(o)	TT_DEL(o) 
#define TTDel_ttwidget(o)	TT_DEL(o) 
#define TTDel_ttlabel(o)	TT_DEL(o) 
#define TTDel_ttanybutton(o)	TT_DEL(o) 
#define TTDel_ttbutton(o)	TT_DEL(o) 
#define TTDel_ttcheckbutton(o)	TT_DEL(o) 
#define TTDel_ttradiobutton(o)	TT_DEL(o) 
#define TTDel_ttbuttongroup(o)	TT_DEL(o) 
#define TTDel_ttwindow(o)	TT_DEL(o) 
#define TTDel_ttframe(o)	TT_DEL(o) 
#define TTDel_ttscrollbar(o)	TT_DEL(o) 
#define TTDel_ttslider(o)	TT_DEL(o) 
#define TTDel_ttscroller(o)	TT_DEL(o) 
#define TTDel_ttmenuitem(o)	TT_DEL(o) 
#define TTDel_ttcheckmenuitem(o)	TT_DEL(o) 
#define TTDel_ttradiomenuitem(o)	TT_DEL(o) 
#define TTDel_ttmenuwindow(o)	TT_DEL(o) 
#define TTDel_ttmenu(o)	TT_DEL(o) 
#define TTDel_ttmenubar(o)	TT_DEL(o) 
#define TTDel_ttanytext(o)	TT_DEL(o) 
#define TTDel_tttextfield(o)	TT_DEL(o) 
#define TTDel_tttextarea(o)	TT_DEL(o) 
#define TTDel_tttheme(o)	TT_DEL(o) 
#define TTDel_ttapplication(o)	TT_DEL(o)


/* public and exported methods */















/* ttobj public and exported methods */
    
    
    
    
    
    
void TTSetUserData_ttobj(ttobj,void *);
    
void * TTGetUserData_ttobj(ttobj); 

/* ttvisible public and exported methods */
    
void TTAdd_ttvisible(ttvisible,ttvisible);
    
void TTAddTo_ttvisible(ttvisible,ttvisible);
    
void TTRemove_ttvisible(ttvisible);
    
void TTSetVisible_ttvisible(ttvisible,byte);
    
void TTSetTheme_ttvisible(ttvisible,tttheme);
    
void TTRepaint_ttvisible(ttvisible,dat,dat,dat,dat);
    
ttvisible TTGetPrev_ttvisible(ttvisible);
    
ttvisible TTGetNext_ttvisible(ttvisible);
    
ttvisible TTGetParent_ttvisible(ttvisible);
    
ttvisible TTGetFirstChild_ttvisible(ttvisible);
    
ttvisible TTGetLastChild_ttvisible(ttvisible);
    
tttheme TTGetTheme_ttvisible(ttvisible); 

/* ttnative public and exported methods */
    
ttnative TTGetFirstScreen_ttnative(); 

/* ttwidget public and exported methods */ 

/* ttlabel public and exported methods */
    
byte TTSetText_ttlabel(ttlabel,byte TT_CONST *);
    
hwfont TT_CONST * TTGetText_ttlabel(ttlabel); 

/* ttanybutton public and exported methods */
    
void TTMouseEvent_ttanybutton(ttanybutton,udat,udat,dat,dat);
    
byte TTSetText_ttanybutton(ttanybutton,hwfont TT_CONST *,dat,dat,dat);
    
dat TTGetTextWidth_ttanybutton(ttanybutton);
    
dat TTGetTextHeight_ttanybutton(ttanybutton);
    
hwfont TT_CONST * TTGetText_ttanybutton(ttanybutton); 

/* ttbutton public and exported methods */
    
void TTSetPressed_ttbutton(ttbutton);
    
byte TTIsPressed_ttbutton(ttbutton); 

/* ttcheckbutton public and exported methods */ 

/* ttradiobutton public and exported methods */ 

/* ttbuttongroup public and exported methods */ 

/* ttwindow public and exported methods */ 

/* ttframe public and exported methods */ 

/* ttscrollbar public and exported methods */ 

/* ttslider public and exported methods */ 

/* ttscroller public and exported methods */ 

/* ttmenuitem public and exported methods */ 

/* ttcheckmenuitem public and exported methods */ 

/* ttradiomenuitem public and exported methods */ 

/* ttmenuwindow public and exported methods */ 

/* ttmenu public and exported methods */
    
ttmenuwindow TTGetMenuWindow_ttmenu(ttmenu); 

/* ttmenubar public and exported methods */ 

/* ttanytext public and exported methods */ 

/* tttextfield public and exported methods */ 

/* tttextarea public and exported methods */ 

/* tttheme public and exported methods */
     

/* ttapplication public and exported methods */







/* methods inherited by derivate classes */
/* set #defines pointing to the most primitive class implementing the method */







/* methods inherited by ttvisible */
    
    
    
    
    
    
#define TTSetUserData_ttvisible(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttvisible(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1))) 

/* methods inherited by ttnative */
    
    
    
    
    
    
#define TTSetUserData_ttnative(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttnative(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttnative(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttnative(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttnative(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttnative(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttnative(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttnative(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttnative(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttnative(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttnative(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttnative(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttnative(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttnative(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttwidget */
    
    
    
    
    
    
#define TTSetUserData_ttwidget(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttwidget(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttwidget(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttwidget(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttwidget(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttwidget(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttwidget(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttwidget(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttwidget(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttwidget(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttwidget(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttwidget(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttwidget(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttwidget(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttlabel */
    
    
    
    
    
    
#define TTSetUserData_ttlabel(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttlabel(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttlabel(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttlabel(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttlabel(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttlabel(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttlabel(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttlabel(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttlabel(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttlabel(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttlabel(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttlabel(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttlabel(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttlabel(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttanybutton */
    
    
    
    
    
    
#define TTSetUserData_ttanybutton(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttanybutton(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttanybutton(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttanybutton(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttanybutton(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttanybutton(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttanybutton(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttanybutton(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttanybutton(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttanybutton(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttanybutton(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttanybutton(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttanybutton(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttanybutton(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttbutton */
    
    
    
    
    
    
#define TTSetUserData_ttbutton(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttbutton(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttbutton(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttbutton(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttbutton(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttbutton(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttbutton(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttbutton(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttbutton(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttbutton(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttbutton(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttbutton(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttbutton(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttbutton(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1)))
    
#define TTMouseEvent_ttbutton(a5, a4, a3, a2, a1) ((void) TTMouseEvent_ttanybutton(((ttanybutton)a5), ((udat)a4), ((udat)a3), ((dat)a2), ((dat)a1)))
    
#define TTSetText_ttbutton(a5, a4, a3, a2, a1) ((byte) TTSetText_ttanybutton(((ttanybutton)a5), ((hwfont TT_CONST *)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetTextWidth_ttbutton(a1) ((dat) TTGetTextWidth_ttanybutton(((ttanybutton)a1)))
    
#define TTGetTextHeight_ttbutton(a1) ((dat) TTGetTextHeight_ttanybutton(((ttanybutton)a1)))
    
#define TTGetText_ttbutton(a1) ((hwfont TT_CONST *) TTGetText_ttanybutton(((ttanybutton)a1))) 

/* methods inherited by ttcheckbutton */
    
    
    
    
    
    
#define TTSetUserData_ttcheckbutton(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttcheckbutton(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttcheckbutton(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttcheckbutton(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttcheckbutton(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttcheckbutton(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttcheckbutton(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttcheckbutton(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttcheckbutton(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttcheckbutton(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttcheckbutton(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttcheckbutton(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttcheckbutton(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttcheckbutton(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1)))
    
#define TTMouseEvent_ttcheckbutton(a5, a4, a3, a2, a1) ((void) TTMouseEvent_ttanybutton(((ttanybutton)a5), ((udat)a4), ((udat)a3), ((dat)a2), ((dat)a1)))
    
#define TTSetText_ttcheckbutton(a5, a4, a3, a2, a1) ((byte) TTSetText_ttanybutton(((ttanybutton)a5), ((hwfont TT_CONST *)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetTextWidth_ttcheckbutton(a1) ((dat) TTGetTextWidth_ttanybutton(((ttanybutton)a1)))
    
#define TTGetTextHeight_ttcheckbutton(a1) ((dat) TTGetTextHeight_ttanybutton(((ttanybutton)a1)))
    
#define TTGetText_ttcheckbutton(a1) ((hwfont TT_CONST *) TTGetText_ttanybutton(((ttanybutton)a1)))
    
#define TTSetPressed_ttcheckbutton(a2, a1) ((void) TTSetPressed_ttbutton(((ttbutton)a2), (()a1)))
    
#define TTIsPressed_ttcheckbutton(a1) ((byte) TTIsPressed_ttbutton(((ttbutton)a1))) 

/* methods inherited by ttradiobutton */
    
    
    
    
    
    
#define TTSetUserData_ttradiobutton(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttradiobutton(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttradiobutton(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttradiobutton(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttradiobutton(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttradiobutton(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttradiobutton(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttradiobutton(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttradiobutton(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttradiobutton(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttradiobutton(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttradiobutton(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttradiobutton(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttradiobutton(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1)))
    
#define TTMouseEvent_ttradiobutton(a5, a4, a3, a2, a1) ((void) TTMouseEvent_ttanybutton(((ttanybutton)a5), ((udat)a4), ((udat)a3), ((dat)a2), ((dat)a1)))
    
#define TTSetText_ttradiobutton(a5, a4, a3, a2, a1) ((byte) TTSetText_ttanybutton(((ttanybutton)a5), ((hwfont TT_CONST *)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetTextWidth_ttradiobutton(a1) ((dat) TTGetTextWidth_ttanybutton(((ttanybutton)a1)))
    
#define TTGetTextHeight_ttradiobutton(a1) ((dat) TTGetTextHeight_ttanybutton(((ttanybutton)a1)))
    
#define TTGetText_ttradiobutton(a1) ((hwfont TT_CONST *) TTGetText_ttanybutton(((ttanybutton)a1)))
    
#define TTSetPressed_ttradiobutton(a2, a1) ((void) TTSetPressed_ttbutton(((ttbutton)a2), (()a1)))
    
#define TTIsPressed_ttradiobutton(a1) ((byte) TTIsPressed_ttbutton(((ttbutton)a1))) 

/* methods inherited by ttbuttongroup */
    
    
    
    
    
    
#define TTSetUserData_ttbuttongroup(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttbuttongroup(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1))) 

/* methods inherited by ttwindow */
    
    
    
    
    
    
#define TTSetUserData_ttwindow(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttwindow(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttwindow(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttwindow(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttwindow(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttwindow(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttwindow(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttwindow(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttwindow(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttwindow(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttwindow(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttwindow(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttwindow(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttwindow(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttframe */
    
    
    
    
    
    
#define TTSetUserData_ttframe(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttframe(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttframe(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttframe(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttframe(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttframe(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttframe(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttframe(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttframe(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttframe(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttframe(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttframe(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttframe(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttframe(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttscrollbar */
    
    
    
    
    
    
#define TTSetUserData_ttscrollbar(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttscrollbar(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttscrollbar(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttscrollbar(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttscrollbar(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttscrollbar(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttscrollbar(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttscrollbar(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttscrollbar(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttscrollbar(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttscrollbar(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttscrollbar(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttscrollbar(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttscrollbar(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1)))
    
#define TTMouseEvent_ttscrollbar(a5, a4, a3, a2, a1) ((void) TTMouseEvent_ttanybutton(((ttanybutton)a5), ((udat)a4), ((udat)a3), ((dat)a2), ((dat)a1)))
    
#define TTSetText_ttscrollbar(a5, a4, a3, a2, a1) ((byte) TTSetText_ttanybutton(((ttanybutton)a5), ((hwfont TT_CONST *)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetTextWidth_ttscrollbar(a1) ((dat) TTGetTextWidth_ttanybutton(((ttanybutton)a1)))
    
#define TTGetTextHeight_ttscrollbar(a1) ((dat) TTGetTextHeight_ttanybutton(((ttanybutton)a1)))
    
#define TTGetText_ttscrollbar(a1) ((hwfont TT_CONST *) TTGetText_ttanybutton(((ttanybutton)a1))) 

/* methods inherited by ttslider */
    
    
    
    
    
    
#define TTSetUserData_ttslider(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttslider(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttslider(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttslider(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttslider(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttslider(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttslider(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttslider(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttslider(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttslider(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttslider(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttslider(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttslider(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttslider(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1)))
    
#define TTMouseEvent_ttslider(a5, a4, a3, a2, a1) ((void) TTMouseEvent_ttanybutton(((ttanybutton)a5), ((udat)a4), ((udat)a3), ((dat)a2), ((dat)a1)))
    
#define TTSetText_ttslider(a5, a4, a3, a2, a1) ((byte) TTSetText_ttanybutton(((ttanybutton)a5), ((hwfont TT_CONST *)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetTextWidth_ttslider(a1) ((dat) TTGetTextWidth_ttanybutton(((ttanybutton)a1)))
    
#define TTGetTextHeight_ttslider(a1) ((dat) TTGetTextHeight_ttanybutton(((ttanybutton)a1)))
    
#define TTGetText_ttslider(a1) ((hwfont TT_CONST *) TTGetText_ttanybutton(((ttanybutton)a1))) 

/* methods inherited by ttscroller */
    
    
    
    
    
    
#define TTSetUserData_ttscroller(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttscroller(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttscroller(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttscroller(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttscroller(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttscroller(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttscroller(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttscroller(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttscroller(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttscroller(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttscroller(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttscroller(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttscroller(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttscroller(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttmenuitem */
    
    
    
    
    
    
#define TTSetUserData_ttmenuitem(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttmenuitem(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttmenuitem(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttmenuitem(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttmenuitem(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttmenuitem(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttmenuitem(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttmenuitem(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttmenuitem(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttmenuitem(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttmenuitem(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttmenuitem(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttmenuitem(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttmenuitem(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttcheckmenuitem */
    
    
    
    
    
    
#define TTSetUserData_ttcheckmenuitem(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttcheckmenuitem(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttcheckmenuitem(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttcheckmenuitem(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttcheckmenuitem(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttcheckmenuitem(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttcheckmenuitem(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttcheckmenuitem(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttcheckmenuitem(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttcheckmenuitem(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttcheckmenuitem(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttcheckmenuitem(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttcheckmenuitem(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttcheckmenuitem(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttradiomenuitem */
    
    
    
    
    
    
#define TTSetUserData_ttradiomenuitem(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttradiomenuitem(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttradiomenuitem(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttradiomenuitem(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttradiomenuitem(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttradiomenuitem(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttradiomenuitem(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttradiomenuitem(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttradiomenuitem(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttradiomenuitem(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttradiomenuitem(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttradiomenuitem(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttradiomenuitem(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttradiomenuitem(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttmenuwindow */
    
    
    
    
    
    
#define TTSetUserData_ttmenuwindow(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttmenuwindow(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttmenuwindow(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttmenuwindow(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttmenuwindow(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttmenuwindow(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttmenuwindow(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttmenuwindow(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttmenuwindow(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttmenuwindow(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttmenuwindow(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttmenuwindow(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttmenuwindow(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttmenuwindow(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttmenu */
    
    
    
    
    
    
#define TTSetUserData_ttmenu(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttmenu(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttmenu(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttmenu(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttmenu(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttmenu(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttmenu(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttmenu(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttmenu(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttmenu(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttmenu(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttmenu(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttmenu(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttmenu(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttmenubar */
    
    
    
    
    
    
#define TTSetUserData_ttmenubar(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttmenubar(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttmenubar(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttmenubar(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttmenubar(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttmenubar(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttmenubar(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttmenubar(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttmenubar(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttmenubar(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttmenubar(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttmenubar(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttmenubar(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttmenubar(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by ttanytext */
    
    
    
    
    
    
#define TTSetUserData_ttanytext(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttanytext(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_ttanytext(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_ttanytext(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_ttanytext(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_ttanytext(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_ttanytext(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_ttanytext(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_ttanytext(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_ttanytext(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_ttanytext(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_ttanytext(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_ttanytext(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_ttanytext(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by tttextfield */
    
    
    
    
    
    
#define TTSetUserData_tttextfield(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_tttextfield(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_tttextfield(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_tttextfield(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_tttextfield(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_tttextfield(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_tttextfield(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_tttextfield(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_tttextfield(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_tttextfield(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_tttextfield(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_tttextfield(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_tttextfield(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_tttextfield(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by tttextarea */
    
    
    
    
    
    
#define TTSetUserData_tttextarea(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_tttextarea(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))
    
#define TTAdd_tttextarea(a2, a1) ((void) TTAdd_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTAddTo_tttextarea(a2, a1) ((void) TTAddTo_ttvisible(((ttvisible)a2), ((ttvisible)a1)))
    
#define TTRemove_tttextarea(a1) ((void) TTRemove_ttvisible(((ttvisible)a1)))
    
#define TTSetVisible_tttextarea(a2, a1) ((void) TTSetVisible_ttvisible(((ttvisible)a2), ((byte)a1)))
    
#define TTSetTheme_tttextarea(a2, a1) ((void) TTSetTheme_ttvisible(((ttvisible)a2), ((tttheme)a1)))
    
#define TTRepaint_tttextarea(a5, a4, a3, a2, a1) ((void) TTRepaint_ttvisible(((ttvisible)a5), ((dat)a4), ((dat)a3), ((dat)a2), ((dat)a1)))
    
#define TTGetPrev_tttextarea(a1) ((ttvisible) TTGetPrev_ttvisible(((ttvisible)a1)))
    
#define TTGetNext_tttextarea(a1) ((ttvisible) TTGetNext_ttvisible(((ttvisible)a1)))
    
#define TTGetParent_tttextarea(a1) ((ttvisible) TTGetParent_ttvisible(((ttvisible)a1)))
    
#define TTGetFirstChild_tttextarea(a1) ((ttvisible) TTGetFirstChild_ttvisible(((ttvisible)a1)))
    
#define TTGetLastChild_tttextarea(a1) ((ttvisible) TTGetLastChild_ttvisible(((ttvisible)a1)))
    
#define TTGetTheme_tttextarea(a1) ((tttheme) TTGetTheme_ttvisible(((ttvisible)a1))) 

/* methods inherited by tttheme */
    
    
    
    
    
    
#define TTSetUserData_tttheme(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_tttheme(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1))) 

/* methods inherited by ttapplication */
    
    
    
    
    
    
#define TTSetUserData_ttapplication(a2, a1) ((void) TTSetUserData_ttobj(((ttobj)a2), ((void *)a1)))
    
#define TTGetUserData_ttapplication(a1) ((void *) TTGetUserData_ttobj(((ttobj)a1)))






#endif /* _TT_DEFSM4_H */

