#!/bin/bash

ARGS="$@"
HW=
DPY=

while [ "$1" ]; do
  case "$1" in
    -nohw|-hw=* )
      HW="$1";
      ;;
    -twin@* )
      DPY="${1:5}";
      ;;
    -* )
      ;;
    *:[0-9a-fA-F]* )
      DPY="$1";
      ;;
  esac
  shift
done

if [ -z "$HW" ]; then
  if [ "$DISPLAY" ]; then
    ARGS="$ARGS -hw=X,font=9x19"
  elif [ "$TWDISPLAY" ]; then
    ARGS="$ARGS -hw=twin@$TWDISPLAY"
  else
    ARGS="$ARGS -hw=tty"
  fi
fi

if [ "$DPY" ]; then
  # check it is a valid TWDISPLAY!
  DPY=`twfindtwin "$DPY"`
else
  DPY=`twfindtwin`
fi

if [ "$DPY" ]; then
  echo twstart: detected twin running on "$DPY"
  exec twdisplay -twin@"$DPY" $ARGS
else
  exec twin $ARGS
fi

