# Copyright (C) 2000 by Massimiliano Ghilardi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
#
#
# Makefile for twin themes
#
#

SUBDIRS=hw_gfx

all: build-subdirs


#
# common rules
#
include $(T)include/version.in
-include $(B)makeautoconf
include $(T)makerules.in



