#
# Makefile for twin themes
#
#

TOPDIR=..
THISDIR=$(TOPDIR)/themes

SUBDIRS=hw_gfx

all: build-subdirs


#
# common rules
#
include $(TOPDIR)/include/makeversion
-include $(TOPDIR)/makeautoconf
include $(TOPDIR)/makerules



