#
# Makefile for the various libraries
#
TOPDIR=..
THISDIR=$(TOPDIR)/libs

SUBDIRS=$(wildcard lib*)

all: build-subdirs

build-dir-libTT: build-dir-libTutf build-dir-libTw


include $(TOPDIR)/makerules

