#
# Makefile for the various libraries
#
TOPDIR=..
THISDIR=$(TOPDIR)/libs

#SUBDIRS=$(filter-out libTT, $(wildcard lib*))
SUBDIRS=$(wildcard lib*)

all: subdirs

dir-libTT: dir-libTutf dir-libTw


include $(TOPDIR)/makerules

