# Copyright (C) 2000 by Massimiliano Ghilardi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
#
#
# Makefile for the various libraries
#

SUBDIRS=$(wildcard lib*)

all: build-subdirs

build-dir-libTT: build-dir-libTutf build-dir-libTw


include $(T)makerules.in

